using System;using System.Collections.Generic;using System.Linq;
using gazegallery.PluginApi;using System.Windows;using System.Windows.Controls;using System.Windows.Ink;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Shapes;
namespace SimpleDraw;
public sealed class Plugin:IGazegalleryPlugin {
 public string Id=>"gazegallery.simple-draw";public string Name=>"Simple Draw";public string Description=>"Brush, straight lines and erasing on a separate layer; save a copy or cancel. Five strokes of undo.";
 IPluginHost host=null!;public void Initialize(IPluginHost host){this.host=host;host.RegisterCommand("Draw on image",Start,"U",Description);}
 public static Color SampleColor(BitmapSource source,InkPresenter presenter,Point point){int x=(int)Math.Floor(point.X),y=(int)Math.Floor(point.Y);if(x<0||y<0||x>=source.PixelWidth||y>=source.PixelHeight)return Color.FromRgb(1,239,108);var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){dc.PushClip(new RectangleGeometry(new Rect(0,0,1,1)));dc.PushTransform(new TranslateTransform(-x,-y));dc.DrawImage(source,new Rect(0,0,source.PixelWidth,source.PixelHeight));presenter.Strokes.Draw(dc);dc.Pop();dc.Pop();}var pixel=new RenderTargetBitmap(1,1,96,96,PixelFormats.Pbgra32);pixel.Render(visual);byte[] data=new byte[4];pixel.CopyPixels(data,4,0);double alpha=data[3]/255.0;return alpha<=0?Color.FromRgb(1,239,108):Color.FromRgb((byte)Math.Min(255,data[2]/alpha),(byte)Math.Min(255,data[1]/alpha),(byte)Math.Min(255,data[0]/alpha));}
 void Start(){var source=host.CurrentImage;if(source==null)return;int w=source.PixelWidth,h=source.PixelHeight;
  var overlay=new Canvas{Focusable=true,Background=Brushes.Transparent,ClipToBounds=true};var presenter=new InkPresenter{IsHitTestVisible=false,Width=w,Height=h,ClipToBounds=true};overlay.Children.Add(presenter);
  var circle=new Ellipse{Stroke=Brushes.White,StrokeThickness=1,Fill=Brushes.Transparent,IsHitTestVisible=false};overlay.Children.Add(circle);var preview=new Line{IsHitTestVisible=false,Visibility=Visibility.Collapsed,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round};overlay.Children.Add(preview);
  var undo=new List<StrokeCollection>();Stroke? drawing=null;Point start=default,last=default;bool active=false,pan=false;string tool="Brush";double size=8;Color color=Color.FromRgb(1,239,108);Color[] palette={color,Colors.Black};int activeColor=0;var swatches=new List<Border>();void UpdateSwatches(){for(int n=0;n<swatches.Count;n++){swatches[n].Background=new SolidColorBrush(palette[n]);swatches[n].BorderThickness=new Thickness(n==activeColor?2:1);}color=palette[activeColor];}
  void Position(){var origin=host.ViewerPoint(new Point());presenter.RenderTransform=new MatrixTransform(host.ImageScale,0,0,host.ImageScale,origin.X,origin.Y);}
  void Pointer(Point p){double diameter=Math.Max(1,size*host.ImageScale);circle.Width=circle.Height=diameter;Canvas.SetLeft(circle,p.X-diameter/2);Canvas.SetTop(circle,p.Y-diameter/2);circle.Visibility=tool=="Line"?Visibility.Collapsed:Visibility.Visible;}
  DrawingAttributes Attributes()=>new(){Color=color,Width=size,Height=size,FitToCurve=false,IgnorePressure=true};
  void Remember(){undo.Add(new StrokeCollection(presenter.Strokes));if(undo.Count>5)undo.RemoveAt(0);}
  void Erase(Point a,Point b){var shape=new EllipseStylusShape(size,size);foreach(var stroke in presenter.Strokes.ToArray()){if(!stroke.HitTest(new[]{a,b},shape))continue;var pieces=stroke.GetEraseResult(new[]{a,b},shape);presenter.Strokes.Remove(stroke);presenter.Strokes.Add(pieces);}}
  overlay.MouseLeftButtonDown+=(_,e)=>{overlay.Focus();last=e.GetPosition(overlay);start=host.ImagePoint(last);if(Keyboard.Modifiers.HasFlag(ModifierKeys.Alt)){palette[activeColor]=SampleColor(source,presenter,start);UpdateSwatches();e.Handled=true;return;}pan=Keyboard.IsKeyDown(Key.Space);active=true;overlay.CaptureMouse();if(!pan){Remember();if(tool=="Brush"){drawing=new Stroke(new StylusPointCollection{new StylusPoint(start.X,start.Y)},Attributes());presenter.Strokes.Add(drawing);}else if(tool=="Eraser")Erase(start,start);else{preview.Stroke=new SolidColorBrush(color);preview.StrokeThickness=size*host.ImageScale;preview.X1=preview.X2=last.X;preview.Y1=preview.Y2=last.Y;preview.Visibility=Visibility.Visible;}}e.Handled=true;};
  overlay.MouseMove+=(_,e)=>{var p=e.GetPosition(overlay);Pointer(p);if(!active)return;if(pan){host.PanBy(p-last);Position();}else{var point=host.ImagePoint(p);if(tool=="Brush"&&drawing!=null)drawing.StylusPoints.Add(new StylusPoint(point.X,point.Y));else if(tool=="Eraser")Erase(host.ImagePoint(last),point);else if(tool=="Line"){preview.X2=p.X;preview.Y2=p.Y;}}last=p;e.Handled=true;};
  overlay.MouseLeftButtonUp+=(_,e)=>{if(active&&!pan&&tool=="Line"){var end=host.ImagePoint(e.GetPosition(overlay));presenter.Strokes.Add(new Stroke(new StylusPointCollection{new StylusPoint(start.X,start.Y),new StylusPoint(end.X,end.Y)},Attributes()));}active=false;drawing=null;preview.Visibility=Visibility.Collapsed;overlay.ReleaseMouseCapture();e.Handled=true;};
  overlay.MouseWheel+=(_,e)=>{if(!active){host.ZoomAt(e.GetPosition(overlay),e.Delta);Position();Pointer(e.GetPosition(overlay));}e.Handled=true;};overlay.SizeChanged+=(_,_)=>Position();overlay.MouseLeave+=(_,_)=>circle.Visibility=Visibility.Collapsed;
  var controls=new WrapPanel();Button Button(string label,Action action){var b=new Button{Content=label,Margin=new Thickness(3),Padding=new Thickness(8,4,8,4)};b.Click+=(_,_)=>action();controls.Children.Add(b);return b;}
  for(int n=0;n<2;n++){int slot=n;var swatch=new Border{Width=24,Height=24,CornerRadius=new CornerRadius(5),BorderBrush=Brushes.Gainsboro,Margin=new Thickness(3),Cursor=Cursors.Hand};swatch.MouseLeftButtonDown+=(_,e)=>{activeColor=slot;UpdateSwatches();e.Handled=true;};swatch.MouseRightButtonUp+=(_,e)=>{using var dialog=new System.Windows.Forms.ColorDialog{FullOpen=true,Color=System.Drawing.Color.FromArgb(palette[slot].R,palette[slot].G,palette[slot].B)};if(dialog.ShowDialog()==System.Windows.Forms.DialogResult.OK){palette[slot]=Color.FromRgb(dialog.Color.R,dialog.Color.G,dialog.Color.B);UpdateSwatches();}e.Handled=true;};swatches.Add(swatch);controls.Children.Add(swatch);}UpdateSwatches();var modes=new List<Button>();foreach(string mode in new[]{"Brush","Line","Eraser"}){var b=Button(mode,()=>{tool=mode;foreach(var button in modes)button.Opacity=Equals(button.Content,mode)?1:.5;});b.Opacity=mode==tool?1:.5;modes.Add(b);}
  controls.Children.Add(new TextBlock{Text="Size",Foreground=Brushes.Gainsboro,VerticalAlignment=VerticalAlignment.Center});var input=new TextBox{Text="8",Width=55,Margin=new Thickness(5),Foreground=Brushes.Gainsboro,CaretBrush=Brushes.Gainsboro,Background=new SolidColorBrush(Color.FromRgb(35,38,42)),VerticalContentAlignment=VerticalAlignment.Center};var slider=new Slider{Minimum=-1,Maximum=1,Value=0,Width=100,Margin=new Thickness(5)};double sizeBase=8;bool sync=false;
  input.TextChanged+=(_,_)=>{if(sync||!double.TryParse(input.Text,out double value)||value<.5||value>2048)return;sync=true;size=sizeBase=value;slider.Value=0;sync=false;};slider.ValueChanged+=(_,_)=>{if(sync)return;sync=true;size=sizeBase*Math.Pow(2,slider.Value);input.Text=size.ToString("0.##");sync=false;};controls.Children.Add(input);controls.Children.Add(slider);

  void Undo(){if(undo.Count==0)return;presenter.Strokes=undo[^1];undo.RemoveAt(undo.Count-1);}Button("Undo stroke",Undo);Button("Clear all",()=>{if(presenter.Strokes.Count==0)return;Remember();presenter.Strokes.Clear();active=false;drawing=null;preview.Visibility=Visibility.Collapsed;overlay.ReleaseMouseCapture();});Button("Cancel",host.EndOverlay);Button("Apply — save copy…",async()=>{var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){dc.DrawImage(source,new Rect(0,0,w,h));dc.PushClip(new RectangleGeometry(new Rect(0,0,w,h)));presenter.Strokes.Draw(dc);dc.Pop();}var output=new RenderTargetBitmap(w,h,96,96,PixelFormats.Pbgra32);output.Render(visual);output.Freeze();if(await host.SaveCopyAsync(output))host.EndOverlay();});host.BeginOverlay(overlay,controls,()=>{});host.SetOverlayUndo(Undo);Position();
 }
}
