using System;using System.Collections.Generic;using System.Linq;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Shapes;using gazegallery.PluginApi;
namespace gazegalleryColorPicker;
public sealed record Sample(Color Color,int X,int Y,double Radius);
public sealed class Plugin:IGazegalleryPlugin {
 public string Id=>"gazegallery.color-picker";public string Name=>"Color Picker";public string Description=>"Pick a pixel or average a circle. Keep three samples with RGB, HEX, HSL, HSV and RGB-derived CMYK.";IPluginHost host=null!;
 public void Initialize(IPluginHost value){host=value;host.RegisterCommand("Pick color",Start,"Shift+P",Description);}
 public static Color Average(BitmapSource source,int x,int y,double radius){int r=(int)Math.Ceiling(radius),left=Math.Max(0,x-r),top=Math.Max(0,y-r),right=Math.Min(source.PixelWidth-1,x+r),bottom=Math.Min(source.PixelHeight-1,y+r);var bitmap=new FormatConvertedBitmap(source,PixelFormats.Bgra32,null,0);int stride=(right-left+1)*4;var bytes=new byte[stride*(bottom-top+1)];bitmap.CopyPixels(new Int32Rect(left,top,right-left+1,bottom-top+1),bytes,stride,0);double red=0,green=0,blue=0,total=0;for(int py=top;py<=bottom;py++)for(int px=left;px<=right;px++){if(radius>0&&(px-x)*(px-x)+(py-y)*(py-y)>radius*radius)continue;int p=(py-top)*stride+(px-left)*4;double alpha=bytes[p+3]/255d;red+=bytes[p+2]*alpha;green+=bytes[p+1]*alpha;blue+=bytes[p]*alpha;total+=alpha;}return total==0?Colors.Transparent:Color.FromRgb((byte)Math.Round(red/total),(byte)Math.Round(green/total),(byte)Math.Round(blue/total));}
 public static string Describe(Sample sample){var c=sample.Color;double r=c.R/255d,g=c.G/255d,b=c.B/255d,max=Math.Max(r,Math.Max(g,b)),min=Math.Min(r,Math.Min(g,b)),d=max-min,h=d==0?0:max==r?60*((g-b)/d%6):max==g?60*((b-r)/d+2):60*((r-g)/d+4);if(h<0)h+=360;double l=(max+min)/2,s=d==0?0:d/(1-Math.Abs(2*l-1)),sv=max==0?0:d/max,k=1-max,cyan=max==0?0:(max-r)/max,magenta=max==0?0:(max-g)/max,yellow=max==0?0:(max-b)/max;return $"Pixel ({sample.X}, {sample.Y}) · radius {sample.Radius:0.##} px\nRGB {c.R}, {c.G}, {c.B} · HEX #{c.R:X2}{c.G:X2}{c.B:X2}\nHSL {h:0.#}°, {s*100:0.#}%, {l*100:0.#}%\nHSV {h:0.#}°, {sv*100:0.#}%, {max*100:0.#}%\nCMYK {cyan*100:0.#}%, {magenta*100:0.#}%, {yellow*100:0.#}%, {k*100:0.#}% (RGB-derived)";}
 void Start(){var source=host.CurrentImage;if(source==null)return;var overlay=new Canvas{Background=Brushes.Transparent,Focusable=true};var circle=new Ellipse{Stroke=Brushes.Gainsboro,StrokeThickness=1,Fill=Brushes.Transparent,IsHitTestVisible=false};overlay.Children.Add(circle);var controls=new StackPanel();var row=new WrapPanel();controls.Children.Add(row);var history=new List<Sample>();var swatches=new WrapPanel();row.Children.Add(swatches);var result=new TextBlock{Foreground=Brushes.Gainsboro,FontFamily=new FontFamily("Consolas"),FontSize=11,Margin=new Thickness(8),Text="Click an image to pick a color"};controls.Children.Add(new Border{CornerRadius=new CornerRadius(5),Background=new SolidColorBrush(Color.FromRgb(35,38,42)),Child=result});bool average=false;double radius=8,basis=8;bool sync=false,pan=false;Point last=new();
 Button Button(string label,Action action){var b=new Button{Content=label,Margin=new Thickness(3),Padding=new Thickness(8,4,8,4)};b.Click+=(_,_)=>action();row.Children.Add(b);return b;}
 var mode=new CheckBox{Content="Circle average",Margin=new Thickness(6),Foreground=Brushes.Gainsboro};mode.Checked+=(_,_)=>average=true;mode.Unchecked+=(_,_)=>average=false;row.Children.Add(mode);row.Children.Add(new TextBlock{Text="Radius",Foreground=Brushes.Gainsboro,VerticalAlignment=VerticalAlignment.Center});var input=new TextBox{Text="8",Width=55,Margin=new Thickness(5),Foreground=Brushes.Gainsboro,CaretBrush=Brushes.Gainsboro,Background=new SolidColorBrush(Color.FromRgb(35,38,42))};var slider=new Slider{Minimum=-1,Maximum=1,Value=0,Width=100,Margin=new Thickness(5)};input.TextChanged+=(_,_)=>{if(sync||!double.TryParse(input.Text,out var value)||value<.5||value>2048)return;sync=true;radius=basis=value;slider.Value=0;sync=false;};slider.ValueChanged+=(_,_)=>{if(sync)return;sync=true;radius=basis*Math.Pow(2,slider.Value);input.Text=radius.ToString("0.##");sync=false;};row.Children.Add(input);row.Children.Add(slider);Button("Copy values",()=>Clipboard.SetText(result.Text));Button("Close",host.EndOverlay);
 void Select(Sample sample){result.Text=Describe(sample);foreach(Border box in swatches.Children)box.BorderThickness=new Thickness(ReferenceEquals(box.Tag,sample)?2:1);}
 overlay.MouseLeftButtonDown+=(_,e)=>{last=e.GetPosition(overlay);if(Keyboard.IsKeyDown(Key.Space)){pan=true;overlay.CaptureMouse();}else{var point=host.ImagePoint(last);int x=(int)Math.Floor(point.X),y=(int)Math.Floor(point.Y);if(x>=0&&y>=0&&x<source.PixelWidth&&y<source.PixelHeight){var sample=new Sample(Average(source,x,y,average?radius:0),x,y,average?radius:0);history.Insert(0,sample);if(history.Count>3)history.RemoveAt(3);swatches.Children.Clear();foreach(var value in history){var box=new Border{Tag=value,Width=28,Height=28,Background=new SolidColorBrush(value.Color),BorderBrush=Brushes.Gainsboro,CornerRadius=new CornerRadius(5),Margin=new Thickness(3),Cursor=Cursors.Hand};box.MouseLeftButtonDown+=(_,a)=>{Select(value);a.Handled=true;};swatches.Children.Add(box);}Select(sample);}}e.Handled=true;};overlay.MouseMove+=(_,e)=>{var point=e.GetPosition(overlay);if(pan){host.PanBy(point-last);last=point;}double size=average?radius*2*host.ImageScale:Math.Max(1,host.ImageScale);circle.Width=circle.Height=size;Canvas.SetLeft(circle,point.X-size/2);Canvas.SetTop(circle,point.Y-size/2);};overlay.MouseLeftButtonUp+=(_,e)=>{pan=false;overlay.ReleaseMouseCapture();e.Handled=true;};overlay.MouseWheel+=(_,e)=>{host.ZoomAt(e.GetPosition(overlay),e.Delta);e.Handled=true;};host.BeginOverlay(overlay,controls,()=>{});
 }
}
