using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Diagnostics;using System.Runtime.InteropServices;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using Microsoft.Win32;using gazegallery.PluginApi;
namespace gazegalleryWallpaper;
public sealed class Plugin:IGazegalleryPlugin {
 public string Id=>"gazegallery.wallpaper";public string Name=>"Wallpaper and lockscreen";public string Description=>"Frame the image for a selected screen, then set wallpaper or lockscreen.";IPluginHost host=null!;
 public void Initialize(IPluginHost host){this.host=host;host.RegisterCommand("Wallpaper / lockscreen",Start,"",Description);}
 static Window Dialog(string title,double height){var w=new Window{Owner=Application.Current.MainWindow,Title=title,Width=620,Height=height,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=new SolidColorBrush(Color.FromRgb(30,32,36)),Foreground=Brushes.Gainsboro,ShowInTaskbar=false};w.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Escape){e.Handled=true;w.Close();}};return w;}
 static Button Button(string text,Action action){var b=new Button{Content=text,Margin=new Thickness(4),Padding=new Thickness(10,5,10,5)};b.Click+=(_,_)=>action();return b;}
 void Start(){var image=host.CurrentImage;if(image==null)return;bool lockscreen=false;var choice=Dialog("Use image as…",180);var row=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};row.Children.Add(Button("Set as wallpaper",()=>choice.DialogResult=true));row.Children.Add(Button("Set as lockscreen",()=>{lockscreen=true;choice.DialogResult=true;}));row.Children.Add(Button("Cancel",choice.Close));choice.Content=row;if(choice.ShowDialog()!=true)return;
  var window=Dialog(lockscreen?"Lockscreen preview":"Wallpaper preview",630);var panel=new StackPanel{Margin=new Thickness(18)};panel.Children.Add(new TextBlock{Text="Screen / aspect ratio",Margin=new Thickness(5)});var screens=System.Windows.Forms.Screen.AllScreens;var screenNames=screens.Select(s=>$"{s.DeviceName} — {s.Bounds.Width} × {s.Bounds.Height}").ToArray();var choices=screenNames.Concat(new[]{"16:9","16:10","4:3","21:9","32:9","9:16"}).ToArray();var ratio=new ComboBox{ItemsSource=choices,SelectedIndex=0,Margin=new Thickness(5)};panel.Children.Add(ratio);
  var layout=new ComboBox{ItemsSource=new[]{"Fill","Fit","Stretch","Center","Tile","Span"},SelectedIndex=0,Margin=new Thickness(5)};panel.Children.Add(layout);var preview=new Image{Width=540,Height=304,Stretch=Stretch.Uniform,Cursor=Cursors.SizeAll};panel.Children.Add(preview);panel.Children.Add(new TextBlock{Text="Drag the preview to adjust framing. Saved images match the selected screen's resolution; custom ratios use a 1920px width.",TextWrapping=TextWrapping.Wrap,FontSize=11,Margin=new Thickness(5)});
  double zoom=1;Vector framing=new();Point down=default;Vector before=default;bool dragging=false;int width=1920,height=1080;
  void Dimensions(){if(ratio.SelectedIndex<screens.Length){var bounds=screens[ratio.SelectedIndex].Bounds;width=bounds.Width;height=bounds.Height;}else{var parts=((string)ratio.SelectedItem).Split(':');width=1920;height=(int)Math.Round(width*double.Parse(parts[1])/double.Parse(parts[0]));}if((string)layout.SelectedItem=="Span"){width=System.Windows.Forms.SystemInformation.VirtualScreen.Width;height=System.Windows.Forms.SystemInformation.VirtualScreen.Height;}}
  void Render(){Dimensions();double factor=Math.Min(540.0/width,310.0/height);preview.Width=width*factor;preview.Height=height*factor;preview.Source=Frame(image,Math.Max(1,(int)preview.Width),Math.Max(1,(int)preview.Height),(string)layout.SelectedItem,framing,width,zoom);}
  ratio.SelectionChanged+=(_,_)=>{framing=new();zoom=1;Render();};layout.SelectionChanged+=(_,_)=>{framing=new();zoom=1;Render();};preview.MouseLeftButtonDown+=(_,e)=>{down=e.GetPosition(preview);before=framing;dragging=true;preview.CaptureMouse();e.Handled=true;};preview.MouseMove+=(_,e)=>{if(!dragging)return;var delta=e.GetPosition(preview)-down;framing=new Vector(Math.Clamp(before.X+delta.X/Math.Max(1,preview.ActualWidth),-1,1),Math.Clamp(before.Y+delta.Y/Math.Max(1,preview.ActualHeight),-1,1));Render();e.Handled=true;};preview.MouseLeftButtonUp+=(_,e)=>{dragging=false;preview.ReleaseMouseCapture();e.Handled=true;};
  preview.MouseWheel+=(_,e)=>{Dimensions();{zoom=Math.Clamp(zoom*Math.Pow(1.15,e.Delta/120d),1,8);Render();}e.Handled=true;};var buttons=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Center};var apply=Button(lockscreen?"Set as lockscreen":"Set as wallpaper",()=>{});apply.Click+=async(_,_)=>{apply.IsEnabled=false;try{Dimensions();string mode=(string)layout.SelectedItem;if((long)width*height>64_000_000)throw new IOException("Selected screen layout exceeds 64 megapixels.");string dir=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"data","plugins","wallpaper"));Directory.CreateDirectory(dir);string file=Path.Combine(dir,lockscreen?"lockscreen.png":"wallpaper.bmp");var framed=Frame(image,width,height,mode,framing,width,zoom);BitmapEncoder encoder=lockscreen?new PngBitmapEncoder():new BmpBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(framed));using(var stream=File.Create(file))encoder.Save(stream);
   if(lockscreen){bool success=await SetLockscreen(file,dir);if(!success){host.Toast("Windows could not set the lockscreen. Choose the generated image in Personalization > Lock screen.");Process.Start(new ProcessStartInfo("explorer.exe","/select,\""+file+"\""){UseShellExecute=true});Process.Start(new ProcessStartInfo("ms-settings:lockscreen"){UseShellExecute=true});}else host.Toast("Lockscreen updated");}
   else{using var key=Registry.CurrentUser.OpenSubKey(@"Control Panel\Desktop",true)??throw new IOException("Windows desktop settings are unavailable.");key.SetValue("WallpaperStyle",mode=="Span"?"22":"2");key.SetValue("TileWallpaper","0");if(!SystemParametersInfo(20,0,file,3))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());host.Toast("Wallpaper updated");}window.Close();}catch(Exception ex){host.Toast(ex.Message);}finally{apply.IsEnabled=true;}};buttons.Children.Add(apply);buttons.Children.Add(Button("Cancel",window.Close));panel.Children.Add(buttons);window.Content=panel;Render();window.ShowDialog();
 }
 public static BitmapSource Frame(BitmapSource image,int width,int height,string mode,Vector offset,int screenWidth,double zoom=1){var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){var bounds=new Rect(0,0,width,height);dc.DrawRectangle(Brushes.Black,null,bounds);dc.PushClip(new RectangleGeometry(bounds));double sx=width/(double)image.PixelWidth,sy=height/(double)image.PixelHeight;double scale=mode=="Fit"?Math.Min(sx,sy):mode is "Center" or "Tile"?width/(double)screenWidth:Math.Max(sx,sy);scale*=zoom;double w=mode=="Stretch"?width:image.PixelWidth*scale,h=mode=="Stretch"?height:image.PixelHeight*scale;double x=(width-w)/2+offset.X*width,y=(height-h)/2+offset.Y*height;if(mode is "Fill" or "Span"){x=Math.Clamp(x,width-w,0);y=Math.Clamp(y,height-h,0);}else if(mode=="Fit"){x=Math.Clamp(x,Math.Min(0,width-w),Math.Max(0,width-w));y=Math.Clamp(y,Math.Min(0,height-h),Math.Max(0,height-h));}if(mode=="Tile"){var brush=new ImageBrush(image){TileMode=TileMode.Tile,ViewportUnits=BrushMappingMode.Absolute,Viewport=new Rect(x,y,w,h),Stretch=Stretch.Fill};dc.DrawRectangle(brush,null,bounds);}else dc.DrawImage(image,new Rect(x,y,w,h));dc.Pop();}var result=new RenderTargetBitmap(width,height,96,96,PixelFormats.Pbgra32);result.Render(visual);result.Freeze();return result;}
 public static string LockscreenScript(string file)=>@"
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Runtime.WindowsRuntime
[Windows.Storage.StorageFile, Windows.Storage, ContentType=WindowsRuntime] | Out-Null
[Windows.System.UserProfile.UserProfilePersonalizationSettings, Windows.System.UserProfile, ContentType=WindowsRuntime] | Out-Null
function Await($operation, $type) {
 $method = [System.WindowsRuntimeSystemExtensions].GetMethods() | Where-Object { $_.Name -eq 'AsTask' -and $_.IsGenericMethod -and $_.GetParameters().Count -eq 1 -and $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' } | Select-Object -First 1
 $task = $method.MakeGenericMethod($type).Invoke($null, @($operation))
 $task.GetAwaiter().GetResult()
}
try {
 if (-not [Windows.System.UserProfile.UserProfilePersonalizationSettings]::IsSupported()) { exit 2 }
 $file = Await ([Windows.Storage.StorageFile]::GetFileFromPathAsync('"+file.Replace("'","''")+@"')) ([Windows.Storage.StorageFile])
 $ok = Await ([Windows.System.UserProfile.UserProfilePersonalizationSettings]::Current.TrySetLockScreenImageAsync($file)) ([bool])
 if ($ok) { exit 0 } else { exit 2 }
} catch { exit 2 }
";
 static async Task<bool> SetLockscreen(string file,string dir){string script=Path.Combine(dir,"set-lockscreen.ps1");await File.WriteAllTextAsync(script,LockscreenScript(file),new System.Text.UTF8Encoding(true));var psi=new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),@"WindowsPowerShell\v1.0\powershell.exe")){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden};foreach(string arg in new[]{"-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",script})psi.ArgumentList.Add(arg);using var process=Process.Start(psi)!;try{using var timeout=new System.Threading.CancellationTokenSource(TimeSpan.FromSeconds(30));await process.WaitForExitAsync(timeout.Token);return process.ExitCode==0;}catch{try{process.Kill(true);}catch{}return false;}finally{try{File.Delete(script);}catch{}}}
 [DllImport("user32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool SystemParametersInfo(uint action,uint parameter,string value,uint flags);
}
