using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace gazegallery;
public partial class MainWindow {
 public double ToolbarHeight=>Mode=="viewer"?0:Math.Max(38,toolbar.ActualHeight);
 double lastToolbarHeight;
 void ResponsiveToolbar(){if(boardReturn==null)return;boardReturn.Visibility=Mode=="board"?Visibility.Visible:Visibility.Collapsed;boardReturn.HorizontalAlignment=HorizontalAlignment.Left;double left=folderPanel.Visibility==Visibility.Visible&&Mode!="board"?folderPanel.Width:180;if(toolbarHost.Child is Grid row){row.ColumnDefinitions[0].Width=new GridLength(left);row.ColumnDefinitions[2].Width=new GridLength(175);}toolbar.MaxWidth=Math.Max(200,root.ActualWidth-left-185);toolbar.UpdateLayout();if(Mode=="grid"&&Math.Abs(lastToolbarHeight-ToolbarHeight)>.5){lastToolbarHeight=ToolbarHeight;treeHeaderHeight=ToolbarHeight;View.LayoutTiles();RefreshTreeHeader();}if(foldersButton.Parent is FrameworkElement nav)nav.Visibility=Mode=="grid"&&folderPanel.Visibility!=Visibility.Visible?Visibility.Visible:Visibility.Collapsed;foldersButton.Visibility=Visibility.Visible;}
 public void DrawViewerExtras(DrawingContext dc){if(Mode!="viewer")return;DrawOverlays(dc);if(bufferingVideo&&View.Image==null){var label=OverlayText("Buffering video");label.TextAlignment=TextAlignment.Center;dc.DrawText(label,new Point(View.ActualWidth/2,View.ActualHeight/2+50));}DrawLargeDetail(dc);DrawSlideTimeline(dc);}
 string? RenamePrompt(string file){var w=Ui.Dialog(this,"Rename file",440,180);var panel=new StackPanel{Margin=new Thickness(16)};var row=new DockPanel();var extension=Ui.Label(Path.GetExtension(file),12);extension.VerticalAlignment=VerticalAlignment.Center;DockPanel.SetDock(extension,Dock.Right);row.Children.Add(extension);var input=Ui.Input(Path.GetFileNameWithoutExtension(file));row.Children.Add(input);panel.Children.Add(row);var save=Ui.Button("Rename",()=>w.DialogResult=true);save.IsDefault=true;panel.Children.Add(save);w.Content=panel;w.Loaded+=(_,_)=>{input.Focus();input.SelectAll();};return w.ShowDialog()==true?input.Text:null;}
 static readonly string[] colorNames={"Canvas","Panel","Text","Muted text","Menu","Hover","Accent","Outline","Selection"};
 static readonly string[][] palettes={new[]{"Charcoal","#181818","#222529","#E4E6E8","#A3ABB3","#222529","#3B434A","#A0B7B2","#42474D","#EFF0E1"},new[]{"Midnight","#101625","#182237","#DFE8FA","#91A2BC","#182237","#293B58","#82AEF2","#354766","#829CCA"},new[]{"Graphite","#202020","#292929","#E5E5E5","#AAAAAA","#292929","#444444","#B9C4CE","#505050","#AAA0C5"},new[]{"Forest","#131D18","#203128","#E0ECE3","#9EB7A5","#203128","#344B3D","#99C9AA","#405C4B","#88BBA0"},new[]{"Plum","#211822","#322434","#F0E1F0","#B7A0BB","#322434","#49384D","#C8A6D5","#614866","#D19AC0"},new[]{"Dusk","#201D2A","#302B3D","#EAE4F4","#AFA3C0","#302B3D","#49415B","#BCA7DF","#60536E","#B19DD2"},new[]{"Warm slate","#24211E","#342F2A","#F0E8DD","#BBAF9F","#342F2A","#4B433B","#D1B38A","#655849","#C89E87"},new[]{"Ocean","#101F25","#1C303A","#DBEDF2","#92AFB9","#1C303A","#2C4652","#85C8D5","#3C5D6B","#82B8C4"},new[]{"Paper","#E4E1DA","#F0EEE8","#282B31","#626975","#F0EEE8","#D2D9DC","#496C75","#ADB5B8","#AA7398"}};
 void ApplyPalette(){var fallback=palettes[0];for(int i=0;i<colorNames.Length;i++)if(!Config.Colors.ContainsKey(colorNames[i]))Config.Colors[colorNames[i]]=fallback[i+1];void Set(ref Brush brush,string key){if(brush.IsFrozen)brush=brush.CloneCurrentValue();if(brush is SolidColorBrush b)b.Color=(Color)ColorConverter.ConvertFromString(Config.Colors[key]);}Set(ref Ui.Selection,"Selection");var selection=(Color)ColorConverter.ConvertFromString(Config.Colors["Selection"]);if(Ui.SelectionTint.IsFrozen)Ui.SelectionTint=Ui.SelectionTint.CloneCurrentValue();((SolidColorBrush)Ui.SelectionTint).Color=Color.FromArgb(85,selection.R,selection.G,selection.B);Set(ref Ui.Canvas,"Canvas");Set(ref Ui.Bg,"Panel");Set(ref Ui.Fg,"Text");Set(ref Ui.Muted,"Muted text");Ui.CanvasColor=((SolidColorBrush)Ui.Canvas).Color;var resources=Application.Current.Resources;foreach(var pair in new[]{("Ink","Text"),("Panel","Menu"),("HoverColor","Hover"),("AccentColor","Accent"),("OutlineColor","Outline"),("MutedColor","Muted text")})resources[pair.Item1]=new SolidColorBrush((Color)ColorConverter.ConvertFromString(Config.Colors[pair.Item2]));if(View!=null){toolbarHost.Background=Ui.Bg;quickPanel.Background=Ui.Bg;View.GridVersion++;View.InvalidateVisual();}}
 static string RandomColor()=>$"#{Random.Shared.Next(256):X2}{Random.Shared.Next(256):X2}{Random.Shared.Next(256):X2}";
 UIElement ColorSettings(){var panel=new StackPanel{Margin=new Thickness(14)};panel.Children.Add(Ui.Label("Palette",14));var presets=new ComboBox{Margin=new Thickness(5)};var status=Ui.Label("Current colors",11);panel.Children.Add(presets);panel.Children.Add(status);var rows=new Dictionary<string,Button>();string? chosen=null;bool loading=false;void Choices(){loading=true;presets.ItemsSource=palettes.Select(p=>p[0]).Concat(Config.CustomPalettes.Keys.Order()).ToArray();presets.SelectedItem=chosen;loading=false;}
 void Refresh(bool modified){foreach(var pair in rows)pair.Value.Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString(Config.Colors[pair.Key]));ApplyPalette();status.Text=modified?"Modified — save as a custom palette to keep a named preset":chosen??"Current colors";}
 presets.SelectionChanged+=(_,_)=>{if(loading||presets.SelectedItem is not string name)return;chosen=name;var builtIn=palettes.FirstOrDefault(p=>p[0]==name);if(builtIn!=null){for(int i=0;i<colorNames.Length;i++)Config.Colors[colorNames[i]]=builtIn[i+1];}else if(Config.CustomPalettes.TryGetValue(name,out var colors))Config.Colors=new(colors);Refresh(false);};var actions=new StackPanel{Orientation=Orientation.Horizontal};actions.Children.Add(Ui.Button("Save as custom…",()=>{var name=Ui.Prompt(this,"Custom palette name",chosen??"")?.Trim();if(string.IsNullOrEmpty(name))return;if(palettes.Any(p=>p[0].Equals(name,StringComparison.OrdinalIgnoreCase))){Toast("Choose a name different from the built-in palettes");return;}if(Config.CustomPalettes.ContainsKey(name)&&!Ui.Confirm(this,"Replace custom palette?",name,"Replace"))return;Config.CustomPalettes[name]=new(Config.Colors);chosen=name;Config.Save();Choices();Refresh(false);}));actions.Children.Add(Ui.Button("Delete custom",()=>{if(chosen==null||!Config.CustomPalettes.ContainsKey(chosen))return;Config.CustomPalettes.Remove(chosen);chosen=null;Config.Save();Choices();Refresh(false);}));panel.Children.Add(actions);panel.Children.Add(Ui.Label("Choose a swatch to customize. OLED overrides the canvas only.",12));panel.Children.Add(Ui.Button("Random all",()=>{foreach(var color in colorNames)Config.Colors[color]=RandomColor();Refresh(true);}));foreach(var name in colorNames){var row=new StackPanel{Orientation=Orientation.Horizontal};row.Children.Add(new TextBlock{Text=name,Width=180,Foreground=Ui.Fg,VerticalAlignment=VerticalAlignment.Center});var swatch=Ui.Button("Choose…",()=>{using var picker=new System.Windows.Forms.ColorDialog{FullOpen=true};var c=(Color)ColorConverter.ConvertFromString(Config.Colors[name]);picker.Color=System.Drawing.Color.FromArgb(c.R,c.G,c.B);if(picker.ShowDialog()==System.Windows.Forms.DialogResult.OK){Config.Colors[name]=$"#{picker.Color.R:X2}{picker.Color.G:X2}{picker.Color.B:X2}";Refresh(true);}});swatch.Width=120;rows[name]=swatch;row.Children.Add(swatch);row.Children.Add(Ui.Button("Random",()=>{Config.Colors[name]=RandomColor();Refresh(true);}));panel.Children.Add(row);}Choices();Refresh(false);return new ScrollViewer{Content=panel};}
}
