using System;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace gazegallery;
public static class BackgroundAnalysis32 {
 public static Color EdgeColor(BitmapSource source){double f=Math.Min(1,96d/Math.Max(source.PixelWidth,source.PixelHeight));BitmapSource small=source;if(f<1){small=new TransformedBitmap(source,new ScaleTransform(f,f));small.Freeze();}var bytes=PixelAnalysis.Pixels(small,out int stride);var bins=new Dictionary<int,(long Weight,long R,long G,long B)>();void Add(int x,int y){int p=y*stride+x*4;int a=bytes[p+3];if(a<32)return;int r=bytes[p+2],g=bytes[p+1],b=bytes[p],key=(r>>4)<<8|(g>>4)<<4|(b>>4);bins.TryGetValue(key,out var n);bins[key]=(n.Weight+a,n.R+(long)r*a,n.G+(long)g*a,n.B+(long)b*a);}for(int x=0;x<small.PixelWidth;x++){Add(x,0);if(small.PixelHeight>1)Add(x,small.PixelHeight-1);}for(int y=1;y<small.PixelHeight-1;y++){Add(0,y);if(small.PixelWidth>1)Add(small.PixelWidth-1,y);}if(bins.Count==0)return Color.FromRgb(24,24,24);var best=bins.Values.OrderByDescending(n=>n.Weight).First();return Color.FromRgb((byte)(best.R/best.Weight),(byte)(best.G/best.Weight),(byte)(best.B/best.Weight));}
}
public partial class MainWindow {
 Brush? background32Color;BitmapSource? background32Source,background32Blur;string background32Mode="";int background32Epoch;bool background32Pending;
 void AddBackgroundChoices32(ContextMenu menu){menu.Items.Add(new Separator());menu.Items.Add(new MenuItem{Header="Background",IsEnabled=false});foreach(string name in new[]{"Solid Color","Auto","Blur","Checkerboard"}){var i=new MenuItem{Header=name,IsCheckable=true,IsChecked=Config.ViewerBackground==name,InputGestureText=Config.ViewerBackground==name?"✓":""};i.Click+=(_,_)=>{Config.ViewerBackground=name;background32Source=null;Config.Save();View.InvalidateVisual();RefreshBackground32();};menu.Items.Add(i);}}
 async void RefreshBackground32(){if(Mode!="viewer"||preparingImage33)return;var image=sourceImage??View.Image;if(currentMotion||image==null||Config.ViewerBackground is "Solid Color" or "Checkerboard"){background32Color=null;background32Blur=null;background32Source=null;background32Epoch++;return;}if(background32Mode!=Config.ViewerBackground||!ReferenceEquals(background32Source,image)){background32Color=null;background32Blur=null;}else return;if(background32Pending)return;background32Pending=true;int token=++background32Epoch;string mode=Config.ViewerBackground;try{var prepared=await Sta.Run(()=>{Brush brush=mode=="Auto"?new SolidColorBrush(BackgroundAnalysis32.EdgeColor(image)):new ImageBrush(BlurredPreview(image));brush.Freeze();return brush;});if(token!=background32Epoch||Mode!="viewer"||currentMotion||!ReferenceEquals(image,sourceImage??View.Image)||Config.ViewerBackground!=mode)return;background32Source=image;background32Mode=mode;if(prepared is ImageBrush b)background32Blur=(BitmapSource)b.ImageSource;else background32Color=prepared;View.InvalidateVisual();}catch(Exception e){Paths.Log("viewer-background",e.Message);}finally{background32Pending=false;}}
 public void DrawBackground32(DrawingContext dc){if(Config.ViewerBackground!="Blur"||currentMotion||background32Blur==null)return;double f=Math.Max(View.ActualWidth/background32Blur.PixelWidth,View.ActualHeight/background32Blur.PixelHeight);dc.PushOpacity(.48);dc.DrawImage(background32Blur,new Rect((View.ActualWidth-background32Blur.PixelWidth*f)/2,(View.ActualHeight-background32Blur.PixelHeight*f)/2,background32Blur.PixelWidth*f,background32Blur.PixelHeight*f));dc.Pop();}
}
public static class WindowSizing32 {
 public static Rect Resize(Rect old,double area,double aspect,Rect monitor){double w=Math.Sqrt(Math.Max(1,area)*aspect),h=w/aspect,maxW=Math.Max(32,monitor.Width*.95),maxH=Math.Max(32,monitor.Height*.95),f=Math.Min(1,Math.Min(maxW/w,maxH/h));w=Math.Clamp(w*f,32,maxW);h=Math.Clamp(h*f,32,maxH);double cx=old.X+old.Width/2,cy=old.Y+old.Height/2;return new Rect(Math.Clamp(cx-w/2,monitor.Left,monitor.Right-w),Math.Clamp(cy-h/2,monitor.Top,monitor.Bottom-h),w,h);}
}
