using System;using System.Windows;using System.Windows.Controls;using System.Windows.Input;
namespace gazegallery;
public partial class MainWindow {
 CheckBox? cropRatioToggle;
 bool CropRatioActive{get{if(Config.CropRatioLock&&Keyboard.Modifiers.HasFlag(ModifierKeys.Shift)){Config.CropRatioLock=false;if(cropRatioToggle!=null)cropRatioToggle.IsChecked=false;Config.Save();Toast("aspect ratio unlocked");}return Config.CropRatioLock;}}
 void AddCropRatios(Panel panel){panel.Children.Add(Ui.Button("Aspect ratio…",CropRatioMenu));cropRatioToggle=new CheckBox{Content="Lock aspect ratio",IsChecked=Config.CropRatioLock,Foreground=Ui.Fg,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(5)};cropRatioToggle.Checked+=(_,_)=>{Config.CropRatioLock=true;Config.Save();};cropRatioToggle.Unchecked+=(_,_)=>{Config.CropRatioLock=false;Config.Save();};panel.Children.Add(cropRatioToggle);}
 void CropRatioMenu(){var menu=new ContextMenu();foreach(var pair in new[]{("1:1 (Square)",1d),("9:16",9d/16),("16:9",16d/9),("4:3",4d/3),("Custom…",0d)}){var item=new MenuItem{Header=pair.Item1};item.Click+=(_,_)=>{double value=pair.Item2;if(value==0){var result=Ui.Prompt(this,"Custom width:height ratio","1:1");var parts=result?.Split(':');if(parts==null||parts.Length!=2||!double.TryParse(parts[0],out double w)||!double.TryParse(parts[1],out double h)||w<=0||h<=0)return;value=w/h;}Config.CropRatio=value;Config.CropRatioLock=true;if(cropRatioToggle!=null)cropRatioToggle.IsChecked=true;Config.Save();if(View.CropRect.IsEmpty&&View.Image!=null){double cw=View.Image.PixelWidth*.5,ch=cw/value;if(ch>View.Image.PixelHeight*.5){ch=View.Image.PixelHeight*.5;cw=ch*value;}View.CropRect=new Rect((View.Image.PixelWidth-cw)/2,(View.Image.PixelHeight-ch)/2,cw,ch);View.InvalidateVisual();}if(!View.CropRect.IsEmpty){var r=View.CropRect;View.CropRect=new Rect(r.X,r.Y,r.Width,r.Width/value);if(Cropping)ConstrainViewerCrop();View.InvalidateVisual();}};menu.Items.Add(item);}menu.IsOpen=true;}
 Rect CropDrag(Point start,Point end){if(!CropRatioActive)return new Rect(start,end);double width=Math.Abs(end.X-start.X),height=Math.Abs(end.Y-start.Y);if(width/Config.CropRatio>height)height=width/Config.CropRatio;else width=height*Config.CropRatio;return new Rect(start,new Point(start.X+(end.X<start.X?-width:width),start.Y+(end.Y<start.Y?-height:height)));}
 Rect CropResize(Rect original,Point start,Point end,int handle){var r=GeometryRules.Resize(original,start,end,handle,false);if(!CropRatioActive)return r;double w=r.Width,h=r.Height;if(handle is 4 or 6)w=h*Config.CropRatio;else h=w/Config.CropRatio;return new Rect(handle is 0 or 3 or 7?original.Right-w:r.X,handle is 0 or 1 or 4?original.Bottom-h:r.Y,w,h);}
 void GapMenu(){var w=Ui.Dialog(this,"Collage gap",320,180);var p=new StackPanel{Margin=new Thickness(16)};p.Children.Add(Ui.Label("Gap (0–1000 px); used by next Pack or Align",12));var input=Ui.Input(Config.CollageGap.ToString());input.Width=100;p.Children.Add(input);var row=new WrapPanel();row.Children.Add(Ui.Button("Save",()=>{if(double.TryParse(input.Text,out double gap)&&gap>=0&&gap<=1000){Config.CollageGap=gap;Config.Save();w.Close();}}));row.Children.Add(Ui.Button("Default",()=>input.Text="8"));row.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(row);w.Content=p;w.ShowDialog();}
}
