using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
namespace gazegallery;
public partial class MainWindow {
 public async Task VerifyRecycleOnly(){string dir=Path.Combine(Paths.Test,"_testing","recycle-check-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var log=new List<string>();var ops=new FileOperations();try{for(int round=0;round<20;round++){var e=new UndoEntry();for(int n=0;n<3;n++){string path=Path.Combine(dir,$"disposable-{round}-{n}.txt");File.WriteAllText(path,$"gazegallery disposable round {round} item {n}");e.Changes.Add(await ops.Trash(path));if(File.Exists(path))throw new Exception("Source still present after recycling");}ops.Commit(e);await ops.Undo();for(int n=0;n<3;n++){string path=Path.Combine(dir,$"disposable-{round}-{n}.txt");if(File.ReadAllText(path)!=$"gazegallery disposable round {round} item {n}")throw new Exception("Restore content mismatch");}log.Add($"PASS batch {round+1}: three files recycled and restored exactly");}log.Add("PASS: 60 trash/restore operations, 20 batch undos");}catch(Exception ex){log.Add(ex.ToString());}finally{ops.Close();File.WriteAllLines(Path.Combine(Paths.Logs,"recycle-check.txt"),log);shutdown=true;Close();}}
 bool verifyNoLoop;
 async Task VerifyDaily(List<object> report,Action<bool,string> check,string work){
  string seed=Path.Combine(Paths.Test,"small_mario.png"),src=Path.Combine(work,"copy-me.png"),dest=Path.Combine(work,"copies");File.Copy(seed,src,true);Directory.CreateDirectory(dest);await Open(src);int undo=Operations.Count;quickCopy=true;await QuickTransfer(dest);check(current==src&&File.Exists(src)&&File.Exists(Path.Combine(dest,"copy-me.png")),"Quick copy retains source and current image");check(Operations.Count==undo,"Quick copy does not create undo entry");quickCopy=false;
  await SetMode("grid");Config.Names=false;View.LayoutTiles();View.Scroll=10;ToggleNames();check(View.Scroll>=0,"Name reflow preserves valid scroll anchor");ShowFolders();await NavigateFolder(Folder);check(Mode=="grid"&&folderPanel.Visibility==Visibility.Visible,"Current folder click retains mode and panel");ShowFolders();await SetMode("board");await ImportBoard(Enumerable.Repeat(seed,7),new Point(180,220));check(View.Board.Count==7&&View.Board.All(i=>i.Rect.Width*View.BoardScale<=View.ActualWidth*.6+.01&&i.Rect.Height*View.BoardScale<=View.ActualHeight*.6+.01),"Collage imports fit sixty percent viewport");CompactPack();bool overlap=false;for(int i=0;i<View.Board.Count;i++)for(int j=i+1;j<View.Board.Count;j++)overlap|=View.Board[i].Rect.IntersectsWith(View.Board[j].Rect);check(!overlap,"Compact pack has no overlaps");var seven=View.Board.Select(i=>i.Clone()).ToList();for(int n=7;n<50;n++){var item=seven[n%7].Clone();item.Rect=new Rect(0,0,40+(n*53)%470,40+(n*79)%650);View.Board.Add(item);}var packClock=Stopwatch.StartNew();CompactPack();report.Add(new{metric="pack_50_ms",value=packClock.Elapsed.TotalMilliseconds});check(View.Board.Count==50,"Packing keeps all fifty images");View.Board=seven;var first=View.Board[0];var rect=first.Rect;FocusBoard(first);check(first.Rect==rect,"Collage focus moves camera only");TryBoardNavigate(Config.Keys["Next"][0]);check(focusedBoard?.ImportOrder==View.Board.OrderBy(i=>i.ImportOrder).ElementAt(1).ImportOrder,"Focused navigation follows import order");View.BoardSelection.Clear();View.BoardSelection.Add(first);await StartBoardCrop();View.CropRect=new Rect(2,2,10,12);await ApplyBoardCrop();check(first.Edited&&first.Image.PixelWidth==10&&first.Image.PixelHeight==12,"Collage crop changes local pixels");ResetBoardSize();check(first.Rect.Width==10&&first.Rect.Height==12,"Reset size honors crop full pixel dimensions");await Undo();await Undo();check(!View.Board[0].Edited,"Collage crop undo restores image");check(File.ReadAllBytes(seed).SequenceEqual(File.ReadAllBytes(src)),"Collage crop leaves original unchanged");ReleaseBoard();Mode="viewer";
  if(Environment.GetCommandLineArgs().Contains("--no-troublesome"))return;verifyNoLoop=true;try{foreach(var path in Directory.GetFiles(Path.Combine(Paths.Test,"troublesome")).Where(Paths.Motion)){await Open(path);var wait=Stopwatch.StartNew();while(video!=null&&!video.Ended&&wait.ElapsedMilliseconds<26000)await Task.Delay(10);check(View.Image!=null,"Troublesome clip shows image: "+Path.GetFileName(path));report.Add(new{metric="troublesome_playback",file=Path.GetFileName(path),elapsedMs=wait.Elapsed.TotalMilliseconds,ended=video?.Ended,frames=video?.PresentationSamples.ToArray(),frameIds=video?.PresentationFrameIds.ToArray()});check(video?.Ended==true,"Troublesome clip reaches end: "+Path.GetFileName(path));var frame=View.Image;await ShowIndex(Index,false,true);check(View.Image!=null,"Loop restart retains a visible image");await StopVideo();}}finally{verifyNoLoop=false;}
 }
}
