using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace gazegallery;
public partial class MainWindow {
 public bool GridLoading;int scrollKey;Key scrollHeldKey;double lastScrollTick;bool quickCopy;public BoardItem? BoardCropItem;BitmapSource? boardCropSource;Point boardCropStart;Rect boardCropBefore;int boardCropHandle;bool boardCropDrag;BoardItem? focusedBoard;double overviewScale;Vector overviewPan;long importSequence;
 void ToggleAutoscroll(){autoScroll=!autoScroll;if(autoButton!=null)autoButton.Content=autoScroll?"Stop scroll":"Autoscroll";lastScrollTick=motionClock.Elapsed.TotalSeconds;View.InvalidateVisual();}
 void CopyGridFiles(){var files=Selection();if(files.Length==0)return;var list=new StringCollection();list.AddRange(files);Clipboard.SetFileDropList(list);Toast($"Copied {files.Length} file(s) to clipboard");}
 void ToggleNames(){int anchor=Enumerable.Range(0,View.Tiles.Count).FirstOrDefault(i=>View.GridEnd35(View.Tiles[i])>=View.Scroll+38);double offset=anchor<View.Tiles.Count?View.GridStart35(View.Tiles[anchor])-View.Scroll:0;Config.Names=!Config.Names;Config.Save();View.LayoutTiles();if(anchor<View.Tiles.Count)View.Scroll=Math.Max(0,View.GridStart35(View.Tiles[anchor])-offset);View.InvalidateVisual();}
 void AdvanceScroll(){if(focusSuspended34)return;double now=motionClock.Elapsed.TotalSeconds,dt=Math.Clamp(now-lastScrollTick,0,.05);lastScrollTick=now;if(Mode!="grid")return;if(GridLoading){View.InvalidateVisual();return;}if((!autoScroll&&scrollKey==0)||boundaryBusy)return;double next=View.Scroll+(scrollKey!=0?scrollKey*600:Config.ScrollSpeed)*dt;double end=Math.Max(0,View.GridBottom-View.GridViewport35);if(scrollKey==0&&next>=end){View.Scroll=end;if(GridMetadataLoading){View.InvalidateVisual();return;}if(autoBoundarySince==default){autoBoundarySince=DateTime.UtcNow;countdownSecond=-1;}int remaining=Math.Max(0,3-(int)(DateTime.UtcNow-autoBoundarySince).TotalSeconds);if(remaining>0&&remaining!=countdownSecond){countdownSecond=remaining;Toast((Config.SiblingNavigation?"Next folder in ":"Looping in ")+remaining+(remaining==1?" second":" seconds"),1.1);}if(remaining==0)Run(()=>CrossGridBoundary(1));View.InvalidateVisual();return;}autoBoundarySince=default;next=Math.Clamp(next,0,end);bool ready=true;for(int i=0;i<Math.Min(GridPaths.Count,View.Tiles.Count);i++){var tile=View.Tiles[i];if(View.GridEnd35(tile)<next-View.GridViewport35*.5||View.GridStart35(tile)>next+View.GridViewport35*1.5||IsFolderTile(i))continue;string path=GridPaths[i];if(GridHoles.Contains(path)||new[]{".mp4",".webm"}.Contains(Path.GetExtension(path).ToLowerInvariant())||thumbFailed.Contains(path))continue;if(!View.Thumbs.ContainsKey(path)){RequestThumb(path);ready=false;}}if(ready||scrollKey!=0)View.Scroll=next;PreloadThumbs();View.InvalidateVisual();}
 async Task QuickTransfer(string folder){var resolved=ResolveDestination(folder);if(resolved==null)return;folder=resolved;if(!quickCopy){await MoveSelection(folder);return;}if(Operations.Busy)return;var selected=Selection();if(selected.Length==0)return;Operations.Busy=true;var batch=BeginBatch34("Copying",selected.Length);try{await batch.Run(selected,async src=>{string dst=Path.Combine(folder,Path.GetFileName(src));Paths.Guard(dst);if(string.Equals(src,dst,StringComparison.OrdinalIgnoreCase))return false;bool overwrite=false;if(File.Exists(dst)){string choice=await Conflict(src,dst,true);if(choice=="cancel")return false;if(choice=="rename")dst=FileNames.Next(dst);else overwrite=true;}await Task.Run(()=>{string temp=dst+".gazegallery-"+Guid.NewGuid().ToString("N");try{File.Copy(src,temp);File.Move(temp,dst,overwrite);}finally{if(File.Exists(temp))File.Delete(temp);}});return true;},()=>ReportBatch34("Copying"));if(batch.Completed.Count>0){if(batch.CancelRequested)Toast($"Copy stopped · {batch.Completed.Count} completed · original files kept");else TransferToast(batch.Completed.ToArray(),"was copied to "+Path.GetFileName(folder.TrimEnd('\\')),false);}}finally{EndBatch34();Operations.Busy=false;}}

 void ResetBoardSize(){if(View.BoardSelection.Count==0)return;View.Snapshot();foreach(var i in View.BoardSelection){double w=i.NaturalWidth,h=i.NaturalHeight;i.Rect=new Rect(i.Rect.X+(i.Rect.Width-w)/2,i.Rect.Y+(i.Rect.Height-h)/2,w,h);}View.InvalidateVisual();}
 void FocusBoard(BoardItem item,bool toggle=true){View.BoardSelection.Clear();View.BoardSelected=-1;if(toggle&&focusedBoard==item){View.BoardScale=overviewScale;View.BoardPan=overviewPan;focusedBoard=null;}else{if(focusedBoard==null){overviewScale=View.BoardScale;overviewPan=View.BoardPan;}focusedBoard=item;FitBoardRect(item.Rect);}View.InvalidateVisual();}
 void FitBoardRect(Rect r){double top=Config.FadeCollage?0:ToolbarHeight;View.BoardScale=Math.Min((View.ActualWidth-16)/r.Width,(View.GridViewport35-top-16)/r.Height);View.BoardPan=new((View.ActualWidth-r.Width*View.BoardScale)/2-r.X*View.BoardScale,top+(View.GridViewport35-top-r.Height*View.BoardScale)/2-r.Y*View.BoardScale);}
 bool TryBoardNavigate(string key){int direction=Config.Keys["Next"].Contains(key)?1:Config.Keys["Previous"].Contains(key)?-1:0;if(direction==0||View.Board.Count==0)return false;var items=View.Board.OrderBy(i=>i.ImportOrder).ToArray();int n=Array.IndexOf(items,focusedBoard);if(n<0&&focusedBoard!=null){var next=direction>0?items.FirstOrDefault(i=>i.ImportOrder>focusedBoard.ImportOrder)??items[0]:items.LastOrDefault(i=>i.ImportOrder<focusedBoard.ImportOrder)??items[^1];FocusBoard(next,false);}else FocusBoard(items[(n+direction+items.Length)%items.Length],false);return true;}
 async Task StartBoardCrop(){if(View.BoardSelection.Count!=1)return;var selected=View.BoardSelection.Single();var source=selected.Edited?selected.Image:await LoaderPool.Run(()=>ImageCache.Read(selected.Path,0));if(Mode!="board"||!View.Board.Contains(selected))return;BoardCropItem=selected;boardCropSource=source;View.CropRect=Rect.Empty;var buttons=new StackPanel{Orientation=Orientation.Horizontal};AddCropRatios(buttons);buttons.Children.Add(Ui.Button("Cancel",CancelBoardCrop));buttons.Children.Add(Ui.Button("Apply",()=>Run(ApplyBoardCrop)));cropPanel.Child=buttons;cropPanel.Visibility=Visibility.Visible;View.InvalidateVisual();}
 void CancelBoardCrop(){BoardCropItem=null;boardCropSource=null;boardCropDrag=false;View.CropRect=Rect.Empty;cropPanel.Visibility=Visibility.Collapsed;View.ReleaseMouseCapture();View.InvalidateVisual();}
 public Rect BoardCropScreen {get{if(BoardCropItem==null||boardCropSource==null||View.CropRect.IsEmpty)return Rect.Empty;var r=View.BoardScreen(BoardCropItem.Rect);return new Rect(r.X+View.CropRect.X*r.Width/boardCropSource.PixelWidth,r.Y+View.CropRect.Y*r.Height/boardCropSource.PixelHeight,View.CropRect.Width*r.Width/boardCropSource.PixelWidth,View.CropRect.Height*r.Height/boardCropSource.PixelHeight);}}
 Point BoardCropPoint(Point p){var r=View.BoardScreen(BoardCropItem!.Rect);return new((p.X-r.X)*boardCropSource!.PixelWidth/r.Width,(p.Y-r.Y)*boardCropSource.PixelHeight/r.Height);}
 void BoardCropDown(Point p){boardCropDrag=true;last=p;panGesture=Keyboard.IsKeyDown(Key.Space);boardCropBefore=View.CropRect;boardCropStart=BoardCropPoint(p);boardCropHandle=View.CropRect.IsEmpty?-2:GeometryRules.Handle(BoardCropScreen,p,14);if(boardCropHandle<0&&!BoardCropScreen.Contains(p)){boardCropHandle=-2;View.CropRect=new Rect(boardCropStart,boardCropStart);}View.CaptureMouse();}
 void BoardCropMove(Point p){if(!boardCropDrag)return;if(panGesture||Keyboard.IsKeyDown(Key.Space)){View.BoardPan+=p-last;last=p;}else{var ip=BoardCropPoint(p);if(boardCropHandle==-2)View.CropRect=CropDrag(boardCropStart,ip);else if(boardCropHandle>=0)View.CropRect=CropResize(boardCropBefore,boardCropStart,ip,boardCropHandle);else View.CropRect=new Rect(boardCropBefore.Location+(ip-boardCropStart),boardCropBefore.Size);}View.InvalidateVisual();}
 async Task ApplyBoardCrop(){if(BoardCropItem==null||boardCropSource==null||View.CropRect.IsEmpty)return;var item=BoardCropItem;var source=boardCropSource;var area=ClampCropArea(View.CropRect,source);if(area.IsEmpty){Toast("Crop must overlap the image");return;}var result=await Sta.Run(()=>CropWithinImage(source,area));View.Snapshot();double sx=item.Rect.Width/source.PixelWidth,sy=item.Rect.Height/source.PixelHeight;item.Rect=new Rect(item.Rect.X+area.X*sx,item.Rect.Y+area.Y*sy,result.PixelWidth*sx,result.PixelHeight*sy);item.Image=result;item.Edited=true;item.NaturalWidth=result.PixelWidth;item.NaturalHeight=result.PixelHeight;CancelBoardCrop();}
 void CompactPack(){double gap=Config.CollageGap;View.BoardSelection.Clear();View.BoardSelected=-1;if(View.Board.Count==0)return;View.Snapshot();focusedBoard=null;if(View.Board.Count==4){for(int i=0;i<4;i++){var r=View.Board[i].Rect;View.Board[i].Rect=new Rect(i%2==0?-gap/2-r.Width:gap/2,i<2?-gap/2-r.Height:gap/2,r.Width,r.Height);}FitBoardRect(View.Board.Select(i=>i.Rect).Aggregate(Rect.Union));View.InvalidateVisual();return;}var items=View.Board.OrderByDescending(i=>i.Rect.Width*i.Rect.Height).ToArray();double ratio=View.ActualWidth/Math.Max(1,View.GridViewport35-(Config.FadeCollage?0:ToolbarHeight)),area=items.Sum(i=>(i.Rect.Width+gap)*(i.Rect.Height+gap)),baseW=Math.Sqrt(area*ratio);Rect[]? best=null;double bestScore=double.MaxValue;
  for(int trial=0;trial<28;trial++){double w=Math.Max(items.Max(i=>i.Rect.Width+gap),baseW*(.55+trial*.055)),h=Math.Max(items.Max(i=>i.Rect.Height+gap),area/w*4);var free=new List<Rect>{new(0,0,w,h)};var placed=new List<Rect>();bool ok=true;foreach(var item in items){double iw=item.Rect.Width+gap,ih=item.Rect.Height+gap;var slots=free.Where(r=>r.Width>=iw&&r.Height>=ih).OrderBy(r=>Math.Min(r.Width-iw,r.Height-ih)).ThenBy(r=>r.Y).ToArray();if(slots.Length==0){ok=false;break;}var chosen=new Rect(slots[0].X,slots[0].Y,iw,ih);placed.Add(new Rect(chosen.X,chosen.Y,iw-gap,ih-gap));var split=new List<Rect>();foreach(var f in free){if(!f.IntersectsWith(chosen)){split.Add(f);continue;}if(chosen.Left>f.Left)split.Add(new Rect(f.Left,f.Top,chosen.Left-f.Left,f.Height));if(chosen.Right<f.Right)split.Add(new Rect(chosen.Right,f.Top,f.Right-chosen.Right,f.Height));if(chosen.Top>f.Top)split.Add(new Rect(f.Left,f.Top,f.Width,chosen.Top-f.Top));if(chosen.Bottom<f.Bottom)split.Add(new Rect(f.Left,chosen.Bottom,f.Width,f.Bottom-chosen.Bottom));}free=split.Where((r,n)=>r.Width>0&&r.Height>0&&!split.Where((_,j)=>j!=n).Any(other=>other.Contains(r)&&other!=r)).Distinct().ToList();}if(!ok)continue;var bounds=placed.Aggregate(Rect.Union);double score=Math.Max(bounds.Width/ratio,bounds.Height);if(score<bestScore){bestScore=score;best=placed.ToArray();}}
  if(best!=null)for(int i=0;i<items.Length;i++)items[i].Rect=best[i];FitBoardRect(View.Board.Select(i=>i.Rect).Aggregate(Rect.Union));View.InvalidateVisual();
 }
}
