using System;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace gazegallery;
public static class ImageAdjustments {
 public static readonly string[] Names={"Brightness","Exposure","Contrast","Highlights","Shadows","Vignette","Saturation","Warmth","Tint","Sharpness","White point","Black point","Hue","Gamma","Grayscale","Invert colors","Threshold enabled","Threshold midpoint","Blur","Blur type","Red","Green","Blue","Invert red","Invert green","Invert blue","Sepia","Posterize","Motion direction","Motion length"};
 public static BitmapSource Render(BitmapSource source,double[] v,double angle=0,bool flipH=false,bool flipV=false){
  if(v.All(n=>Math.Abs(n)<.00001))return Math.Abs(angle)<.001&&!flipH&&!flipV?source:Rotate(source,angle,flipH,flipV);
  var converted=new FormatConvertedBitmap(source,PixelFormats.Bgra32,null,0);int w=source.PixelWidth,h=source.PixelHeight,stride=w*4;byte[] input=new byte[stride*h],output=new byte[stride*h];converted.CopyPixels(input,stride,0);
  double brightness=v[0]/100,exposure=Math.Pow(2,v[1]/25),contrast=Math.Pow(2,v[2]/100),sat=Math.Max(0,1+v[6]/100),warm=v[7]/500,tint=v[8]/500,white=Math.Max(.05,1-v[10]/200),black=v[11]/200;
  if(v.Take(12).All(n=>n==0))Buffer.BlockCopy(input,0,output,0,input.Length);else Parallel.For(0,h,new ParallelOptions{MaxDegreeOfParallelism=LoaderPool.Limit},y=>{double ny=(y-h/2.0)/Math.Max(1,h/2.0);for(int x=0;x<w;x++){int p=y*stride+x*4;double b=input[p]/255.0,g=input[p+1]/255.0,r=input[p+2]/255.0,lum=.2126*r+.7152*g+.0722*b,shadows=v[4]/200*(1-lum)*(1-lum),high=v[3]/200*lum*lum;double nx=(x-w/2.0)/Math.Max(1,w/2.0),vig=1-v[5]/100*.6*Math.Min(1,(nx*nx+ny*ny)/2);
   double Channel(double c,double balance){c=((c*exposure+brightness+shadows+high-black)/white-.5)*contrast+.5;c=lum+(c-lum)*sat;return Math.Clamp((c+balance)*vig,0,1);}
   output[p]=(byte)Math.Round(Channel(b,-warm)*255);output[p+1]=(byte)Math.Round(Channel(g,tint)*255);output[p+2]=(byte)Math.Round(Channel(r,warm)*255);output[p+3]=input[p+3];}});
  if(v.Length>12)output=ExtendedAdjustments.Apply(output,w,h,v);
  if(w>2&&h>2&&Math.Abs(v[9])>.001){var before=(byte[])output.Clone();double amount=v[9]/100;Parallel.For(1,h-1,new ParallelOptions{MaxDegreeOfParallelism=LoaderPool.Limit},y=>{for(int x=1;x<w-1;x++)for(int c=0;c<3;c++){int i=y*stride+x*4+c;double mean=(before[i-4]+before[i+4]+before[i-stride]+before[i+stride])/4.0;output[i]=(byte)Math.Clamp(Math.Round(before[i]+(before[i]-mean)*amount),0,255);}});}
  var bitmap=BitmapSource.Create(w,h,source.DpiX,source.DpiY,PixelFormats.Bgra32,null,output,stride);bitmap.Freeze();if(Math.Abs(angle)<.001&&!flipH&&!flipV)return bitmap;
  return Rotate(bitmap,angle,flipH,flipV);
 }
 static BitmapSource Rotate(BitmapSource bitmap,double angle,bool flipH,bool flipV){int w=bitmap.PixelWidth,h=bitmap.PixelHeight;var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){dc.PushClip(new RectangleGeometry(new Rect(0,0,w,h)));dc.PushTransform(new RotateTransform(angle,w/2.0,h/2.0));dc.PushTransform(new ScaleTransform(flipH?-1:1,flipV?-1:1,w/2.0,h/2.0));dc.DrawImage(bitmap,new Rect(0,0,w,h));dc.Pop();dc.Pop();dc.Pop();}var result=new RenderTargetBitmap(w,h,96,96,PixelFormats.Pbgra32);result.Render(visual);result.Freeze();return result;
 }
 public static BitmapSource PreviewSource(BitmapSource source){double f=Math.Min(1,768.0/Math.Max(source.PixelWidth,source.PixelHeight));if(f==1)return source;var small=new TransformedBitmap(source,new ScaleTransform(f,f));small.Freeze();return small;}
}
public partial class MainWindow {
 double[] editValues=new double[ImageAdjustments.Names.Length];double editAngle;bool editFlipH,editFlipV;int editEpoch,editSession;BitmapSource? editPreviewSource;
 void BeginEditing(){editEpoch++;int session=++editSession;editValues=new double[ImageAdjustments.Names.Length];editAngle=rotationBase=0;motionLineMode=motionLineDragging=false;editFlipH=editFlipV=false;editPreviewSource=null;var source=sourceImage;if(source==null)return;_=Task.Run(async()=>{var small=await Sta.Run(()=>ImageAdjustments.PreviewSource(source));await Dispatcher.InvokeAsync(()=>{if(Cropping&&session==editSession){editPreviewSource=small;QueueEditPreview();}});});}
 void AddEditControls(Panel panel){panel.Children.Insert(0,Ui.Button("Adjust image…",EditAdjustments));AddRotation32(panel);}
 Window? adjustmentWindow;bool editRendering;
 void EditAdjustments(){if(adjustmentWindow!=null){adjustmentWindow.Activate();return;}var window=Ui.Dialog(this,"Image adjustments",540,650);window.WindowStartupLocation=WindowStartupLocation.Manual;window.Left=Left+14;window.Top=Math.Max(0,Top+(ActualHeight-window.Height)/2);adjustmentWindow=window;editSliders32.Clear();AdjustmentsOpen=true;View.InvalidateVisual();var panel=new StackPanel{Margin=new Thickness(14)};var resets=new System.Collections.Generic.List<Action>();bool resetting=false;
 void Changed(){if(!resetting)QueueEditPreview();}
 void SliderControl(Panel group,int slot){var row=new Grid();row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(105)});row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(42)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(30)});row.Children.Add(Ui.Label(ImageAdjustments.Names[slot],11));var slider=new Slider{Minimum=-100,Maximum=100,Value=editValues[slot],Margin=new Thickness(6),VerticalAlignment=VerticalAlignment.Center};if(slot is 18 or 26 or 27){slider.Minimum=0;slider.Maximum=slot==18?50:100;}editSliders32[slot]=slider;if(slot==27)slider.TickFrequency=1;Grid.SetColumn(slider,1);row.Children.Add(slider);var label=Ui.Label(slider.Value.ToString("0.#"),11);Grid.SetColumn(label,2);row.Children.Add(label);slider.ValueChanged+=(_,_)=>{editValues[slot]=slider.Value;label.Text=slider.Value.ToString("0.#");Changed();};var reset=Ui.Button("↺",()=>{slider.Value=0;if(slot==18){editValues[28]=editValues[29]=0;Changed();}});reset.Padding=new Thickness(4);reset.ToolTip="Reset "+ImageAdjustments.Names[slot];Grid.SetColumn(reset,3);row.Children.Add(reset);resets.Add(()=>slider.Value=0);group.Children.Add(row);if(slot==17)slider.IsEnabled=editValues[16]!=0;}
 void Toggle(Panel group,string label,int slot){Button? button=null;void Update()=>button!.Content=label+(editValues[slot]!=0?" ✓":"");button=Ui.Button(label,()=>{editValues[slot]=editValues[slot]==0?1:0;Update();Changed();});Update();resets.Add(()=>{editValues[slot]=0;Update();});group.Children.Add(button);}
 foreach(var group in new[]{("Light",new[]{0,1,13,2,3,4,10,11}),("Color",new[]{12,6,7,8,26,27}),("Detail",new[]{9,5}),("Composite",new[]{20,21,22}),("Blur",new[]{18}),("Black and white",Array.Empty<int>())}){var contents=new StackPanel();foreach(int slot in group.Item2)SliderControl(contents,slot);if(group.Item1=="Color"){Toggle(contents,"Grayscale",14);Toggle(contents,"Invert colors",15);}if(group.Item1=="Composite"){Toggle(contents,"Invert red",23);Toggle(contents,"Invert green",24);Toggle(contents,"Invert blue",25);}if(group.Item1=="Blur"){var type=new ComboBox{ItemsSource=new[]{"Gaussian","Box","Motion"},SelectedIndex=(int)editValues[19],Margin=new Thickness(5)};type.SelectionChanged+=(_,_)=>{editValues[19]=type.SelectedIndex;Changed();};contents.Children.Add(type);var direction=Ui.Button("Draw motion direction / length",()=>{type.SelectedIndex=2;motionLineMode=true;Toast("Drag a line on the image to set motion blur");});contents.Children.Add(direction);resets.Add(()=>{type.SelectedIndex=0;editValues[28]=editValues[29]=0;motionLineMode=false;});}if(group.Item1=="Black and white"){var enabled=new CheckBox{Content="Threshold",IsChecked=editValues[16]!=0,Margin=new Thickness(5)};contents.Children.Add(enabled);SliderControl(contents,17);var midpoint=((Grid)contents.Children[^1]).Children.OfType<Slider>().Single();enabled.Checked+=(_,_)=>{editValues[16]=1;midpoint.IsEnabled=true;Changed();};enabled.Unchecked+=(_,_)=>{editValues[16]=0;midpoint.IsEnabled=false;Changed();};resets.Add(()=>{enabled.IsChecked=false;midpoint.IsEnabled=false;editValues[16]=0;});}panel.Children.Add(new Expander{Header=group.Item1,Foreground=Ui.Fg,Content=contents,Margin=new Thickness(4),IsExpanded=group.Item1=="Light"});}
 var buttons=new WrapPanel();buttons.Children.Add(Ui.Button("Reset all",()=>{resetting=true;foreach(var reset in resets)reset();editValues=new double[ImageAdjustments.Names.Length];editFlipH=editFlipV=false;SetEditAngle32(0);resetting=false;QueueEditPreview();}));buttons.Children.Add(Ui.Button("Done",window.Close));panel.Children.Add(buttons);window.Content=new ScrollViewer{Content=panel};window.Closed+=(_,_)=>{adjustmentWindow=null;editSliders32.Clear();AdjustmentsOpen=false;View.InvalidateVisual();};window.Show();}
 async void QueueEditPreview(){editEpoch++;if(editRendering||!Cropping||editPreviewSource==null)return;editRendering=true;int session=editSession;try{while(Cropping&&session==editSession&&editPreviewSource!=null){int token=editEpoch;var small=editPreviewSource;var values=(double[])editValues.Clone();double angle=0;if(values.Length>29&&sourceImage!=null)values[29]*=small.PixelWidth/(double)sourceImage.PixelWidth;bool h=editFlipH,v=editFlipV;var result=await Sta.Run(()=>ImageAdjustments.Render(small,values,angle,h,v));if(!Cropping||session!=editSession)break;double ratio=View.Image==null?1:View.Image.PixelWidth/(double)result.PixelWidth;View.Scale*=ratio;if(!View.CropRect.IsEmpty)View.CropRect=new Rect(View.CropRect.X/ratio,View.CropRect.Y/ratio,View.CropRect.Width/ratio,View.CropRect.Height/ratio);View.Image=result;View.InvalidateVisual();if(token==editEpoch)break;await Task.Delay(16);}}catch(Exception e){Error(e);}finally{editRendering=false;if(Cropping&&session!=editSession&&editPreviewSource!=null)QueueEditPreview();}}
 Task<BitmapSource> EditedFullImage(){var image=cropOriginal??sourceImage!;var values=(double[])editValues.Clone();double angle=editAngle;bool h=editFlipH,v=editFlipV;return Sta.Run(()=>ImageAdjustments.Render(image,values,angle,h,v));}
 Rect FullEditArea(){if(View.Image==null)return Rect.Empty;var rect=View.CropRect.IsEmpty?new Rect(0,0,View.Image.PixelWidth,View.Image.PixelHeight):ViewerCropArea();if(rect.IsEmpty)return Rect.Empty;var full=cropOriginal??sourceImage!;double fx=full.PixelWidth/(double)View.Image.PixelWidth,fy=full.PixelHeight/(double)View.Image.PixelHeight;return new Rect(rect.X*fx,rect.Y*fy,rect.Width*fx,rect.Height*fy);}
 void TransformEdit(string action){if(action=="Flip horizontal")editFlipH=!editFlipH;else if(action=="Flip vertical")editFlipV=!editFlipV;else SetEditAngle32(editAngle+90);QueueEditPreview();}
}
