using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Documents;
using Microsoft.Win32;
namespace gazegallery;
public class ExternalProgram {public string Executable{get;set;}="";public string Arguments{get;set;}="{file}";}
public partial class MainWindow {
 BitmapScalingMode ScalingMode=>Config.Nearest?BitmapScalingMode.NearestNeighbor:Config.SmoothFilter=="Bicubic"?BitmapScalingMode.HighQuality:BitmapScalingMode.Linear;
 string DestinationStart(){try{var parent=Directory.GetParent(Config.LastDestination)?.FullName;if(parent!=null&&Directory.Exists(parent))return parent;}catch{}return hasFolder?Folder:Paths.Test;}
 void NavigateSelection(int direction){if(View.Selected.Count!=1)return;int old=View.Selected.Single(),n=old+direction;if(n<FolderTileCount||n>=GridPaths.Count)return;View.Selected.Clear();View.Selected.Add(n);View.Anchor=n;View.Reveal(n);View.InvalidateVisual();}
 async Task NavigateViewer(int direction){if(cropNeighbors!=null){var neighbors=cropNeighbors;cropNeighbors=null;string? target=direction>0?neighbors.Next:neighbors.Previous;await Scan();if(target!=null&&Files.Contains(target)){await ShowIndex(Files.IndexOf(target));return;}}int next=Index+direction;if(Config.SiblingNavigation&&(Files.Count==0||next<0||next>=Files.Count)){var parent=Directory.GetParent(Folder);if(parent==null)return;var siblings=Directory.GetDirectories(parent.FullName).OrderBy(x=>x,new Natural()).ToArray();int index=Array.FindIndex(siblings,x=>string.Equals(x,Folder,StringComparison.OrdinalIgnoreCase))+direction;if(index<0||index>=siblings.Length)return;await Open(siblings[index]);CenteredFolderToast(Folder);if(direction<0&&Files.Count>0)await ShowIndex(Files.Count-1);return;}bool loopStart=next>=Files.Count&&Files.Count>0,loopLast=next<0&&Files.Count>0;await ShowIndex(next);if(loopStart)Toast("Looped to start");else if(loopLast)Toast("Looped to last");}
 sealed record CropNeighbors(string? Previous,string? Next);CropNeighbors? cropNeighbors;
 void RememberCropNeighbors(){cropNeighbors=Files.Count<=1?new(null,null):new(Files[(Index-1+Files.Count)%Files.Count],Files[(Index+1)%Files.Count]);}
 async void FlashThumbnail(int index){int token=modeTransition;await Task.Delay(250);if(Mode!="grid"||token!=modeTransition)return;View.FlashIndex=index;View.FlashAlpha=.2;int frames=0;TimeSpan previous=TimeSpan.MinValue;EventHandler? rendered=null;rendered=(_,args)=>{if(args is RenderingEventArgs r&&r.RenderingTime==previous)return;if(args is RenderingEventArgs t)previous=t.RenderingTime;if(Mode!="grid"||token!=modeTransition){CompositionTarget.Rendering-=rendered;return;}if(++frames==3){if(View.Selected.Count==0&&index<GridPaths.Count){View.Selected.Add(index);View.Anchor=index;}CompositionTarget.Rendering-=rendered;}};CompositionTarget.Rendering+=rendered;var start=DateTime.UtcNow;while(Mode=="grid"&&token==modeTransition&&(DateTime.UtcNow-start).TotalMilliseconds<550){View.FlashAlpha=.2*(1-(DateTime.UtcNow-start).TotalMilliseconds/550);View.InvalidateVisual();await Task.Delay(16);}CompositionTarget.Rendering-=rendered;View.FlashIndex=-1;View.InvalidateVisual();}
 void TransferToast(string[] files,string destination,bool undo=true){toast.BeginAnimation(UIElement.OpacityProperty,null);toast.Margin=new Thickness(10,0,10,18);toast.Inlines.Clear();toast.Inlines.Add(new Run(files.Length==1?Path.GetFileName(files[0]):$"{files.Length} files"));toast.Inlines.Add(new LineBreak());toast.Inlines.Add(new Run(destination));toast.Inlines.Add(new LineBreak());toast.Inlines.Add(new Run(undo?string.Join(" / ",Config.Keys["Undo"].Select(FriendlyKey))+" to undo":"Original file kept"){FontSize=10,Foreground=Ui.Muted});toast.TextAlignment=TextAlignment.Center;toast.Opacity=.67*1.33;toast.VerticalAlignment=VerticalAlignment.Bottom;toastDuration=4*.67;toastTime=DateTime.Now;toast.Visibility=Visibility.Visible;}
 void OpenWithMenuLegacy(){string? file=ExternalActionImage;if(file==null)return;string ext=Path.GetExtension(file).ToLowerInvariant();if(!Config.ExternalPrograms.TryGetValue(ext,out var entries))Config.ExternalPrograms[ext]=entries=Enumerable.Range(0,3).Select(_=>new ExternalProgram()).ToList();var menu=new ContextMenu();foreach(var entry in entries){var item=new MenuItem{Header=string.IsNullOrEmpty(entry.Executable)?"Set program…":Path.GetFileNameWithoutExtension(entry.Executable)};item.Click+=(_,_)=>{if(entry.Executable.Length==0)ConfigureProgram(entry,ext);else try{LaunchExternal(entry,file);}catch(Exception ex){Error(ex);}};item.PreviewMouseRightButtonUp+=(_,e)=>{e.Handled=true;menu.IsOpen=false;ConfigureProgram(entry,ext);};menu.Items.Add(item);}menu.Items.Add(new Separator());var sets=new MenuItem{Header="Sets / other extensions…"};sets.Click+=(_,_)=>ExternalSetsMenu(ext);menu.Items.Add(sets);menu.Items.Add(new MenuItem{Header="Right-click to configure · "+ext,IsEnabled=false});menu.IsOpen=true;}
 void ConfigureProgram(ExternalProgram entry,string ext){var draft=new ExternalProgram{Executable=entry.Executable,Arguments=entry.Arguments};var w=Ui.Dialog(this,"Open with — "+ext,480,260);var panel=new StackPanel{Margin=new Thickness(16)};var label=Ui.Label(draft.Executable.Length==0?"Choose a program":Path.GetFileName(draft.Executable),12);panel.Children.Add(label);var arguments=Ui.Button("Arguments…",()=>{var text=Ui.Prompt(w,"Arguments — use {file} for the current file",draft.Arguments);if(text!=null)draft.Arguments=text;});arguments.IsEnabled=draft.Executable.Length>0;panel.Children.Add(Ui.Button("Choose executable…",()=>{var d=new OpenFileDialog{Filter="Programs|*.exe"};if(d.ShowDialog(w)==true){draft.Executable=d.FileName;label.Text=Path.GetFileName(d.FileName);arguments.IsEnabled=true;}}));panel.Children.Add(arguments);var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};buttons.Children.Add(Ui.Button("Set",()=>{if(!File.Exists(draft.Executable)){Toast("Choose an existing executable");return;}entry.Executable=draft.Executable;entry.Arguments=draft.Arguments;Config.Save();w.Close();}));buttons.Children.Add(Ui.Button("Clear",()=>{entry.Executable="";entry.Arguments="{file}";Config.Save();w.Close();}));buttons.Children.Add(Ui.Button("Cancel",w.Close));panel.Children.Add(buttons);w.Content=panel;w.ShowDialog();}
 static System.Diagnostics.ProcessStartInfo ExternalStartInfo(ExternalProgram entry,string file){var p=new System.Diagnostics.ProcessStartInfo(entry.Executable){UseShellExecute=true,WorkingDirectory=Path.GetDirectoryName(Path.GetFullPath(entry.Executable))!};if(entry.Arguments.Trim()=="{file}")p.ArgumentList.Add(file);else{string quoted="\""+file.Replace("\"","\\\"")+"\"";p.Arguments=entry.Arguments.Contains("{file}")?entry.Arguments.Replace("{file}",quoted):entry.Arguments+" "+quoted;}return p;}
 static void LaunchExternal(ExternalProgram entry,string file)=>System.Diagnostics.Process.Start(ExternalStartInfo(entry,file));
 BitmapSource? cropOriginal;
 void TransformCrop(string action){if(Cropping&&View.Image!=null)TransformEdit(action);}
}
