using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace gazegallery;
public partial class MainWindow {
 public Brush MediaBackground=>Config.Oled?Brushes.Black:new SolidColorBrush(Color.FromRgb(24,24,24));
 static string FriendlyKey(string key)=>Regex.Replace(key,@"(?<=^|\+)D([0-9])$","$1").Replace("Return","Enter");
 static string NormalizeKey(string key)=>Regex.Replace(key,@"(?<=^|\+)([0-9])$","D$1").Replace("Return","Enter",StringComparison.OrdinalIgnoreCase);
 string[] SelectedGridImages()=>View.Selected.Where(i=>i>=FolderTileCount&&i<GridPaths.Count).Order().Select(i=>GridPaths[i]).Where(File.Exists).ToArray();
 async System.Threading.Tasks.Task StartCollage(){var paths=Mode=="grid"?SelectedGridImages():current==null?Array.Empty<string>():new[]{current};if(Mode=="grid"&&paths.Length==0)return;collageReturnMode=Mode;await SetMode("board");if(Mode!="board")return;collageOrigin=paths.FirstOrDefault();await ImportBoard(paths);if(!paths.Any(Paths.Motion))Toast($"max {boardLimit} images",1);}
 void ScrollSpeedMenu(){bool resume=autoScroll;PauseScroll();var w=Ui.Dialog(this,"Autoscroll speed",420,235);w.ResizeMode=ResizeMode.NoResize;var p=new StackPanel{Margin=new Thickness(12)};p.Children.Add(Ui.Label("Pixels per second (0.1–1200)",12));var input=Ui.Input(Config.ScrollSpeed.ToString(CultureInfo.InvariantCulture));input.Width=100;input.HorizontalAlignment=HorizontalAlignment.Center;input.HorizontalContentAlignment=HorizontalAlignment.Center;p.Children.Add(input);var error=Ui.Label("",11);void Save(){if(!double.TryParse(input.Text,NumberStyles.AllowDecimalPoint,CultureInfo.InvariantCulture,out double n)||n<.1||n>1200){error.Text="Enter a speed from 0.1 to 1200.";return;}Config.ScrollSpeed=n;Config.Save();w.Close();}input.PreviewTextInput+=(_,e)=>e.Handled=!Regex.IsMatch(input.Text.Remove(input.SelectionStart,input.SelectionLength).Insert(input.SelectionStart,e.Text),@"^\d{0,4}(\.\d{0,3})?$");input.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Enter){Save();e.Handled=true;}};var row=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Center};foreach(int value in new[]{30,60,120,240})row.Children.Add(Ui.Button(value.ToString(),()=>{input.Text=value.ToString();Save();}));p.Children.Add(row);p.Children.Add(error);var buttons=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right};buttons.Children.Add(Ui.Button("Set",Save));buttons.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(buttons);w.Content=p;w.ShowDialog();if(resume&&Mode=="grid"){autoScroll=true;lastScrollTick=motionClock.Elapsed.TotalSeconds;if(autoButton!=null)autoButton.Content="Stop scroll";}}
 void CustomScrollSpeed(){var w=Ui.Dialog(this,"Custom autoscroll speed",330,250);w.ResizeMode=ResizeMode.NoResize;var p=new StackPanel{Margin=new Thickness(15),HorizontalAlignment=HorizontalAlignment.Center};p.Children.Add(Ui.Label("0.1–1200 pixels per second",12));var input=Ui.Input(Config.ScrollSpeed.ToString(CultureInfo.InvariantCulture));input.Width=130;input.HorizontalContentAlignment=HorizontalAlignment.Center;input.HorizontalAlignment=HorizontalAlignment.Center;bool Valid(string s)=>Regex.IsMatch(s,@"^\d{0,4}(\.\d{0,3})?$");string Proposed(string text)=>input.Text.Remove(input.SelectionStart,input.SelectionLength).Insert(input.SelectionStart,text);input.PreviewTextInput+=(_,e)=>e.Handled=!Valid(Proposed(e.Text));DataObject.AddPastingHandler(input,(_,e)=>{if(e.DataObject.GetData(DataFormats.UnicodeText) is not string t||!Valid(Proposed(t)))e.CancelCommand();});var error=Ui.Label("",11);void Save(){if(!double.TryParse(input.Text,NumberStyles.AllowDecimalPoint,CultureInfo.InvariantCulture,out double speed)||speed<.1||speed>1200){error.Text="Enter a speed from 0.1 to 1200.";return;}Config.ScrollSpeed=speed;Config.Save();w.Close();}input.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Enter){e.Handled=true;Save();}};p.Children.Add(input);p.Children.Add(error);p.Children.Add(Ui.Button("Apply",Save));p.Children.Add(Ui.Button("Cancel",w.Close));w.Content=p;w.Loaded+=(_,_)=>{input.Focus();input.SelectAll();};w.ShowDialog();}
 static string BindingCategory(string action)=>action.EndsWith("collage")?"Collage":action.EndsWith("thumbnails")||action=="Thumbnails"?"Thumbnails":action is "Play / pause" or "Mute"?"Playback":action is "Next" or "Previous" or "Folder tree" or "Shuffle" or "Navigation arrows"?"Navigation":action is "Copy" or "Paste" or "Save as" or "Trash" or "Undo" or "Rename" or "Quick sort" or "Show in Explorer"?"Files and sorting":action is "Crop" or "Flip horizontal" or "Flip vertical" or "Rotate 90°" or "Filtering"?"Image view":"Window and application";
 UIElement BindingEditor(Window w,Dictionary<string,TextBox> edits){var root=new DockPanel{Margin=new Thickness(12)};var top=new StackPanel();top.Children.Add(Ui.Button("Keyboard and mouse guide",()=>ShowBindingGuide34(w,()=>Config.Keys.ToDictionary(k=>k.Key,k=>edits.TryGetValue(k.Key,out var box)?box.Text.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries).Select(NormalizeKey).ToArray():k.Value))));top.Children.Add(Ui.Label("Search actions or bindings",12));var search=Ui.Input("");top.Children.Add(search);top.Children.Add(Ui.Label("Separate bindings with commas, or use Press key.",11));DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);var rows=new StackPanel();var groups=new List<(StackPanel Panel,List<(string Name,DockPanel Row,TextBox Input)> Rows)>();foreach(var group in Config.Keys.GroupBy(k=>BindingCategory(k.Key)).OrderBy(g=>g.Key)){var section=new StackPanel{Margin=new Thickness(0,8,0,4)};section.Children.Add(Ui.Label(group.Key,15));var entries=new List<(string,DockPanel,TextBox)>();foreach(var kv in group.OrderBy(k=>k.Key)){var row=new DockPanel();var label=Ui.Label(kv.Key,12);label.Width=190;DockPanel.SetDock(label,Dock.Left);row.Children.Add(label);var input=Ui.Input(string.Join(", ",kv.Value.Select(FriendlyKey)));var capture=Ui.Button("Press key",()=>CaptureBinding(w,input));DockPanel.SetDock(capture,Dock.Right);row.Children.Add(capture);row.Children.Add(input);edits[kv.Key]=input;entries.Add((kv.Key,row,input));section.Children.Add(row);}groups.Add((section,entries));rows.Children.Add(section);}search.TextChanged+=(_,_)=>{string q=search.Text.Trim();foreach(var group in groups){bool any=false;foreach(var item in group.Rows){bool show=item.Name.Contains(q,StringComparison.OrdinalIgnoreCase)||item.Input.Text.Contains(q,StringComparison.OrdinalIgnoreCase);item.Row.Visibility=show?Visibility.Visible:Visibility.Collapsed;any|=show;}group.Panel.Visibility=any?Visibility.Visible:Visibility.Collapsed;}};root.Children.Add(new ScrollViewer{Content=rows});return root;}
 // Handle pointer scrubbing explicitly. WPF repeat buttons otherwise race the playback timer.
 void SetupSeek(){seek.Minimum=0;seek.Maximum=1;seek.VerticalAlignment=VerticalAlignment.Center;seek.Margin=new Thickness(12,0,12,0);seek.PreviewMouseLeftButtonDown+=(_,e)=>{if(video==null)return;seekDragging=true;seek.CaptureMouse();ScrubAt(e.GetPosition(seek).X);e.Handled=true;};seek.PreviewMouseMove+=(_,e)=>{if(seekDragging&&e.LeftButton==MouseButtonState.Pressed){ScrubAt(e.GetPosition(seek).X);e.Handled=true;}};seek.PreviewMouseLeftButtonUp+=(_,e)=>{if(!seekDragging)return;ScrubAt(e.GetPosition(seek).X);seekDragging=false;seek.ReleaseMouseCapture();e.Handled=true;};seek.LostMouseCapture+=(_,_)=>seekDragging=false;}
 void ScrubAt(double x){if(video==null)return;seek.Maximum=Math.Max(1,video.Length);double thumb=12;if(seek.Template.FindName("PART_Track",seek) is Track track&&track.Thumb!=null)thumb=track.Thumb.ActualWidth;double fraction=Math.Clamp((x-thumb/2)/Math.Max(1,seek.ActualWidth-thumb),0,1);seek.Value=fraction*seek.Maximum;video.Seek((long)seek.Value);}
}
public static class Branding {
 public const string Outline="M 72,100 Q 72,72 100,72 H 744 Q 772,72 772,100 V 266 Q 772,294 744,294 H 716 Q 699,294 691,276 C 639,163 537,110 421,110 C 256,110 122,244 122,410 C 122,578 256,714 421,714 C 559,714 677,617 704,491 Q 707,476 690,476 H 660 C 596,476 596,394 660,394 H 744 Q 772,394 772,422 V 744 Q 772,772 744,772 H 100 Q 72,772 72,744 Z M 110,125 V 245 Q 110,268 124,245 C 152,196 195,153 242,125 Q 261,110 237,110 H 125 Q 110,110 110,125 Z M 125,734 H 237 Q 263,734 242,719 C 195,690 152,649 124,600 Q 110,577 110,600 V 719 Q 110,734 125,734 Z M 609,734 H 719 Q 734,734 734,719 V 600 Q 734,577 720,600 C 690,650 650,690 602,719 Q 581,734 609,734 Z M 608,110 Q 580,110 603,125 C 650,153 693,198 721,245 Q 734,268 734,245 V 125 Q 734,110 719,110 Z M 567,415 A 145,145 0 1 1 277,415 A 145,145 0 1 1 567,415 Z";
 static readonly Geometry geometry=Make();static Geometry Make(){var g=Geometry.Parse("F0 "+Outline);g.Freeze();return g;}
 public static void Draw(DrawingContext dc,Rect rect){dc.PushTransform(new TranslateTransform(rect.X,rect.Y));dc.PushTransform(new ScaleTransform(rect.Width/844,rect.Height/844));dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(25,25,24)),null,new Rect(0,0,844,844),105,105);dc.DrawGeometry(new SolidColorBrush(Color.FromRgb(239,240,225)),null,geometry);dc.Pop();dc.Pop();}
 public static BitmapSource Icon(){var v=new DrawingVisual();using(var dc=v.RenderOpen())Draw(dc,new Rect(0,0,256,256));var b=new RenderTargetBitmap(256,256,96,96,PixelFormats.Pbgra32);b.Render(v);b.Freeze();return b;}
}
public sealed class FolderGuides : System.Windows.Documents.Adorner {
 readonly TreeView tree;readonly Func<string> current;
 public FolderGuides(TreeView tree,Func<string> current):base(tree){this.tree=tree;this.current=current;IsHitTestVisible=false;}
 protected override void OnRender(DrawingContext dc){var pen=new Pen(new SolidColorBrush(Color.FromArgb(40,210,215,220)),1);void Visit(ItemsControl parent){foreach(var node in parent.Items.OfType<TreeViewItem>()){if(node.Tag is string path&&(string.Equals(path.TrimEnd('\\'),current().TrimEnd('\\'),StringComparison.OrdinalIgnoreCase)||current().StartsWith(path.TrimEnd('\\')+"\\",StringComparison.OrdinalIgnoreCase))&&node.Header is FrameworkElement header&&header.IsVisible){var pos=header.TranslatePoint(new Point(0,header.ActualHeight/2),tree);if(pos.Y>=0&&pos.Y<tree.ActualHeight)dc.DrawLine(pen,new Point(0,pos.Y),new Point(Math.Max(0,pos.X-19),pos.Y));}if(node.IsExpanded)Visit(node);}}Visit(tree);}
}
