using System;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Controls;
namespace gazegallery;
public static class FolderOrnament35 {
 static readonly Geometry wave=Make("M 4,29 C -3,13 14,13 23,29 C 32,45 48,44 45,25 C 43,8 37,4 48,5 C 72,5 70,45 92,45 C 108,45 92,10 106,9 C 126,8 122,36 138,35 C 147,35 145,27 141,25");
 static readonly Geometry ribbon=Make("M 48,5 C 69,5 70,45 92,45 L 84,48 C 63,46 61,11 42,8 Z");
 static Geometry Make(string data){var g=Geometry.Parse(data);g.Freeze();return g;}
 public static void Draw(DrawingContext dc,Rect r){var ink=new SolidColorBrush(Color.FromArgb(160,200,200,200));dc.PushTransform(new TranslateTransform(r.X,r.Y));dc.PushTransform(new ScaleTransform(r.Width/150,r.Height/50));dc.DrawGeometry(null,new Pen(ink,2.5){StartLineCap=PenLineCap.Round,EndLineCap=PenLineCap.Round},wave);dc.DrawGeometry(ink,null,ribbon);dc.Pop();dc.Pop();}
}
// Frozen previews and a presented-file snapshot keep decoding and file-list changes off the render path.
public sealed class Filmstrip:FrameworkElement {
 readonly MainWindow host;readonly ImageCache cache=new(48*1024*1024);readonly Dictionary<string,BitmapSource> images=new();readonly Dictionary<string,int> pending=new();readonly HashSet<string> failed=new();readonly List<(Rect Rect,int Index)> hits=new();string folder="",current="";string[] files=Array.Empty<string>();List<string>? fileList;double center,target;Point down;double downCenter;bool dragging,moved;int epoch,lastIndex=-1;DateTime last=DateTime.UtcNow;
 public Filmstrip(MainWindow host){this.host=host;ClipToBounds=true;MouseWheel+=(_,e)=>{target-=e.Delta/120.0;InvalidateVisual();e.Handled=true;};MouseLeftButtonDown+=(_,e)=>{down=e.GetPosition(this);downCenter=target;dragging=true;moved=false;CaptureMouse();e.Handled=true;};MouseMove+=(_,e)=>{if(!dragging)return;double dx=e.GetPosition(this).X-down.X;moved|=Math.Abs(dx)>4;target=downCenter-dx/Step;InvalidateVisual();e.Handled=true;};MouseLeftButtonUp+=(_,e)=>{if(dragging&&!moved&&host.FilmstripCanPresent35){var p=e.GetPosition(this);var hit=hits.LastOrDefault(h=>h.Rect.Contains(p));if(hit.Rect.Width>0&&hit.Index<files.Length){int index=host.Files.IndexOf(files[hit.Index]);if(index>=0)_=host.ShowIndex(index);}}dragging=false;ReleaseMouseCapture();e.Handled=true;};MouseRightButtonUp+=(_,e)=>{host.FilmstripMenu33().IsOpen=true;e.Handled=true;};}
 double ThumbSize=>Math.Clamp(host.Config.FilmstripSize,24,240);double Step=>ThumbSize/.78;
 public static int Wrap(int index,int count)=>count==0?0:(index%count+count)%count;
 public void Reset(){epoch++;images.Clear();failed.Clear();cache.Clear();folder=host.Folder;current="";lastIndex=-1;pending.Clear();files=Array.Empty<string>();fileList=null;target=center=host.Index;InvalidateVisual();}
 public void Animate(){if(host.FilmstripCanPresent35){if(folder!=host.Folder)Reset();bool changed=fileList!=host.Files||files.Length!=host.Files.Count||current!=host.Current||lastIndex!=host.Index;if(changed){fileList=host.Files;files=host.Files.ToArray();lastIndex=host.Index;current=host.Current??"";center=target=host.Index;InvalidateVisual();}}if(files.Length==0)return;int slots=files.Length+1;if(Math.Abs(target)>slots*4){double cycles=Math.Floor(target/slots)*slots;target-=cycles;center-=cycles;}double dt=Math.Clamp((DateTime.UtcNow-last).TotalSeconds,0,.05);last=DateTime.UtcNow;double diff=target-center;if(Math.Abs(diff)>.001){center+=diff*(1-Math.Exp(-dt*18));InvalidateVisual();}else center=target;}
 protected override void OnRender(DrawingContext dc){base.OnRender(dc);hits.Clear();if(files.Length==0)return;dc.DrawRectangle(new SolidColorBrush(Color.FromArgb(185,18,18,18)),null,new Rect(RenderSize));int count=Math.Max(1,(int)Math.Ceiling(ActualWidth/Step)),mid=(int)Math.Round(center),radius=count/2+3;var keep=new HashSet<string>();var seen=new HashSet<int>();foreach(int offset in Enumerable.Range(-radius,radius*2+1).OrderBy(o=>Math.Abs(mid+o-center))){int index=Wrap(mid+offset,files.Length+1);double x=ActualWidth/2+(mid+offset-center)*Step;if(index==files.Length){if(x+ThumbSize/2>=0&&x-ThumbSize/2<=ActualWidth)FolderOrnament35.Draw(dc,new Rect(x-ThumbSize*.38,ActualHeight-ThumbSize*.7,ThumbSize*.76,ThumbSize*.26));continue;}if(!seen.Add(index))continue;string path=files[index];keep.Add(path);if(!images.ContainsKey(path))Request(path);double size=Math.Min(ThumbSize*(index==lastIndex?1.25:1),ActualHeight-18);var r=new Rect(x-size/2,ActualHeight-size-8,size,size);if(r.Right<0||r.Left>ActualWidth)continue;dc.PushClip(new RectangleGeometry(r,7,7));dc.DrawRectangle(Ui.Bg,null,r);if(images.TryGetValue(path,out var image)){double scale=Math.Max(r.Width/image.PixelWidth,r.Height/image.PixelHeight);dc.DrawImage(image,new Rect(r.X+(r.Width-image.PixelWidth*scale)/2,r.Y+(r.Height-image.PixelHeight*scale)/2,image.PixelWidth*scale,image.PixelHeight*scale));}dc.Pop();if(index==lastIndex)dc.DrawRoundedRectangle(null,new Pen(new SolidColorBrush(Color.FromRgb(215,63,63)),3),r,7,7);if(VideoThumbnails.IsVideo(path)){dc.PushOpacity(.75);dc.DrawEllipse(Brushes.Black,null,new Point(r.X+r.Width/2,r.Y+r.Height/2),10,10);var ft=host.OverlayLabel("▶");dc.DrawText(ft,new Point(r.X+r.Width/2-ft.Width/2,r.Y+r.Height/2-ft.Height/2));dc.Pop();}hits.Add((r,index));}foreach(var key in images.Keys.Where(k=>!keep.Contains(k)).ToArray())images.Remove(key);}
 void Request(string path){if(failed.Contains(path)||pending.ContainsKey(path)||pending.Count>=40)return;int token=epoch;pending[path]=token;host.View.Thumbs.TryGetValue(path,out var ready);if(ready!=null){images[path]=ready;pending.Remove(path);return;}_=Task.Run(async()=>{BitmapSource? image=null;bool cancelled=false;try{image=VideoThumbnails.IsVideo(path)?await VideoThumbnails.Get(path,180,()=>token==epoch):await cache.Get(path,180,()=>token==epoch);}catch(OperationCanceledException){cancelled=true;}catch{}if(Dispatcher.HasShutdownStarted)return;await Dispatcher.InvokeAsync(()=>{if(pending.TryGetValue(path,out int request)&&request==token)pending.Remove(path);if(token==epoch){if(image!=null)images[path]=image;else if(!cancelled)failed.Add(path);}InvalidateVisual();});});}
}
public partial class MainWindow {public FormattedText OverlayLabel(string text)=>OverlayText(text);public void FilmstripCloseMenu(ContextMenu menu)=>CloseOverlayMenu(menu,()=>{Config.Filmstrip=false;strip.Visibility=Visibility.Collapsed;});}
