using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using SkiaSharp;
namespace gazegallery;
public sealed class LargeRaster {
 public string Path{get;}public int Width{get;}public int Height{get;}public BitmapSource Preview{get;}
 LargeRaster(string path,int w,int h,BitmapSource preview){Path=path;Width=w;Height=h;Preview=preview;}
 public static bool IsLarge(string path){try{using var codec=SKCodec.Create(path);return codec!=null&&((long)codec.Info.Width*codec.Info.Height>64_000_000||Math.Max(codec.Info.Width,codec.Info.Height)>16000);}catch{return false;}}
 public static LargeRaster? Open(string path){using var codec=SKCodec.Create(path);if(codec==null||(long)codec.Info.Width*codec.Info.Height<=64_000_000&&Math.Max(codec.Info.Width,codec.Info.Height)<=16000)return null;int w=codec.Info.Width,h=codec.Info.Height;var size=codec.GetScaledDimensions(Math.Min(1,8192f/Math.Max(w,h)));using var bmp=new SKBitmap(new SKImageInfo(size.Width,size.Height,SKColorType.Bgra8888,SKAlphaType.Premul));var result=codec.GetPixels(bmp.Info,bmp.GetPixels());if(result!=SKCodecResult.Success&&result!=SKCodecResult.IncompleteInput)throw new IOException("Large image preview: "+result);return new(path,w,h,WebImages.Convert(bmp,8192));}
 public (BitmapSource Image,Rect Source) Region(Rect requested,double scale,CancellationToken token){using var codec=SKCodec.Create(Path)??throw new IOException("Cannot decode image detail");var size=codec.GetScaledDimensions((float)Math.Clamp(scale,.125,1));double sx=size.Width/(double)Width,sy=size.Height/(double)Height;int x=Math.Clamp((int)Math.Floor(requested.X*sx),0,size.Width-1),y=Math.Clamp((int)Math.Floor(requested.Y*sy),0,size.Height-1),right=Math.Clamp((int)Math.Ceiling(requested.Right*sx),x+1,size.Width),bottom=Math.Clamp((int)Math.Ceiling(requested.Bottom*sy),y+1,size.Height);int w=right-x,h=bottom-y;var info=new SKImageInfo(size.Width,size.Height,SKColorType.Bgra8888,SKAlphaType.Premul);var status=codec.StartScanlineDecode(info);if(status!=SKCodecResult.Success||codec.ScanlineOrder!=SKCodecScanlineOrder.TopDown)throw new IOException("This large-image format does not provide scanline detail decoding.");if(y>0&&!codec.SkipScanlines(y))throw new IOException("Cannot skip image scanlines");IntPtr row=Marshal.AllocHGlobal(info.RowBytes);try{var pixels=new byte[checked(w*h*4)];for(int i=0;i<h;i++){token.ThrowIfCancellationRequested();if(codec.GetScanlines(row,1,info.RowBytes)!=1)throw new IOException("Incomplete image detail");Marshal.Copy(IntPtr.Add(row,x*4),pixels,i*w*4,w*4);}var bitmap=BitmapSource.Create(w,h,96,96,PixelFormats.Pbgra32,null,pixels,w*4);bitmap.Freeze();return(bitmap,new Rect(x/sx,y/sy,w/sx,h/sy));}finally{Marshal.FreeHGlobal(row);}}
}
public partial class MainWindow {
 LargeRaster? largeRaster;BitmapSource? largeDetail;Rect largeDetailRect=Rect.Empty,largeRequested=Rect.Empty;CancellationTokenSource? detailCancel;bool detailBusy;double lastDetailRequest;int largeEpoch;
 void ClearLarge(){largeEpoch++;detailCancel?.Cancel();largeRaster=null;largeDetail=null;largeDetailRect=largeRequested=Rect.Empty;}
 async void UpdateLargeDetail(){if(largeRaster==null||Mode!="viewer"||View.Image==null||detailBusy||motionClock.Elapsed.TotalSeconds-lastDetailRequest<.15)return;double nativeScale=View.Scale*View.Image.PixelWidth/largeRaster.Width;if(nativeScale<=View.Image.PixelWidth/(double)largeRaster.Width*.9)return;var visible=new Rect(Math.Max(0,-View.Pan.X/nativeScale-100),Math.Max(0,-View.Pan.Y/nativeScale-100),Math.Max(1,(View.ActualWidth+200)/nativeScale),Math.Max(1,(View.ActualHeight+200)/nativeScale));visible.Intersect(new Rect(0,0,largeRaster.Width,largeRaster.Height));if(visible.IsEmpty||largeDetailRect.Contains(visible)&&largeRequested.Width<=visible.Width*1.2)return;lastDetailRequest=motionClock.Elapsed.TotalSeconds;detailBusy=true;detailCancel?.Cancel();detailCancel=new();var token=detailCancel.Token;var raster=largeRaster;int epoch=largeEpoch;try{var result=await Task.Run(()=>raster.Region(visible,nativeScale,token));if(epoch==largeEpoch){largeDetail=result.Image;largeDetailRect=result.Source;largeRequested=visible;View.InvalidateVisual();}}catch(OperationCanceledException){}catch(Exception ex){Paths.Log("large-detail",ex.Message);lastDetailRequest=motionClock.Elapsed.TotalSeconds+10;}finally{detailBusy=false;}}
 void DrawLargeDetail(DrawingContext dc){if(largeRaster==null||largeDetail==null||View.Image==null)return;double scale=View.Scale*View.Image.PixelWidth/largeRaster.Width;dc.DrawImage(largeDetail,new Rect(View.Pan.X+largeDetailRect.X*scale,View.Pan.Y+largeDetailRect.Y*scale,largeDetailRect.Width*scale,largeDetailRect.Height*scale));}
}
