using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Controls.Primitives;
namespace gazegallery;
public partial class MainWindow {
 public List<string> GridPaths=new();public Dictionary<string,double> GridRatios=new(StringComparer.OrdinalIgnoreCase);public int FolderTileCount;double folderWidth=280;bool navigatingTree,autoScroll,slideshow;DateTime slideDeadline;Stopwatch motionClock=Stopwatch.StartNew();double previousMotion;bool? toolbarShown;Button foldersButton=null!,autoButton=null!,fullscreenExit=null!,boardReturn=null!;bool fadeSync;Border treeResize=new();bool resizingTree;double treeResizeStart,treeWidthStart;
 public bool IsFolderTile(int i)=>i>=0&&i<FolderTileCount;
 Task PrepareGrid()=>PrepareProgressiveGrid();
 void RebuildGridPaths(){var list=new List<string>();if(Config.ShowSubfolders&&hasFolder){var parent=Directory.GetParent(Folder);if(parent!=null)list.Add(parent.FullName);else list.Add(Folder);try{list.AddRange(Directory.EnumerateDirectories(Folder).OrderBy(p=>p,new Natural()));}catch{}}int newFolderCount=list.Count;if(GridHoles.Count>0)MergeGridHoles(list);else list.AddRange(Files);FolderTileCount=newFolderCount;list=list.Take(newFolderCount).Concat(list.Skip(newFolderCount).Where(p=>FolderFilter34.Matches(p,gridFilter34))).ToList();GridPaths=list;View.Selected.Clear();}
 void SetupLatest(){if(!Config.Keys.ContainsKey("Open with"))Config.Keys["Open with"]=new[]{"L"};if(!Config.CopyAliasMigration){Config.Keys["Copy"]=Config.Keys["Copy"].Append("Ctrl+C").Distinct().ToArray();Config.CopyAliasMigration=true;}foreach(var pair in new[]{("Autoscroll thumbnails","Space"),("Copy thumbnails","Ctrl+C"),("Scroll up thumbnails","Up"),("Scroll down thumbnails","Down")})if(!Config.Keys.ContainsKey(pair.Item1))Config.Keys[pair.Item1]=new[]{pair.Item2};if(!Config.DailyMenuMigration){if(Config.MenuLayouts.TryGetValue("board",out var boardMenu)&&!boardMenu.Contains("Reset size"))boardMenu.Insert(Math.Max(0,boardMenu.IndexOf("Reset aspect ratio")+1),"Reset size");Config.DailyMenuMigration=true;}if(!Config.InputMigration){Config.Keys["Previous"]=Config.Keys["Previous"].Where(k=>k!="Space").ToArray();Config.Keys["Play / pause"]=new[]{"Space"};Config.InputMigration=true;}foreach(var pair in new[]{("Select all collage","O"),("Equal area collage","L"),("Pack collage","P")})if(!Config.Keys.ContainsKey(pair.Item1))Config.Keys[pair.Item1]=new[]{pair.Item2};Config.Save();
  var row=(Grid)toolbarHost.Child;foldersButton=Ui.Button("Folders",ShowFolders);foldersButton.HorizontalAlignment=HorizontalAlignment.Left;var leftTools=new StackPanel{Orientation=Orientation.Horizontal};leftTools.Children.Add(foldersButton);var viewMode=Ui.Button("View mode",()=>Run(()=>SetMode("viewer")));leftTools.Children.Add(viewMode);leftTools.Tag="grid-navigation";Grid.SetColumn(leftTools,0);row.Children.Add(leftTools);
  fadeToggle.Checked+=(_,_)=>SaveFade(true);fadeToggle.Unchecked+=(_,_)=>SaveFade(false);
  treeResize.Width=6;treeResize.Background=Brushes.Transparent;treeResize.Cursor=Cursors.SizeWE;treeResize.HorizontalAlignment=HorizontalAlignment.Left;treeResize.Visibility=Visibility.Collapsed;treeResize.MouseLeftButtonDown+=(_,e)=>{resizingTree=true;treeResizeStart=e.GetPosition(root).X;treeWidthStart=folderWidth;treeResize.CaptureMouse();e.Handled=true;};treeResize.MouseMove+=(_,e)=>{if(!resizingTree)return;folderWidth=Math.Clamp(treeWidthStart+e.GetPosition(root).X-treeResizeStart,160,Math.Max(180,root.ActualWidth*.65));PanelLayout();};treeResize.MouseLeftButtonUp+=(_,_)=>{resizingTree=false;treeResize.ReleaseMouseCapture();};root.Children.Add(treeResize);
  fullscreenExit=Ui.Button("×",()=>{if(IsActualFullscreen36)ToggleFullscreen();else HideFullscreenExit36();});fullscreenExit.Width=fullscreenExit.Height=32;fullscreenExit.Clip=new EllipseGeometry(new Rect(0,0,32,32));fullscreenExit.FontSize=12;fullscreenExit.Content=new System.Windows.Shapes.Path{Data=Geometry.Parse("M 1,1 L 13,13 M 13,1 L 1,13"),Stroke=Brushes.White,StrokeThickness=1,Width=14,Height=14,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};fullscreenExit.Padding=new Thickness(0);fullscreenExit.HorizontalAlignment=HorizontalAlignment.Center;fullscreenExit.VerticalAlignment=VerticalAlignment.Top;fullscreenExit.Background=new SolidColorBrush(Color.FromRgb(50,50,50));fullscreenExit.Opacity=0;fullscreenExit.RenderTransform=new TranslateTransform(0,-52);fullscreenExit.Visibility=Visibility.Collapsed;root.Children.Add(fullscreenExit);Panel.SetZIndex(fullscreenExit,100);
 }
 void SaveFade(bool value){if(fadeSync)return;if(Mode=="board")Config.FadeCollage=value;else Config.FadeToolbar=value;Config.Save();toolbarShown=null;}
 bool FadeEnabled=>Mode=="board"?Config.FadeCollage:Config.FadeToolbar;
 void ModeChrome(){if(Mode!="grid"&&fadeToggle.Parent is StackPanel rightTools)foreach(var old in rightTools.Children.OfType<Button>().ToArray())rightTools.Children.Remove(old);fadeSync=true;fadeToggle.IsChecked=FadeEnabled;fadeSync=false;toolbarHost.BeginAnimation(OpacityProperty,null);toolbarHost.Opacity=FadeEnabled?0:1;toolbarShown=FadeEnabled?false:true;foldersButton.Visibility=Mode=="grid"?Visibility.Visible:Visibility.Collapsed;}
 bool exitShown;
 void AnimateChrome(){if(!chromeInitialized)return;var pointer=Mouse.GetPosition(root);bool near=pointer.X>=0&&pointer.X<=root.ActualWidth&&pointer.Y>=toolbarHost.Margin.Top&&pointer.Y<=toolbarHost.Margin.Top+ToolbarHeight;bool show=!FadeEnabled||near;if(BoardCropItem!=null)show=false;toolbarHost.IsHitTestVisible=BoardCropItem==null;if(toolbarShown!=show){toolbarShown=show;toolbarHost.BeginAnimation(OpacityProperty,new DoubleAnimation(show?1:0,TimeSpan.FromMilliseconds(show?180:220)){EasingFunction=new QuadraticEase{EasingMode=EasingMode.EaseInOut}});}fullscreenExit.Visibility=IsActualFullscreen36&&Config.FullscreenExit&&BoardCropItem==null?Visibility.Visible:Visibility.Collapsed;fullscreenExit.IsHitTestVisible=fullscreenExit.Visibility==Visibility.Visible;bool exit=fullscreenExit.Visibility==Visibility.Visible&&(pointer.Y<(Mode!="viewer"?ToolbarHeight+60:60)||fullscreenExit.IsMouseOver);if(exit!=exitShown){exitShown=exit;fullscreenExit.BeginAnimation(OpacityProperty,new DoubleAnimation(exit?.75:0,TimeSpan.FromMilliseconds(180)));((TranslateTransform)fullscreenExit.RenderTransform).BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(exit?(Mode!="viewer"?ToolbarHeight+12:12):-52,TimeSpan.FromMilliseconds(200)){EasingFunction=new QuadraticEase()});}}
 void AddLatestToolbar(){if(Mode=="grid"){Ui.Check(toolbar,"Subfolders",Config.ShowSubfolders,v=>{Config.ShowSubfolders=v;Config.Save();RebuildGridPaths();View.Scroll=0;View.LayoutTiles();});autoButton=Ui.Button(autoScroll?"Stop scroll":"Autoscroll",()=>{ToggleAutoscroll();});toolbar.Children.Add(autoButton);toolbar.Children.Add(Ui.Button("Speed",SetScrollSpeed));toolbar.Children.Add(new TextBlock{Text="Zoom:",FontSize=12,Foreground=Ui.Fg,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(5)});toolbar.Children.Add(Ui.Button("In",()=>ColumnStep(-1)));toolbar.Children.Add(Ui.Button("Out",()=>ColumnStep(1)));var top=Ui.Button("To top",()=>{View.Scroll=0;View.InvalidateVisual();});top.PreviewMouseRightButtonUp+=(_,e)=>{e.Handled=true;var m=new ContextMenu();var i=new MenuItem{Header="To bottom"};i.Click+=(_,_)=>ToBottom();m.Items.Add(i);m.IsOpen=true;};if(fadeToggle.Parent is StackPanel rightTools){foreach(var old in rightTools.Children.OfType<Button>().ToArray())rightTools.Children.Remove(old);rightTools.Children.Insert(0,top);}}ModeChrome();}
 void SetScrollSpeed()=>ScrollSpeedMenu();
 void PauseScroll(){autoScroll=false;if(autoButton!=null)autoButton.Content="Autoscroll";}
 void SetSlideTime(){var w=Ui.Dialog(this,"Slideshow interval",330,275);var p=new StackPanel{Margin=new Thickness(18)};p.Children.Add(Ui.Label("Minutes (0 - 999)",12));var minutes=Ui.Input(((int)Config.SlideSeconds/60).ToString());minutes.Width=90;minutes.HorizontalAlignment=HorizontalAlignment.Left;p.Children.Add(minutes);p.Children.Add(Ui.Label("Seconds (0 - 59.9)",12));var seconds=Ui.Input((Config.SlideSeconds%60).ToString("0.#",System.Globalization.CultureInfo.InvariantCulture));seconds.Width=90;seconds.HorizontalAlignment=HorizontalAlignment.Left;p.Children.Add(seconds);minutes.TextChanged+=(_,_)=>{if(double.TryParse(minutes.Text,out double n)&&n>999)minutes.Text="999";};var error=Ui.Label("",11);p.Children.Add(error);var row=new WrapPanel();void Save(){if(string.IsNullOrWhiteSpace(minutes.Text))minutes.Text="0";if(string.IsNullOrWhiteSpace(seconds.Text))seconds.Text="0";if(!int.TryParse(minutes.Text,out int m)||m<0||!double.TryParse(seconds.Text,System.Globalization.NumberStyles.AllowDecimalPoint,System.Globalization.CultureInfo.InvariantCulture,out double s)||s<0||s>59.9||Math.Abs(s*10-Math.Round(s*10))>.00001||m*60+s<=0){error.Text="Enter a positive time within the shown ranges.";return;}Config.SlideSeconds=Math.Min(999,m)*60+s;Config.Save();slideRemaining=Config.SlideSeconds;slideDeadline=DateTime.Now.AddSeconds(Config.SlideSeconds);w.Close();View.InvalidateVisual();}row.Children.Add(Ui.Button("Save",Save));row.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(row);w.Content=p;w.ShowDialog();}
 void ToggleSlideshow()=>ChangeSlideshow();
 bool slideBusy;
 void AdvanceTimedModes(){if(focusSuspended34)return;double now=motionClock.Elapsed.TotalSeconds,dt=Math.Clamp(now-previousMotion,0,.05);previousMotion=now;if(slidePaused)return;if(!slideshow||slideBusy||Mode!="viewer"||Cropping||OwnedWindows.Count>0||Operations.Busy){slideDeadline=DateTime.Now.AddSeconds(Config.SlideSeconds);return;}if(videoActive&&video!=null?!video.Ended:DateTime.Now<slideDeadline)return;slideBusy=true;Run(async()=>{try{await ShowIndex(Index+1,false);}finally{slideDeadline=DateTime.Now.AddSeconds(Config.SlideSeconds);slideBusy=false;}});}
 async Task SaveCropCopy(){if(!Cropping||sourceImage==null||current==null)return;string ext=Path.GetExtension(current),stem=Path.GetFileNameWithoutExtension(current);string target=FileNames.Available(Path.Combine(Folder,stem+"_cropped_01"+ext));Paths.Guard(target);var area=FullEditArea();if(area.IsEmpty){Toast("Crop must overlap the image");return;}Operations.Busy=true;try{var source=await EditedFullImage();var result=await Sta.Run(()=>CropPixels(source,area,Config.Oled));await Task.Run(()=>{if(ExtendedImages.Supports(current))ExtendedImages.Save(result,target,ext);else if(ext.Equals(".webp",StringComparison.OrdinalIgnoreCase))WebImages.SaveWebP(result,target);else{BitmapEncoder enc=ext.ToLowerInvariant() switch{".png"=>new PngBitmapEncoder(),".bmp"=>new BmpBitmapEncoder(),_=>new JpegBitmapEncoder{QualityLevel=95}};enc.Frames.Add(BitmapFrame.Create(result));using var f=File.Create(target);enc.Save(f);}});Toast("Saved edited copy — "+Path.GetFileName(target));}finally{Operations.Busy=false;}}
 void ResetBoardAspect(){if(View.BoardSelection.Count==0)return;View.Snapshot();foreach(var item in View.BoardSelection){double area=item.Rect.Width*item.Rect.Height,ratio=item.NaturalWidth/Math.Max(1,item.NaturalHeight);double w=Math.Sqrt(area*ratio),h=w/ratio;item.Rect=new Rect(item.Rect.X+(item.Rect.Width-w)/2,item.Rect.Y+(item.Rect.Height-h)/2,w,h);}View.InvalidateVisual();}
}


