using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Diagnostics;using System.Windows.Media;
namespace gazegallery;
public partial class MainWindow {
 async Task VerifyLatest21(List<object> report,Action<bool,string> check,string work){
 check(new Settings().SmoothFilter=="Bicubic","Fresh profile bicubic default");check(ResolveViewerAction("P")=="Filtering"&&ResolveViewerAction("L")=="Open with","Viewer P and L exclude collage bindings");check(plugins.Any(p=>p.Id=="gazegallery.wallpaper"),"Wallpaper plugin loads separately");check(TryPluginKey("U"),"Drawing plugin U shortcut opens overlay");EndPluginOverlay();
 string stress=Path.Combine(Paths.Test,"_testing","stress-3000-small");await Open(stress);ShowFolders();check(folderPanel.Visibility==Visibility.Visible,"Folder tree open for transition test");for(int i=0;i<6;i++){var loading=SetMode("grid");await SetMode("viewer");await loading;check(Mode=="viewer"&&!GridLoading,"Old thumbnail load cannot override viewer "+i);}await SetMode("grid");check(toolbar.Children.Count>=8&&toolbar.Visibility==Visibility.Visible,"Large-folder toolbar populated after repeated entry");check(folderPanel.Visibility==Visibility.Visible,"Tree persists through viewer/thumbnail transitions");await Task.Delay(900);check(View.Selected.Count==1,"Viewed thumbnail selected after flash");
 Config.ScrollSpeed=240;await Task.Delay(600);autoScroll=true;var samples=new List<double>();var timer=Stopwatch.StartNew();double last=0;EventHandler render=(_,_)=>{double now=timer.Elapsed.TotalMilliseconds;if(last>0)samples.Add(now-last);last=now;};CompositionTarget.Rendering+=render;await Task.Delay(5000);CompositionTarget.Rendering-=render;autoScroll=false;report.Add(new{metric="autoscroll_3000_240pxs",samples=samples.Count,medianMs=samples.Order().ElementAtOrDefault(samples.Count/2),p95Ms=samples.Order().ElementAtOrDefault((int)(samples.Count*.95)),maximumMs=samples.DefaultIfEmpty().Max(),scroll=View.Scroll});check(View.Scroll>100,"Autoscroll advances through 3000 entries");
 string siblings=Path.Combine(work,"siblings");Directory.CreateDirectory(Path.Combine(siblings,"2"));Directory.CreateDirectory(Path.Combine(siblings,"10"));File.Copy(Path.Combine(Paths.Test,"small_mario.png"),Path.Combine(siblings,"2","one.png"));Config.SiblingNavigation=true;await Open(Path.Combine(siblings,"2"));await NavigateViewer(1);check(Folder.EndsWith("10")&&Files.Count==0,"Sibling navigation enters empty folder in natural order");await NavigateViewer(1);check(Folder.EndsWith("10"),"Sibling navigation stops at final sibling");Config.SiblingNavigation=false;
 await Empty();await NavigateFolder(stress);check(hasFolder&&Files.Count==3000&&Mode=="grid"&&toolbar.Children.Count>=8,"Folder tree works from empty launch state");await SetMode("viewer");
 }
}
