using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
namespace gazegallery;
public partial class MainWindow {
 public bool ThumbUnavailable(string path)=>thumbFailed.Contains(path);
 void HighlightFolder(){if(folderPanel.Child is not DockPanel dock)return;var tree=dock.Children.OfType<TreeView>().FirstOrDefault();if(tree==null)return;void Walk(ItemsControl parent){foreach(var node in parent.Items.OfType<TreeViewItem>()){if(node.Tag is not string path)continue;if(string.Equals(path,Folder,StringComparison.OrdinalIgnoreCase)){node.IsSelected=true;node.IsExpanded=true;node.BringIntoView();}else if(Folder.StartsWith(path.TrimEnd('\\')+"\\",StringComparison.OrdinalIgnoreCase)){node.IsExpanded=true;Walk(node);}}}Walk(tree);}
 List<string> MenuOrder(string mode){foreach(var obsolete in Config.MenuLayouts.Values)obsolete.RemoveAll(a=>a=="Sort mode"||a=="Borderless windowed"||a=="Image-sized borderless");Config.Keys.Remove("Sort mode");if(Config.MenuLayouts.TryGetValue(mode,out var saved)){for(int i=0;i<saved.Count;i++)if(saved[i]=="Open file")saved[i]="Open file with external program";saved.Remove("Settings");int position=saved.LastIndexOf("Diagnostics");if(position>=0)saved.Insert(position+1,"Settings");else saved.Insert(Math.Max(0,saved.Count-2),"Settings");if(mode=="board"&&!saved.Contains("Paste"))saved.Insert(Math.Max(0,saved.IndexOf("Select all collage")),"Paste");if(mode!="board"&&!Config.OverlayMenu26){saved.RemoveAll(a=>a is "Slideshow" or "Sort mode" or "Diagnostics" or "Navigation arrows");saved.RemoveAll(a=>a=="Overlays");int collage=saved.IndexOf("Collage");int at=collage>=0?collage+1:0;if(at<saved.Count&&saved[at]=="-")at++;else saved.Insert(at++,"-");saved.Insert(at++,"Overlays");saved.Insert(at,"-");Config.OverlayMenu26=true;}return saved;}var defaults=mode=="board"?new[]{"Remove selected images","Reset aspect ratio","Reset size","Paste","Select all collage","Equal area collage","Pack collage","Normalize width","Normalize height","Align in a row","Align in a column","Crop","Fullscreen","Save as","-","Settings","-","Return","Exit"}:new[]{"Folder tree","Thumbnails","Collage","-","Overlays","-","Quick sort","Copy","Save as","Trash","Undo","Crop","-","Open file with external program","Shuffle","Fullscreen","Settings","-","Exit"};var list=defaults.Where(a=>a=="Settings"||!Config.HiddenActions.Contains(a)).ToList();Config.MenuLayouts[mode]=list;return list;}
 void ShowContext(Point point){if(BoardCropItem!=null)return;if(Mode=="grid"){int target=View.HitTile(point);if(target>=0&&!View.Selected.Contains(target))SelectGridTile(target);}var cm=new ContextMenu{HorizontalContentAlignment=HorizontalAlignment.Stretch};if(Mode=="board"){int hit=View.HitBoard(point);if(hit>=0&&View.BoardSelection.Count<2){View.BoardSelection.Clear();View.BoardSelection.Add(View.Board[hit]);View.BoardSelected=hit;View.InvalidateVisual();}}foreach(var name in MenuOrder(Mode).Where(a=>a!="Exit"&&(Mode!="board"||a!="Return")).Concat(Mode=="board"?new[]{"Return","Exit"}:new[]{"Exit"})){if(name=="-"){if(cm.Items.Count==0||cm.Items[cm.Items.Count-1] is Separator)continue;cm.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});continue;}var label=name switch{"Return"=>collageReturnMode=="grid"?"Return to thumbnails":"Return to view mode","Collage"=>"Start collage","Crop" when Mode!="board"=>"Edit mode","Save as" when Mode=="board"=>"Export","Select all collage"=>"Select all","Equal area collage"=>"Equal area","Pack collage"=>"Pack",_=>name};var item=new MenuItem{Header=label,InputGestureText=Config.Keys.TryGetValue(name,out var keys)?string.Join(" / ",keys.Take(name=="Select all collage"?1:2).Select(FriendlyKey)):""};if(name=="Collage"&&Mode=="grid")item.IsEnabled=SelectedGridImages().Length>0;if(Mode=="board"&&name=="Crop")item.IsEnabled=View.BoardSelection.Count==1;if(Mode=="board"&&name is "Normalize width" or "Normalize height" or "Align in a row" or "Align in a column")item.IsEnabled=View.BoardSelection.Count>=2;if(name=="Overlays"){item.InputGestureText="▸";PopulateOverlays(item);PreferRightSubmenu(item);}else if(name=="Open file with external program"){item.InputGestureText="▸";PopulateExternalMenu(item);PreferRightSubmenu(item);}else if(name=="Image-sized borderless"){item.IsCheckable=true;item.IsChecked=imageWindow;item.InputGestureText=imageWindow?"✓":"";item.IsEnabled=ExternalActionImage!=null;item.Click+=(_,_)=>Run(ToggleImageWindow);}else item.Click+=(_,_)=>Run(()=>MenuAction(name));if(Mode=="grid"&&SelectedGridFolders().Length>0&&name is "Copy" or "Save as" or "Crop" or "Quick sort" or "Open file with external program")item.IsEnabled=false;if(!CanContextAction(name))item.IsEnabled=false;cm.Items.Add(item);}if(!MenuOrder(Mode).Contains("Settings")){var settings=new MenuItem{Header="Settings"};settings.Click+=(_,_)=>ShowSettings();cm.Items.Insert(Math.Max(0,cm.Items.Count-1),settings);}AddPluginCommands(cm);NormalizeMenuSeparators(cm);cm.PreviewMouseRightButtonDown+=(_,e)=>e.Handled=true;cm.PreviewMouseRightButtonUp+=(_,e)=>{if(OverlayEntry33(e.OriginalSource)!=null){lastRightClick=0;e.Handled=true;return;}if(TryDoubleRight())cm.IsOpen=false;e.Handled=true;};cm.IsOpen=true;}
 async System.Threading.Tasks.Task MenuAction(string name){switch(name){case "Overlays":OverlaysMenu();break;case "Normalize width":case "Normalize height":case "Align in a row":case "Align in a column":ArrangeBoard(name);break;case "Crop" when Mode=="board":await StartBoardCrop();break;case "Remove selected images":RemoveBoardSelection();break;case "Reset aspect ratio":ResetBoardAspect();break;case "Reset size":ResetBoardSize();break;case "Select all collage":ToggleBoardSelection();break;case "Equal area collage":NormalizeBoard();break;case "Pack collage":PackBoard();break;case "Return":await ReturnFromCollage();break;default:await Action(name);break;}}
 void EditMenu(string mode){var w=Ui.Dialog(this,mode+" context menu",520,610);var order=MenuOrder(mode).ToList();var panel=new DockPanel{Margin=new Thickness(16)};var controls=new StackPanel{Orientation=Orientation.Horizontal};var list=new ListBox{Background=Ui.Bg,Foreground=Ui.Fg,BorderThickness=new Thickness(0)};void Refresh(int selected=0){list.ItemsSource=null;list.ItemsSource=order;list.SelectedIndex=Math.Clamp(selected,0,Math.Max(0,order.Count-1));}void Move(int d){int i=list.SelectedIndex,j=i+d;if(i<0||j<0||j>=order.Count||order[i]=="Exit"||order[j]=="Exit")return;(order[i],order[j])=(order[j],order[i]);Refresh(j);}controls.Children.Add(Ui.Button("Up",()=>Move(-1)));controls.Children.Add(Ui.Button("Down",()=>Move(1)));controls.Children.Add(Ui.Button("Separator",()=>{order.Insert(Math.Max(0,list.SelectedIndex),"-");Refresh();}));controls.Children.Add(Ui.Button("Remove",()=>{if(list.SelectedItem is string a&&a!="Settings"&&a!="Exit"){order.RemoveAt(list.SelectedIndex);Refresh();}}));DockPanel.SetDock(controls,Dock.Top);panel.Children.Add(controls);var bottom=new StackPanel();var available=Config.Keys.Keys.Where(k=>k!="Sort mode").Concat(new[]{"Open file","Open folder","Collage","Slideshow","Settings","Return","Remove selected images","Reset aspect ratio","Reset size","Normalize width","Normalize height","Align in a row","Align in a column"}).Distinct().Order().ToArray();var choices=new ComboBox{ItemsSource=available,SelectedIndex=0,Margin=new Thickness(5)};bottom.Children.Add(choices);bottom.Children.Add(Ui.Button("Add action",()=>{if(choices.SelectedItem is string a&&!order.Contains(a)){order.Insert(Math.Max(0,order.Count-1),a);Refresh();}}));bottom.Children.Add(Ui.Button("Save arrangement",()=>{order.RemoveAll(a=>a=="Exit");if(!order.Contains("Settings"))order.Add("Settings");order.Add("Exit");Config.MenuLayouts[mode]=order;Config.Save();w.Close();}));DockPanel.SetDock(bottom,Dock.Bottom);panel.Children.Add(bottom);panel.Children.Add(list);Refresh();w.Content=panel;w.ShowDialog();}
 void CaptureBinding(Window dialog,TextBox input){Toast("Press the key or mouse button to add; Escape cancels");KeyEventHandler? keys=null;MouseButtonEventHandler? mouse=null;void Finish(string? key){dialog.PreviewKeyDown-=keys;dialog.PreviewMouseDown-=mouse;if(key!=null){var values=input.Text.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries).ToList();if(!values.Contains(key))values.Add(key);input.Text=string.Join(", ",values);}}keys=(_,e)=>{e.Handled=true;if(e.Key is Key.LeftCtrl or Key.RightCtrl or Key.LeftShift or Key.RightShift or Key.LeftAlt or Key.RightAlt)return;Finish(e.Key==Key.Escape?null:KeyName(e));};mouse=(_,e)=>{string? key=e.ChangedButton switch{MouseButton.Middle=>"MouseMiddle",MouseButton.XButton1=>"MouseBack",MouseButton.XButton2=>"MouseForward",_=>null};if(key!=null){e.Handled=true;Finish(key);}};dialog.PreviewKeyDown+=keys;dialog.PreviewMouseDown+=mouse;dialog.Focus();}
}
