using System;using System.Diagnostics;using System.Runtime.InteropServices;using System.Windows;using System.Windows.Controls;
namespace gazegallery;
public partial class MainWindow {
 bool focusSuspended34,resumeScroll34,resumeSlide34,resumeAnimation34,resumeMovie34;Video? suspendedMovie34;AnimatedImage? suspendedAnimation34;int suspendedGeneration34,suspendedFilter34;string suspendedFolder34="",suspendedMode34="";DateTime focusPoll34,suspendedAt34;
 [DllImport("user32.dll")]static extern IntPtr GetForegroundWindow();
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr window,out uint process);
 public static bool OwnFocus34(uint process)=>process==(uint)Environment.ProcessId;
 void PollFocus34(bool force=false){if(!force&&(DateTime.UtcNow-focusPoll34).TotalMilliseconds<100)return;focusPoll34=DateTime.UtcNow;GetWindowThreadProcessId(GetForegroundWindow(),out uint pid);ApplyFocus34(!Config.PauseMotionOnBlur||OwnFocus34(pid));}
 public void ApplyFocus34(bool active){if(!active&&focusSuspended34&&(generation!=suspendedGeneration34||video!=suspendedMovie34||animation!=suspendedAnimation34))focusSuspended34=false;if(!active&&!focusSuspended34){focusSuspended34=true;suspendedAt34=DateTime.UtcNow;suspendedGeneration34=generation;suspendedFilter34=filterRevision34;suspendedFolder34=Folder;suspendedMode34=Mode;suspendedMovie34=video;suspendedAnimation34=animation;resumeMovie34=videoActive&&video?.Playing==true;resumeAnimation34=animation?.Playing==true;resumeScroll34=autoScroll;resumeSlide34=slideshow&&!slidePaused;if(resumeMovie34)video!.SetPaused(true);if(resumeAnimation34)animation!.Playing=false;if(resumeScroll34)PauseScroll();if(resumeSlide34){slideRemaining=Math.Max(0,(slideDeadline-DateTime.Now).TotalSeconds);slidePaused=true;slidePausedAt=DateTime.UtcNow;}ClosePeek34();}else if(active&&focusSuspended34){focusSuspended34=false;bool same=generation==suspendedGeneration34&&Folder==suspendedFolder34&&Mode==suspendedMode34&&filterRevision34==suspendedFilter34;if(same){if(resumeMovie34&&video==suspendedMovie34&&videoActive)video!.SetPaused(false);if(resumeAnimation34&&animation==suspendedAnimation34)animation!.Playing=true;if(resumeSlide34&&slideshow&&slidePaused){if(slidePausedAt.HasValue)slideVisualStart+=DateTime.UtcNow-slidePausedAt.Value;slidePausedAt=null;slidePaused=false;slideDeadline=DateTime.Now.AddSeconds(slideRemaining);}if(resumeScroll34&&Mode=="grid"){if(autoBoundarySince!=default)autoBoundarySince+=DateTime.UtcNow-suspendedAt34;autoScroll=true;if(autoButton!=null)autoButton.Content="Stop scroll";lastScrollTick=motionClock.Elapsed.TotalSeconds;}}suspendedMovie34=null;suspendedAnimation34=null;}}
 long? loopA34,loopB34;TextBlock? loopLabel34;
 void SetAB34(bool end){if(!videoActive||video==null)return;if(slideshow)EndSlideshow();long at=video.Time;if(!end){loopA34=at;loopB34=null;}else {if(loopA34==null||at<=loopA34.Value){Toast("Set A first, then set B after A");return;}loopB34=at;}video.SetLoop(false);video.SetAB(loopA34,loopB34);RefreshAB34();}
 void ClearAB34(){loopA34=loopB34=null;if(video!=null){video.SetAB(null,null);video.SetLoop(!slideshow);}RefreshAB34();}
 void RefreshAB34(){if(loopLabel34!=null)loopLabel34.Text=loopA34==null?"A–B loop: off":$"A {TimeSpan.FromMilliseconds(loopA34.Value):mm\\:ss\\.f} · B {(loopB34.HasValue?TimeSpan.FromMilliseconds(loopB34.Value).ToString(@"mm\:ss\.f"):"not set")}";}
}

