using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Animation;
namespace gazegallery;
public partial class MainWindow {
 Button? quickModeButton;DateTime boundaryArmed,autoBoundarySince;int boundaryDirection;bool boundaryBusy;double treeHeaderHeight=38;
 void ToggleQuickCopy(){quickCopy=!quickCopy;Quick=false;ToggleQuick();quickModeButton?.BeginAnimation(OpacityProperty,new DoubleAnimation(.25,1,TimeSpan.FromMilliseconds(300)));}
 void ScrollGridBy(double delta){double end=Math.Max(0,View.GridBottom-View.GridViewport35);int direction=Math.Sign(delta);bool boundary=direction<0?View.Scroll<=.01:View.Scroll>=end-.01;if(boundary){if(Files.Count==0)return;if(GridMetadataLoading){Toast("Jump to bottom is not ready\nBuffering",2);return;}if(boundaryDirection==direction&&(DateTime.UtcNow-boundaryArmed).TotalSeconds>=.5&&(DateTime.UtcNow-boundaryArmed).TotalSeconds<6){boundaryDirection=0;Run(()=>CrossGridBoundary(direction));}else if(boundaryDirection!=direction||(DateTime.UtcNow-boundaryArmed).TotalSeconds>=6){boundaryDirection=direction;boundaryArmed=DateTime.UtcNow;Toast("Scroll "+(direction>0?"down":"up")+" again to "+(Config.SiblingNavigation?(direction>0?"go to next folder":"go to previous folder"):"loop"),3);}return;}boundaryDirection=0;autoBoundarySince=default;View.Scroll=Math.Clamp(View.Scroll+delta,0,end);View.InvalidateVisual();}
 async Task CrossGridBoundary(int direction){if(boundaryBusy)return;boundaryBusy=true;bool resume=autoScroll;try{if(!Config.SiblingNavigation){View.Scroll=direction>0?0:Math.Max(0,View.GridBottom-View.GridViewport35);View.InvalidateVisual();return;}var parent=Directory.GetParent(Folder);if(parent==null)return;var siblings=Directory.GetDirectories(parent.FullName).OrderBy(p=>p,new Natural()).ToArray();if(siblings.Length==0)return;int index=Array.FindIndex(siblings,p=>p.Equals(Folder,StringComparison.OrdinalIgnoreCase));string target=siblings[(index+direction+siblings.Length)%siblings.Length];if(target!=Folder)await NavigateFolder(target);View.Scroll=direction>0?0:Math.Max(0,View.GridBottom-View.GridViewport35);View.InvalidateVisual();}finally{boundaryBusy=false;autoBoundarySince=default;if(resume&&Mode=="grid"){autoScroll=true;lastScrollTick=motionClock.Elapsed.TotalSeconds;if(autoButton!=null)autoButton.Content="Stop scroll";}}}
 void AddTreeHeader(DockPanel dock){var header=new StackPanel{Orientation=Orientation.Horizontal,Height=treeHeaderHeight};header.Children.Add(Ui.Button("Folders",ShowFolders));header.Children.Add(Ui.Button(Mode=="grid"?"View mode":"Thumbnails",()=>Run(()=>SetMode(Mode=="grid"?"viewer":"grid"))));DockPanel.SetDock(header,Dock.Top);dock.Children.Insert(0,header);}
 void RefreshTreeHeader(){if(folderPanel.Visibility!=Visibility.Visible||folderPanel.Child is not DockPanel dock)return;if(dock.Children.Count>0&&dock.Children[0] is StackPanel old&&old.Tag as string=="mode-header")dock.Children.RemoveAt(0);AddTreeHeader(dock);((FrameworkElement)dock.Children[0]).Tag="mode-header";}
}
