using System;using System.Globalization;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace gazegallery;
public partial class MainWindow {
 double timerOpacity=1;DateTime timerOpacityTime=DateTime.UtcNow;bool slidePaused;double slideRemaining;bool resumeVideo;
 FormattedText OverlayText(string value)=>new(value,CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Consolas"),12,Ui.Fg,VisualTreeHelper.GetDpi(View).PixelsPerDip);
 string PositionText=>$"[{(Files.Count==0?0:Index+1)}/{Files.Count}]";
 string ZoomText{get{double scale=View.Scale*(largeRaster==null||View.Image==null?1:View.Image.PixelWidth/(double)largeRaster.Width);return $"{scale*100:0.##}%";}}
 double RemainingSeconds=>!slideshow?Config.SlideSeconds:videoActive&&video!=null?Math.Max(0,(video.Length-video.Time)/1000.0):slidePaused?slideRemaining:Math.Max(0,(slideDeadline-DateTime.Now).TotalSeconds);
 string TimerText{get{long s=(long)Math.Ceiling(RemainingSeconds);return $"{s/60:000}min {s%60:00}sec";}}
 Rect OverlayRect(string text,int row)=>new(Math.Max(8,View.ActualWidth-OverlayText("999min 59sec").Width-36),22+row*30,OverlayText(text).Width+12,25);
 Rect ZoomOverlay=>OverlayRect(ZoomText,0);public Rect PositionOverlay=>OverlayRect(PositionText,1);Rect SlideOverlay=>OverlayRect(TimerText,2);
 void DrawOverlay(DrawingContext dc,string value,int row,bool timer=false){var rect=OverlayRect(value,row);var text=OverlayText(value);if(timer){int zeros=0;while(zeros<3&&value[zeros]=='0')zeros++;if(zeros>0){var faded=Ui.Fg.Clone();faded.Opacity=.4;text.SetForegroundBrush(faded,0,zeros);}int secondsStart=value.IndexOf(' ')+1;int secondZeros=0;while(secondZeros<2&&value[secondsStart+secondZeros]=='0')secondZeros++;if(secondZeros>0){var faded=Ui.Fg.Clone();faded.Opacity=.4;text.SetForegroundBrush(faded,secondsStart,secondZeros);}}dc.PushOpacity(.75);dc.DrawRoundedRectangle(Config.Oled?Brushes.Black:Ui.Canvas,null,rect,5,5);dc.Pop();dc.DrawText(text,new Point(rect.X+6,rect.Y+5));}
 void DrawOverlays(DrawingContext dc){if(Config.ZoomIndicator&&View.Image!=null)DrawOverlay(dc,ZoomText,0);if(Config.PositionIndicator)DrawOverlay(dc,PositionText,1);if(Config.SlideshowTimer){var near=SlideOverlay;near.Inflate(35,25);bool show=!Config.TimerAutoHide||near.Contains(System.Windows.Input.Mouse.GetPosition(View));double elapsed=Math.Clamp((DateTime.UtcNow-timerOpacityTime).TotalSeconds,0,.1);timerOpacityTime=DateTime.UtcNow;timerOpacity=Math.Clamp(timerOpacity+(show?1:-1)*elapsed/0.2,0,1);dc.PushOpacity(timerOpacity);DrawOverlay(dc,TimerText,2,true);dc.Pop();}}
 void ChangeSlideshow(){if(!slideshow){slideshow=true;slidePaused=false;slideRemaining=Config.SlideSeconds;slideDeadline=DateTime.Now.AddSeconds(slideRemaining);video?.SetLoop(false);if(View.Image!=null&&current!=null&&!Paths.Motion(current))BeginSlideVisual(View.Image,generation);}else if(slidePaused){if(slidePausedAt.HasValue)slideVisualStart+=DateTime.UtcNow-slidePausedAt.Value;slidePausedAt=null;slidePaused=false;slideDeadline=DateTime.Now.AddSeconds(slideRemaining);if(resumeVideo&&video!=null&&!video.Playing)video.Pause();}else{slideRemaining=Math.Max(0,(slideDeadline-DateTime.Now).TotalSeconds);slidePaused=true;slidePausedAt=DateTime.UtcNow;resumeVideo=video?.Playing==true;if(resumeVideo)video?.Pause();}Toast(slidePaused?"Slideshow paused":"Slideshow started");View.InvalidateVisual();}
 void EndSlideshow(){bool wasRunning=slideshow;holdingSlide33=false;slideshow=false;slidePausedAt=null;previousSlide=null;slideBackground=null;visualGeneration++;slidePaused=false;slideRemaining=Config.SlideSeconds;video?.SetLoop(true);if(wasRunning)Toast("Slideshow ended");View.InvalidateVisual();}
 void SlideshowMenu()=>SlideshowMenu33().IsOpen=true;
 ContextMenu SlideshowMenu33(){var menu=new ContextMenu();void Add(string title,Action action){var item=new MenuItem{Header=title};item.Click+=(_,_)=>action();menu.Items.Add(item);}Add("Start / Stop",StartStopSlideshow33);Add("Set time",SetSlideTime);Add("Effects",SlideshowOptions);var auto=new MenuItem{Header="Auto-hide timer",IsCheckable=true,IsChecked=Config.TimerAutoHide,InputGestureText="move mouse near to show again"};auto.Click+=(_,_)=>{Config.TimerAutoHide=auto.IsChecked;Config.Save();};menu.Items.Add(auto);CloseOverlayMenu(menu,()=>{Config.SlideshowTimer=false;EndSlideshow();},"End slideshow and close overlay");return menu;}
 void PositionContext()=>BuildPositionMenu35().IsOpen=true;

 void CloseOverlayMenu(ContextMenu menu,Action close,string label="Close overlay",bool separator=true){lastRightClick=0;if(separator)menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});var item=new MenuItem{Header=label};item.Click+=(_,_)=>{close();Config.Save();View.InvalidateVisual();};menu.Items.Add(item);}
 void OverlaysMenu(){var menu=new ContextMenu();PopulateOverlays(menu);menu.IsOpen=true;}
}
