using System;using System.IO;using System.Threading;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace gazegallery;
public partial class MainWindow {
 Border peek34=new(){IsHitTestVisible=false,Visibility=Visibility.Collapsed,Background=Brushes.Transparent,CornerRadius=new(8),Padding=new(12),Margin=new(0),HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};Image peekImage34=new(){Stretch=Stretch.Uniform};string? peekPath34,peekCandidate34;DateTime peekSince34;int peekEpoch34;Video? peekVideo34;AnimatedImage? peekAnimation34;WriteableBitmap? peekFrame34;TextBlock peekLoading35=new(){Text="",Foreground=Ui.Muted,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};readonly SemaphoreSlim peekTransition34=new(1,1);
 void SetupPeek34(){var content=new Grid();content.Children.Add(peekImage34);content.Children.Add(peekSkeleton37);peek34.Child=content;root.Children.Add(peekDim36);Panel.SetZIndex(peekDim36,190);root.Children.Add(peek34);Panel.SetZIndex(peek34,191);}
 void ClosePeek34(){peekDim36.Visibility=Visibility.Collapsed;peek34.Visibility=Visibility.Collapsed;peekLoading35.Visibility=Visibility.Collapsed;peekSkeleton37.Visibility=Visibility.Collapsed;if(peekPath34==null&&peekCandidate34==null&&peekVideo34==null&&peekAnimation34==null)return;peekEpoch34++;peekPath34=peekCandidate34=null;peek34.Visibility=Visibility.Collapsed;peekImage34.Source=null;peekFrame34=null;var v=peekVideo34;var a=peekAnimation34;peekVideo34=null;peekAnimation34=null;if(v!=null||a!=null)_=DisposePeek34(v,a);}
 async Task DisposePeek34(Video? movie,AnimatedImage? animation){await peekTransition34.WaitAsync();try{await Task.Run(()=>{movie?.Dispose();animation?.Dispose();});}catch(Exception ex){Paths.Log("peek-dispose-error",ex.Message);}finally{peekTransition34.Release();}}
 void ShowPeekSkeleton35(string path){peekDim36.Visibility=Visibility.Visible;peekImage34.Source=null;peekLoading35.Visibility=Visibility.Collapsed;peekSkeleton37.Visibility=Visibility.Visible;SizePeekSkeleton37(path);peek34.Visibility=Visibility.Visible;peek34.Width=peek34.MaxWidth=Math.Max(40,root.ActualWidth*.95);peek34.Height=peek34.MaxHeight=Math.Max(40,root.ActualHeight*.95);peekImage34.MaxWidth=peek34.MaxWidth-24;peekImage34.MaxHeight=peek34.MaxHeight-24;}
 void TickPeek34(){if(Mode!="grid"||focusSuspended34||!IsActive||!altPeekHeld35||Keyboard.FocusedElement is TextBox||Operations.Busy){ClosePeek34();return;}int i=View.HitTile(Mouse.GetPosition(View));string? path=i>=FolderTileCount&&i<GridPaths.Count&&!GridHoles.Contains(GridPaths[i])?GridPaths[i]:null;if(path==null){ClosePeek34();return;}if(path!=peekCandidate34){ClosePeek34();peekCandidate34=path;peekSince34=DateTime.UtcNow;ShowPeekSkeleton35(path);return;}if(peekPath34==null&&(DateTime.UtcNow-peekSince34).TotalMilliseconds>=30){peekPath34=path;int epoch=++peekEpoch34;_=LoadPeek34(path,epoch);}peek34.Width=peek34.MaxWidth=Math.Max(40,root.ActualWidth*.95);peek34.Height=peek34.MaxHeight=Math.Max(40,root.ActualHeight*.95);peekImage34.MaxWidth=peek34.MaxWidth-24;peekImage34.MaxHeight=peek34.MaxHeight-24;if(peekVideo34!=null&&peekVideo34.Update(ref peekFrame34)){peekLoading35.Visibility=Visibility.Collapsed;peekSkeleton37.Visibility=Visibility.Collapsed;peekImage34.Source=peekFrame34;peek34.Visibility=Visibility.Visible;}var animation=peekAnimation34;if(animation?.Due==true){animation.Busy=true;_=AdvancePeek34(animation,peekEpoch34);}}
 async Task LoadPeek34(string path,int epoch){await peekTransition34.WaitAsync();Video? movie=null;AnimatedImage? animation=null;try{if(epoch!=peekEpoch34)return;if(Path.GetExtension(path).Equals(".gif",StringComparison.OrdinalIgnoreCase)||WebImages.Animated(path)){animation=await Task.Run(()=>new AnimatedImage(path));if(epoch!=peekEpoch34){await Task.Run(animation.Dispose);return;}peekAnimation34=animation;animation=null;}else if(Paths.Motion(path)){movie=await Task.Run(()=>{var v=new Video(true,1280);try{v.Play(path,true,0,true);return v;}catch{v.Dispose();throw;}});if(epoch!=peekEpoch34){await Task.Run(movie.Dispose);return;}peekVideo34=movie;movie=null;}else{var image=await Cache.Get(path,2048,()=>epoch==peekEpoch34);if(epoch!=peekEpoch34)return;peekLoading35.Visibility=Visibility.Collapsed;peekSkeleton37.Visibility=Visibility.Collapsed;peekImage34.Source=image;peek34.Visibility=Visibility.Visible;}}catch(Exception ex){if(epoch==peekEpoch34){ClosePeek34();Paths.Log("peek-error",ex.Message);}}finally{peekTransition34.Release();}}
 async Task AdvancePeek34(AnimatedImage animation,int epoch){try{var image=await animation.Advance();if(epoch!=peekEpoch34||animation!=peekAnimation34)return;peekLoading35.Visibility=Visibility.Collapsed;peekSkeleton37.Visibility=Visibility.Collapsed;peekImage34.Source=image;peek34.Visibility=Visibility.Visible;}catch(Exception ex){if(epoch==peekEpoch34){ClosePeek34();Paths.Log("peek-animation-error",ex.Message);}}finally{animation.Busy=false;}}
}

