using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.Loader;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Microsoft.Win32;
using gazegallery.PluginApi;
namespace gazegallery;
public static class PluginCatalog {
 public static readonly List<(string Id,IImageDecoder Decoder)> Decoders=new();public static Func<string,bool> Enabled=_=>true;
 public static bool Supports(string path)=>Decoders.Any(d=>Enabled(d.Id)&&d.Decoder.Extensions.Contains(Path.GetExtension(path),StringComparer.OrdinalIgnoreCase));
 public static BitmapSource? Decode(string path,int max){var d=Decoders.FirstOrDefault(d=>Enabled(d.Id)&&d.Decoder.Extensions.Contains(Path.GetExtension(path),StringComparer.OrdinalIgnoreCase));if(d.Decoder==null)return null;var image=d.Decoder.Decode(path,max);if(!image.IsFrozen)image.Freeze();return image;}
}
public partial class MainWindow:IPluginHost {
 readonly List<IGazegalleryPlugin> plugins=new();readonly List<(string Id,string Title,Action Run,string Shortcut,string Help)> pluginCommands=new();string registeringPlugin="";UIElement? pluginOverlay;Border? pluginTools;Action? pluginCancel;Action? pluginUndo;void IPluginHost.SetOverlayUndo(Action undo)=>pluginUndo=undo;
 void SetupPlugins(){PluginCatalog.Enabled=id=>!Config.DisabledPlugins.Contains(id);PluginCatalog.Decoders.Clear();string folder=Path.Combine(Paths.Root,"plugins");Directory.CreateDirectory(folder);foreach(var file in Directory.GetFiles(folder,"*.dll")){try{var assembly=AssemblyLoadContext.Default.LoadFromAssemblyPath(file);foreach(var type in assembly.GetTypes().Where(t=>!t.IsAbstract&&typeof(IGazegalleryPlugin).IsAssignableFrom(t))){var plugin=(IGazegalleryPlugin)Activator.CreateInstance(type)!;if(plugin.ApiVersion!=1)throw new IOException("Unsupported plugin API version");registeringPlugin=plugin.Id;plugin.Initialize(this);plugins.Add(plugin);}}catch(Exception ex){Paths.Log("plugin-load-error",new{file,error=ex.Message});}}registeringPlugin="";}
 string? IPluginHost.CurrentFile=>current;BitmapSource? IPluginHost.CurrentImage=>Mode=="viewer"&&largeRaster==null&&current!=null&&!Paths.Motion(current)?sourceImage:null;double IPluginHost.ImageScale=>View.Scale;
 void IPluginHost.RegisterCommand(string title,Action execute,string shortcut,string help){pluginCommands.Add((registeringPlugin,title,execute,shortcut,help));string action="Plugin: "+registeringPlugin+" / "+title;if(shortcut.Length>0&&!Config.Keys.ContainsKey(action))Config.Keys[action]=new[]{shortcut};}void IPluginHost.RegisterDecoder(IImageDecoder decoder)=>PluginCatalog.Decoders.Add((registeringPlugin,decoder));
 Point IPluginHost.ImagePoint(Point p)=>View.ImagePoint(p);Point IPluginHost.ViewerPoint(Point p)=>new(View.Pan.X+p.X*View.Scale,View.Pan.Y+p.Y*View.Scale);
 void IPluginHost.Toast(string text)=>Toast(text);
 void IPluginHost.BeginOverlay(UIElement overlay,Panel controls,Action cancelled){EndPluginOverlay();pluginOverlay=overlay;pluginCancel=cancelled;if(overlay is FrameworkElement element)element.Margin=View.Margin;root.Children.Add(overlay);pluginTools=new Border{Child=controls,Background=Ui.Bg,CornerRadius=new CornerRadius(6),Padding=new Thickness(8),Margin=new Thickness(15),HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Bottom};root.Children.Add(pluginTools);}
 void IPluginHost.EndOverlay()=>EndPluginOverlay();void EndPluginOverlay(){if(pluginOverlay!=null)root.Children.Remove(pluginOverlay);if(pluginTools!=null)root.Children.Remove(pluginTools);pluginOverlay=null;pluginTools=null;pluginUndo=null;var cancel=pluginCancel;pluginCancel=null;cancel?.Invoke();}
 async Task<bool> IPluginHost.SaveCopyAsync(BitmapSource image){try{var dialog=new SaveFileDialog{InitialDirectory=Folder,FileName=Path.GetFileNameWithoutExtension(current??"Image")+"_drawn.png",Filter="PNG image|*.png|JPEG image|*.jpg"};if(dialog.ShowDialog(this)!=true)return false;if(string.Equals(dialog.FileName,current,StringComparison.OrdinalIgnoreCase))throw new IOException("Choose a different filename; drawing only saves copies.");await Task.Run(()=>{BitmapEncoder encoder=Path.GetExtension(dialog.FileName).Equals(".jpg",StringComparison.OrdinalIgnoreCase)?new JpegBitmapEncoder{QualityLevel=95}:new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using var f=File.Create(dialog.FileName);encoder.Save(f);});Toast("Saved drawing copy");return true;}catch(Exception ex){Error(ex);return false;}}
 UIElement PluginSettings(){var panel=new StackPanel{Margin=new Thickness(15)};panel.Children.Add(Ui.Label("Local plugins",18));panel.Children.Add(Ui.Label("Plugins are local .NET extensions and run with gazegallery's file access. Install plugins you trust.",12));foreach(var plugin in plugins){Ui.Check(panel,plugin.Name,!Config.DisabledPlugins.Contains(plugin.Id),enabled=>{if(enabled)Config.DisabledPlugins.Remove(plugin.Id);else if(!Config.DisabledPlugins.Contains(plugin.Id))Config.DisabledPlugins.Add(plugin.Id);Config.Save();});panel.Children.Add(Ui.Label(plugin.Description,11));}panel.Children.Add(Ui.Button("Open plugin folder",()=>System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("explorer.exe",Path.Combine(Paths.Root,"plugins")){UseShellExecute=true})));panel.Children.Add(Ui.Button("Open developer guide (.md)",()=>System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("notepad.exe","\""+Path.Combine(Paths.Root,"plugins","PluginGuide.md")+"\""){UseShellExecute=true})));panel.Children.Add(Ui.Label("New DLLs load at startup. Enable/disable takes effect immediately for commands and decoders.",11));return new ScrollViewer{Content=panel};}
 bool TryPluginKey(string key){var command=pluginCommands.FirstOrDefault(c=>!Config.DisabledPlugins.Contains(c.Id)&&Config.Keys.TryGetValue("Plugin: "+c.Id+" / "+c.Title,out var keys)&&keys.Contains(key,StringComparer.OrdinalIgnoreCase));if(command.Run==null||((IPluginHost)this).CurrentImage==null)return false;try{command.Run();}catch(Exception ex){EndPluginOverlay();Error(ex);}return true;}
 void AddPluginCommands(ContextMenu menu){var rootItem=new MenuItem{Header="Plugins"};foreach(var command in pluginCommands.Where(c=>!Config.DisabledPlugins.Contains(c.Id))){var plugin=plugins.First(p=>p.Id==command.Id);var header=new StackPanel{MaxWidth=280};header.Children.Add(Ui.Label(command.Title,12));var help=Ui.Label(command.Help.Length>0?command.Help:plugin.Description,10);help.Foreground=Ui.Muted;header.Children.Add(help);var item=new MenuItem{Header=header,InputGestureText=command.Shortcut,IsEnabled=((IPluginHost)this).CurrentImage!=null};item.Click+=(_,_)=>{try{command.Run();}catch(Exception ex){EndPluginOverlay();Error(ex);}};rootItem.Items.Add(item);}if(rootItem.Items.Count==0)rootItem.Items.Add(new MenuItem{Header="No enabled plugins",IsEnabled=false});int index=menu.Items.OfType<MenuItem>().Select((item,i)=>(item,i)).FirstOrDefault(x=>Equals(x.item.Header,"Settings")).i;index=0;for(int i=0;i<menu.Items.Count;i++)if(menu.Items[i] is MenuItem item&&Equals(item.Header,"Settings")){index=i;break;}if(index>0&&menu.Items[index-1] is not Separator)menu.Items.Insert(index++,new Separator{Style=(Style)FindResource(typeof(Separator))});menu.Items.Insert(index,rootItem);}
}
