using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;
namespace gazegallery;
public partial class MainWindow {
 void RefreshQuickPanel(){if(!Quick)return;Quick=false;ToggleQuick();}
 void ToggleBoardSelection(){if(View.BoardSelection.SetEquals(View.Board))View.BoardSelection.Clear();else View.BoardSelection=View.Board.ToHashSet();View.InvalidateVisual();}
 public void SelectGridTile(int index,bool control=false,bool shift=false){
  if(index<0||index>=GridPaths.Count||GridHoles.Contains(GridPaths[index])||index==0&&IsFolderTile(index))return;
  bool folder=IsFolderTile(index);bool same=View.Selected.All(i=>IsFolderTile(i)==folder);if(!same){View.Selected.Clear();View.Anchor=index;}
  if(shift&&same){int anchor=View.Anchor;if(anchor<0||anchor>=GridPaths.Count||IsFolderTile(anchor)!=folder)anchor=index;View.Selected.Clear();for(int i=Math.Min(index,anchor);i<=Math.Max(index,anchor);i++)if(IsFolderTile(i)==folder&&!(i==0&&folder)&&!GridHoles.Contains(GridPaths[i]))View.Selected.Add(i);}
  else if(control){if(!View.Selected.Add(index))View.Selected.Remove(index);View.Anchor=index;}
  else {View.Selected.Clear();View.Selected.Add(index);View.Anchor=index;}
  View.InvalidateVisual();
 }
 string[] SelectedGridFolders()=>View.Selected.Where(i=>i>0&&i<FolderTileCount&&i<GridPaths.Count).Order().Select(i=>GridPaths[i]).Where(Directory.Exists).ToArray();
 public static long CountFolderFiles(string folder){long count=0;var pending=new Stack<string>();pending.Push(folder);while(pending.Count>0){var path=pending.Pop();foreach(var entry in Directory.EnumerateFileSystemEntries(path)){var attr=File.GetAttributes(entry);if((attr&FileAttributes.Directory)==0)count++;else if((attr&FileAttributes.ReparsePoint)==0)pending.Push(entry);}}return count;}
 bool ConfirmRecycle(string message,string action,bool space){var w=Ui.Dialog(this,"Move to Recycle Bin",510,190);var p=new StackPanel{Margin=new Thickness(16)};var label=Ui.Label(message,13);label.TextWrapping=TextWrapping.Wrap;p.Children.Add(label);var row=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right};row.Children.Add(Ui.Button(action,()=>w.DialogResult=true));row.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(row);w.Content=p;if(space)w.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Space){e.Handled=true;w.DialogResult=true;}};return w.ShowDialog()==true;}
 async Task TrashFolders(){if(Operations.Busy)return;var selected=SelectedGridFolders();if(selected.Length==0)return;Operations.Busy=true;var entry=new UndoEntry{Navigation=navigation,Viewed=current};try{Toast("Counting files…",1);long count=await Task.Run(()=>selected.Sum(CountFolderFiles));string message=selected.Length==1?$"You are trying to delete a folder that contains {count} files":$"You are trying to delete {selected.Length} folders with {count} files";if(!ConfirmRecycle(message,"Delete",false))return;foreach(var path in selected)entry.Changes.Add(await Operations.TrashFolder(path));}catch(Exception ex){Error(ex);}finally{Operations.Commit(entry);Operations.Busy=false;if(entry.Changes.Count>0){View.Selected.Clear();await Scan();View.LayoutTiles();Toast($"{entry.Changes.Count} folder(s) sent to recycle bin — Ctrl+Z to undo");}}}
 void CreateSubfolder(){if(!hasFolder)return;var w=Ui.Dialog(this,"Create new folder",420,210);var p=new StackPanel{Margin=new Thickness(16)};p.Children.Add(Ui.Label("Folder name",12));var input=Ui.Input("");p.Children.Add(input);var error=Ui.Label("",11);p.Children.Add(error);void Create(){var name=input.Text.Trim();if(string.IsNullOrWhiteSpace(name)||name is "." or ".."||name.IndexOfAny(Path.GetInvalidFileNameChars())>=0||name.EndsWith('.')||name.EndsWith(' ')){error.Text="Enter a valid folder name.";return;}var target=Path.Combine(Folder,name);try{if(Directory.Exists(target)||File.Exists(target)){error.Text="That name already exists.";return;}Directory.CreateDirectory(target);RebuildGridPaths();View.LayoutTiles();w.Close();Toast("Created folder — "+name);}catch(Exception ex){error.Text=ex.Message;}}var row=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right};row.Children.Add(Ui.Button("Create",Create));row.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(row);w.Content=p;input.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Enter){e.Handled=true;Create();}};w.Loaded+=(_,_)=>input.Focus();w.ShowDialog();}
 async Task ApplySortOrder(string sort){string? keep=current;Config.Sort=sort;shuffled=false;ClearGridHoles();Config.Save();await Scan();if(keep!=null&&Files.Contains(keep))Index=Files.IndexOf(keep);if(Mode=="grid"){await PrepareGrid();View.Scroll=0;}UpdateTitle();View.InvalidateVisual();}
 void AddSortChoices(ItemsControl menu){var sorts=new[]{"Newest","Oldest","Name A–Z","Name Z–A","Smallest","Largest"};for(int i=0;i<sorts.Length;i++){if(i>0&&i%2==0)menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});string value=sorts[i];var item=new MenuItem{Header=value,InputGestureText=Config.Sort==value?"✓":""};item.Click+=(_,_)=>Run(()=>ApplySortOrder(value));menu.Items.Add(item);}}
 void PopulateOverlays(ItemsControl menu){void Add(string title,Func<bool> read,Action<bool> write){if(Config.HiddenOverlays.Contains(title))return;var item=new MenuItem{Header=title,Tag="overlay-option",StaysOpenOnClick=true,IsCheckable=true,IsChecked=read(),InputGestureText=read()?"✓":""};item.Click+=(_,e)=>{write(item.IsChecked);item.InputGestureText=item.IsChecked?"✓":"";Config.Save();View.InvalidateVisual();e.Handled=true;};item.AddHandler(Mouse.PreviewMouseUpEvent,new MouseButtonEventHandler((_,e)=>{if(e.ChangedButton!=MouseButton.Right)return;OpenOverlayOptions33(title);e.Handled=true;}),true);menu.Items.Add(item);}Add("Zoom",()=>Config.ZoomIndicator,v=>Config.ZoomIndicator=v);Add("Image Position",()=>Config.PositionIndicator,v=>Config.PositionIndicator=v);Add("Slideshow",()=>Config.SlideshowTimer,v=>{Config.SlideshowTimer=v;if(v)Config.TimerAutoHide=false;else EndSlideshow();});Add("Diagnostics",()=>diagnostic,v=>{diagnostic=v;graph.Visibility=v?Visibility.Visible:Visibility.Collapsed;});Add("Navigation Arrows",()=>Config.Arrows,v=>Config.Arrows=v);Add("Filmstrip",()=>Config.Filmstrip,v=>{Config.Filmstrip=v;ResetFilmstrip();UpdateFilmstripLayout33();});Add("Metadata",()=>Config.MetadataOverlay,v=>{Config.MetadataOverlay=v;metadataPath=null;});Add("Histogram",()=>Config.Histogram,v=>{Config.Histogram=v;histogramImage=null;});menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});menu.Items.Add(new MenuItem{Header="Right click overlays to show their options",IsEnabled=false});}

}

