using System;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shell;
namespace gazegallery;
public partial class MainWindow {
 DateTime lastPreload;double priorScroll;public void PreloadThumbs(){if(Mode!="grid"||(DateTime.UtcNow-lastPreload).TotalMilliseconds<120)return;lastPreload=DateTime.UtcNow;bool down=View.Scroll>=priorScroll;priorScroll=View.Scroll;var candidates=Enumerable.Range(0,Math.Min(GridPaths.Count,View.Tiles.Count)).Where(i=>View.GridEnd35(View.Tiles[i])>=View.Scroll-View.GridViewport35*(down?1:3)&&View.GridStart35(View.Tiles[i])<=View.Scroll+View.GridViewport35*(down?4:2)).OrderBy(i=>Math.Abs(View.GridStart35(View.Tiles[i])-View.Scroll-View.GridViewport35/2));foreach(int i in candidates)if(!IsFolderTile(i)&&!GridHoles.Contains(GridPaths[i])&&!View.Thumbs.ContainsKey(GridPaths[i]))RequestThumb(GridPaths[i]);}
 DateTime lastPrune; void PruneThumbs(){if((DateTime.UtcNow-lastPrune).TotalMilliseconds<500)return;lastPrune=DateTime.UtcNow;long bytes=View.Thumbs.Values.Sum(b=>(long)b.PixelWidth*b.PixelHeight*4);if(bytes<=288*1048576L)return;var indices=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);for(int n=0;n<GridPaths.Count;n++)indices[GridPaths[n]]=n;foreach(var p in View.Thumbs.Keys.OrderByDescending(p=>indices.TryGetValue(p,out int i)&&i<View.Tiles.Count?Math.Abs(View.GridStart35(View.Tiles[i])-View.Scroll):double.MaxValue).ToArray()){if(bytes<=224*1048576L)break;if(indices.TryGetValue(p,out int i)&&i<View.Tiles.Count&&View.GridEnd35(View.Tiles[i])>=View.Scroll-View.GridViewport35*2&&View.GridStart35(View.Tiles[i])<=View.Scroll+View.GridViewport35*4)continue;var b=View.Thumbs[p];bytes-=(long)b.PixelWidth*b.PixelHeight*4;View.Thumbs.Remove(p);}}

 AnimatedImage? animation;Border toolbarHost=new();CheckBox fadeToggle=new();bool chromeInitialized;Dictionary<BoardItem,Rect> groupStart=new();
 void SetupRevision(){FocusVisualStyle=null;View.FocusVisualStyle=null;if(!Config.CompactMenuMigrated){foreach(var a in new[]{"Rename","Flip horizontal","Flip vertical","Rotate 90°","Open folder","Paste","Filtering"})if(!Config.HiddenActions.Contains(a))Config.HiddenActions.Add(a);Config.CompactMenuMigrated=true;Config.Save();}
  root.Children.Remove(toolbar);var row=new Grid();row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(90)});row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(105)});Grid.SetColumn(toolbar,1);toolbar.Height=double.NaN;toolbar.MinHeight=38;toolbar.HorizontalAlignment=HorizontalAlignment.Center;toolbar.Margin=new Thickness(0);toolbar.Background=Brushes.Transparent;row.Children.Add(toolbar);fadeToggle.Content="Fade Away";fadeToggle.Foreground=Ui.Fg;fadeToggle.VerticalAlignment=VerticalAlignment.Center;fadeToggle.HorizontalAlignment=HorizontalAlignment.Right;fadeToggle.Margin=new Thickness(8);fadeToggle.IsChecked=Config.FadeToolbar;Grid.SetColumn(fadeToggle,2);var rightTools=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};rightTools.Children.Add(fadeToggle);boardReturn=Ui.Button("Return",()=>Run(ReturnFromCollage));Grid.SetColumn(boardReturn,0);row.Children.Add(boardReturn);Grid.SetColumn(rightTools,2);row.Children.Add(rightTools);toolbarHost.Child=row;toolbarHost.Background=new SolidColorBrush(Color.FromRgb(30,32,35));toolbarHost.Height=double.NaN;toolbarHost.MinHeight=38;toolbarHost.VerticalAlignment=VerticalAlignment.Top;toolbarHost.Visibility=Visibility.Collapsed;root.Children.Add(toolbarHost);
  chromeInitialized=true;SetupLatest();
 }
 void RefreshChrome(){if(!chromeInitialized)return;toolbarHost.Visibility=Mode=="viewer"?Visibility.Collapsed:Visibility.Visible;fadeToggle.Visibility=Mode is "grid" or "board"?Visibility.Visible:Visibility.Collapsed;toolbarHost.Margin=new Thickness(0);AnimateChrome();}

 async void AdvanceAnimation(){var a=animation;if(a==null||!a.Due||Mode!="viewer")return;a.Busy=true;try{var frame=await a.Advance();if(a!=animation||frame==null)return;bool first=View.Image==null||animationPath35!=presentedPath35;if(first)View.ZoomUsed=false;View.Image=frame;MarkPresented35(animationPath35);if(first){View.Fit();UpdateTitle();}View.InvalidateVisual();}catch(Exception ex){if(a==animation){animation=null;Error(ex);a.Dispose();}}finally{a.Busy=false;}}
 void RememberFolder(string path){Config.RecentFolders.RemoveAll(p=>string.Equals(p,path,StringComparison.OrdinalIgnoreCase));Config.RecentFolders.Insert(0,path);Config.RecentFolders=Config.RecentFolders.Take(3).ToList();Config.Save();}
 async Task NavigateFolder(string dir){string prior=Folder;dir=Path.GetFullPath(dir);if(hasFolder&&string.Equals(dir.TrimEnd('\\'),Folder.TrimEnd('\\'),StringComparison.OrdinalIgnoreCase))return;if(!Directory.Exists(dir))return;if(!LeaveBoard())return;
 ResetFilter34();int token=++modeTransition;navigatingTree=true;PauseScroll();EndPluginOverlay();if(Cropping)CancelCrop();generation++;thumbGeneration++;hasFolder=true;Folder=dir;Files.Clear();current=viewerReturn=null;Index=0;Mode="grid";GridLoading=true;GridMetadataLoading=true;GridRatios.Clear();View.Image=null;sourceImage=null;ClearLarge();View.Tiles.Clear();View.Thumbs.Clear();View.Selected.Clear();View.Scroll=0;thumbFailed.Clear();Quick=false;quickPanel.Visibility=Visibility.Collapsed;BuildModeToolbar();Toast(dir,2);RememberFolder(dir);
 try{await StopVideo();if(token!=modeTransition)return;await Scan();if(token!=modeTransition)return;current=Files.FirstOrDefault();viewerReturn=current;Watch();await PrepareGrid();if(token!=modeTransition)return;GridLoading=false;View.LayoutTiles();UpdateTitle();HighlightFolder();RevealFolderArrival(prior);}finally{if(token==modeTransition){navigatingTree=false;GridLoading=false;View.InvalidateVisual();}}}
 void BuildFolders(){if(folderPanel.Visibility==Visibility.Visible){folderPanel.Visibility=Visibility.Collapsed;return;}var panel=new StackPanel{Margin=new Thickness(8)};panel.Children.Add(Ui.Label("Recent folders",12));foreach(var p in Config.RecentFolders.Where(Directory.Exists).ToArray()){var b=Ui.Button(FolderDisplayName(p),()=>Run(()=>NavigateFolder(p)));b.ToolTip=p;b.FontSize=11;b.Padding=new Thickness(4,2,4,2);b.Margin=new Thickness(1);b.HorizontalContentAlignment=HorizontalAlignment.Center;b.HorizontalAlignment=HorizontalAlignment.Stretch;panel.Children.Add(b);}panel.Children.Add(new Separator());panel.Children.Add(Ui.Label("Pinned folders",12));var pin=Ui.Button("+",()=>{if(hasFolder&&!Config.Pins.Contains(Folder))Config.Pins.Add(Folder);Config.Save();folderPanel.Visibility=Visibility.Collapsed;ShowFolders();});pin.HorizontalAlignment=HorizontalAlignment.Right;pin.Padding=new Thickness(4,2,4,2);pin.Margin=new Thickness(1);panel.Children.Add(pin);foreach(var p in Config.Pins.ToArray()){var line=new DockPanel();var remove=Ui.Button("−",()=>{Config.Pins.Remove(p);Config.Save();folderPanel.Visibility=Visibility.Collapsed;ShowFolders();});DockPanel.SetDock(remove,Dock.Right);line.Children.Add(remove);var b=Ui.Button(FolderDisplayName(p),()=>Run(()=>NavigateFolder(p)));b.ToolTip=p;b.Padding=new Thickness(4,2,4,2);b.Margin=new Thickness(1);remove.Padding=new Thickness(4,2,4,2);remove.Margin=new Thickness(1);AttachPinDrag(line,b,p);b.HorizontalAlignment=HorizontalAlignment.Stretch;line.Children.Add(b);panel.Children.Add(line);}panel.Children.Add(new Separator());panel.Children.Add(Ui.Label("Folder tree",12));var tree=new TreeView{Background=Ui.Bg,Foreground=Ui.Fg,BorderThickness=new Thickness(0)};
  tree.Loaded+=(_,_)=>{var layer=System.Windows.Documents.AdornerLayer.GetAdornerLayer(tree);if(layer!=null){var guide=new FolderGuides(tree,()=>Folder);layer.Add(guide);tree.LayoutUpdated+=(_,_)=>guide.InvalidateVisual();}};
  TreeViewItem Add(ItemsControl owner,string path){var node=new TreeViewItem{Header=Path.GetFileName(path.TrimEnd('\\')) is {Length:>0} name?name:path,Tag=path,Foreground=Ui.Fg};node.Items.Add("Loading…");void Populate(){if(node.Items.Count!=1||node.Items[0] is not string)return;node.Items.Clear();try{foreach(var sub in Directory.EnumerateDirectories(path))Add(node,sub);}catch{}if(node.Items.Count==0)node.Items.Add(new TreeViewItem{Header="",Height=0,Focusable=false,IsHitTestVisible=false});}node.Expanded+=(_,e)=>{Populate();e.Handled=true;};node.Selected+=(_,e)=>{e.Handled=true;};var header=new TextBlock{Text=node.Header.ToString(),Foreground=Ui.Fg,Padding=new Thickness(2,0,2,0),Background=Brushes.Transparent};header.MouseLeftButtonUp+=(_,e)=>{e.Handled=true;Run(()=>NavigateFolder(path));};if(string.Equals(path.TrimEnd('\\'),Folder.TrimEnd('\\'),StringComparison.OrdinalIgnoreCase)||Folder.StartsWith(path.TrimEnd('\\')+"\\",StringComparison.OrdinalIgnoreCase)){node.BorderBrush=new SolidColorBrush(Color.FromArgb(45,210,215,220));node.BorderThickness=new Thickness(0);}node.Header=header;node.PreviewMouseLeftButtonDown+=(_,e)=>{DependencyObject? source=e.OriginalSource as DependencyObject;while(source!=null&&source is not TreeViewItem)source=VisualTreeHelper.GetParent(source);if(source==node&&e.GetPosition(header).X<0){node.IsExpanded=!node.IsExpanded;e.Handled=true;}};header.HorizontalAlignment=HorizontalAlignment.Stretch;node.HorizontalContentAlignment=HorizontalAlignment.Stretch;owner.Items.Add(node);bool currentPath=string.Equals(path.TrimEnd('\\'),Folder.TrimEnd('\\'),StringComparison.OrdinalIgnoreCase);if(currentPath){Populate();node.IsExpanded=true;node.IsSelected=true;node.Loaded+=(_,_)=>node.BringIntoView();}else if(Folder.StartsWith(path.TrimEnd('\\')+"\\",StringComparison.OrdinalIgnoreCase)){Populate();node.IsExpanded=true;}return node;}
  foreach(var drive in Directory.GetLogicalDrives())Add(tree,drive);var dock=new DockPanel();DockPanel.SetDock(panel,Dock.Top);dock.Children.Add(panel);dock.Children.Add(tree);folderPanel.Child=dock;folderPanel.Visibility=Visibility.Visible;Panel.SetZIndex(folderPanel,20);RefreshTreeHeader();}

 void LaunchCompanion(){var start=new ProcessStartInfo(Path.Combine(AppContext.BaseDirectory,"gazegallery.exe")){UseShellExecute=true};var origin=collageOrigin??current;if(origin!=null&&File.Exists(origin))start.ArgumentList.Add(origin);Process.Start(start);}
 void ClearBoard(){if(View.Board.Count==0)return;View.Snapshot();View.Board.Clear();View.BoardSelection.Clear();View.BoardSelected=-1;View.InvalidateVisual();}
 void RemoveBoardSelection(){var removed=View.BoardSelection.Count>0?View.BoardSelection.ToHashSet():focusedBoard!=null&&View.Board.Contains(focusedBoard)?new HashSet<BoardItem>{focusedBoard}:new HashSet<BoardItem>();if(removed.Count==0)return;View.Snapshot();View.Board.RemoveAll(removed.Contains);if(View.Board.Count==0)focusedBoard=null;View.BoardSelection.Clear();View.BoardSelected=-1;View.InvalidateVisual();}
}





