using System;using System.Globalization;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;
namespace gazegallery;
public sealed class RotationRuler32:FrameworkElement {
 public static readonly DependencyProperty ValueProperty=DependencyProperty.Register(nameof(Value),typeof(double),typeof(RotationRuler32),new FrameworkPropertyMetadata(0d,FrameworkPropertyMetadataOptions.AffectsRender,(d,e)=>((RotationRuler32)d).ValueChanged?.Invoke(d,EventArgs.Empty),(_,v)=>Math.Clamp((double)v,-90,90)));
 public double Value{get=>(double)GetValue(ValueProperty);set=>SetValue(ValueProperty,value);}public event EventHandler? ValueChanged;Point down;double before;bool moving,moved;
 public RotationRuler32(){Height=48;MinWidth=160;Cursor=Cursors.SizeWE;Focusable=true;ToolTip="Drag the degree ruler · wheel for fine rotation";MouseLeftButtonDown+=(_,e)=>{down=e.GetPosition(this);before=Value;moving=true;moved=false;CaptureMouse();e.Handled=true;};MouseMove+=(_,e)=>{if(!moving)return;double dx=e.GetPosition(this).X-down.X;moved|=Math.Abs(dx)>2;Value=Math.Round((before-dx/4)*10)/10;e.Handled=true;};MouseLeftButtonUp+=(_,e)=>{if(moving&&!moved)Value=Math.Round((Value+(e.GetPosition(this).X-ActualWidth/2)/4)*10)/10;moving=false;ReleaseMouseCapture();e.Handled=true;};MouseWheel+=(_,e)=>{Value+=e.Delta/120d*(Keyboard.Modifiers.HasFlag(ModifierKeys.Control)?.1:1);e.Handled=true;};}
 protected override void OnRender(DrawingContext dc){dc.DrawRoundedRectangle(Ui.Bg,null,new Rect(RenderSize),5,5);dc.PushClip(new RectangleGeometry(new Rect(RenderSize)));for(int angle=-90;angle<=90;angle++){double x=ActualWidth/2+(angle-Value)*4;if(x<0||x>ActualWidth)continue;bool major=angle%15==0;dc.DrawLine(new Pen(Ui.Muted,1),new Point(x,35),new Point(x,major?27:31));if(major){var text=new FormattedText(angle+"°",CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Segoe UI"),11,Ui.Fg,VisualTreeHelper.GetDpi(this).PixelsPerDip);dc.DrawText(text,new Point(x-text.Width/2,5));}}dc.DrawLine(new Pen(Ui.Fg,2),new Point(ActualWidth/2,38),new Point(ActualWidth/2,46));dc.Pop();}
}
public partial class MainWindow {
 readonly System.Collections.Generic.Dictionary<int,Slider> editSliders32=new();RotationRuler32? rotationRuler;TextBox? rotationNumber;double rotationBase;bool rotationSync;bool motionLineMode,motionLineDragging;Point motionStart,motionEnd;
 void AddRotation32(Panel panel){var row=new WrapPanel{VerticalAlignment=VerticalAlignment.Center};rotationRuler=new RotationRuler32{Width=260,Margin=new Thickness(4)};rotationNumber=Ui.Input("0");rotationNumber.Width=55;rotationNumber.VerticalContentAlignment=VerticalAlignment.Center;rotationNumber.Margin=new Thickness(4);rotationRuler.ValueChanged+=(_,_)=>{if(rotationSync)return;editAngle=rotationBase+rotationRuler.Value;EnsureRotationCrop32();rotationSync=true;rotationNumber.Text=editAngle.ToString("0.#",CultureInfo.InvariantCulture);rotationSync=false;View.InvalidateVisual();};rotationNumber.TextChanged+=(_,_)=>{if(!rotationSync&&double.TryParse(rotationNumber.Text,NumberStyles.Float,CultureInfo.InvariantCulture,out var value))SetEditAngle32(value);};row.Children.Add(rotationRuler);row.Children.Add(rotationNumber);row.Children.Add(Ui.Label("°",11));row.Children.Add(Ui.Button("↺",()=>SetEditAngle32(0)));row.Children.Add(Ui.Button("90° clockwise",()=>SetEditAngle32(editAngle+90)));panel.Children.Insert(1,row);}
 void SetEditAngle32(double value){editAngle=(value%360+540)%360-180;rotationBase=Math.Round(editAngle/90)*90;EnsureRotationCrop32();rotationSync=true;if(rotationRuler!=null)rotationRuler.Value=editAngle-rotationBase;if(rotationNumber!=null&&!rotationNumber.IsKeyboardFocused)rotationNumber.Text=editAngle.ToString("0.#",CultureInfo.InvariantCulture);rotationSync=false;View.InvalidateVisual();}
 void EnsureRotationCrop32(){if(Cropping&&View.Image!=null&&View.CropRect.IsEmpty)View.CropRect=new Rect(0,0,View.Image.PixelWidth,View.Image.PixelHeight);}
 public void DrawEditImage32(DrawingContext dc,bool dim){if(View.Image==null)return;var r=View.ImageRect;dc.PushTransform(new RotateTransform(editAngle,r.X+r.Width/2,r.Y+r.Height/2));if(dim&&!AdjustmentsOpen)dc.PushOpacity(.6);dc.DrawImage(View.Image,r);if(dim&&!AdjustmentsOpen)dc.Pop();dc.Pop();}
 public void DrawMotionPreview32(DrawingContext dc){if(!motionLineDragging)return;var a=View.Pan+(Vector)motionStart*View.Scale;var b=View.Pan+(Vector)motionEnd*View.Scale;dc.DrawLine(new Pen(Ui.Fg,2),(Point)a,(Point)b);}
 public void DrawRotationGrid32(DrawingContext dc,Rect crop){var pen=new Pen(new SolidColorBrush(Color.FromArgb(90,220,220,220)),1);for(int i=1;i<6;i++){double x=crop.Left+crop.Width*i/6;dc.DrawLine(pen,new Point(x,crop.Top),new Point(x,crop.Bottom));}for(int i=1;i<9;i++){double y=crop.Top+crop.Height*i/9;dc.DrawLine(pen,new Point(crop.Left,y),new Point(crop.Right,y));}}
 bool MotionDown32(Point point){if(!Cropping||!motionLineMode)return false;EnsureRotationCrop32();motionStart=motionEnd=View.ImagePoint(point);motionLineDragging=true;View.CaptureMouse();View.InvalidateVisual();return true;}
 bool MotionMove32(Point point){if(!motionLineDragging)return false;motionEnd=View.ImagePoint(point);View.InvalidateVisual();return true;}
 bool MotionUp32(){if(!motionLineDragging)return false;motionLineDragging=false;motionLineMode=false;View.ReleaseMouseCapture();var line=motionEnd-motionStart;var full=cropOriginal??sourceImage;if(View.Image!=null&&full!=null&&line.Length>1){editValues[19]=2;editValues[28]=Math.Atan2(line.Y,line.X)*180/Math.PI-editAngle;editValues[29]=line.Length*full.PixelWidth/View.Image.PixelWidth;editValues[18]=25;if(editSliders32.TryGetValue(18,out var slider))slider.Value=25;QueueEditPreview();}View.InvalidateVisual();return true;}
}
