using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using Microsoft.Win32;
namespace gazegallery;
public partial class MainWindow {
 bool bufferingVideo;string collageReturnMode="viewer";string? collageOrigin;bool rowReverse,columnReverse;StackPanel startupPage=new();
 System.Windows.Controls.Image startupLogo=new();System.Windows.Controls.TextBlock emptyFolderLine=new(),emptyFolderPath=new();
 void SetupRound24(){startupPage.VerticalAlignment=VerticalAlignment.Center;startupPage.HorizontalAlignment=HorizontalAlignment.Center;startupPage.MaxWidth=650;foreach(var text in new[]{"- Quick Start - ","Drag an image onto the top half of the program to quickly load and view it","Press "+string.Join(" / ",Config.Keys["Folder tree"].Select(FriendlyKey))+" to open Folder Tree and choose a folder to view","Right click for a context menu with more options"}){var line=Ui.Label(text,12);line.TextAlignment=TextAlignment.Center;startupPage.Children.Add(line);}startupLogo.Source=Branding.Icon();startupLogo.Width=startupLogo.Height=72;startupLogo.Margin=new Thickness(0,14,0,14);startupPage.Children.Add(startupLogo);var openButton=Ui.Button("Open File",()=>Run(()=>Action("Open file")));openButton.HorizontalAlignment=HorizontalAlignment.Center;startupPage.Children.Add(openButton);var links=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Center};links.Children.Add(Ui.Button("Folder Tree",ShowFolders));links.Children.Add(Ui.Button("Thumbnail mode",()=>Run(()=>SetMode("grid"))));startupPage.Children.Add(links);emptyFolderLine.TextAlignment=emptyFolderPath.TextAlignment=TextAlignment.Center;emptyFolderLine.Foreground=emptyFolderPath.Foreground=Ui.Fg;emptyFolderLine.Inlines.Add("Currently viewing the ");emptyFolderLine.Inlines.Add(new System.Windows.Documents.Run("(empty of images)"){Foreground=new SolidColorBrush(Colors.White){Opacity=.4}});emptyFolderLine.Inlines.Add(" folder");emptyFolderPath.MaxWidth=600;emptyFolderPath.TextWrapping=TextWrapping.Wrap;startupPage.Children.Add(emptyFolderLine);startupPage.Children.Add(emptyFolderPath);startupPage.MouseRightButtonUp+=(_,e)=>{HandleViewerRightClick(e.GetPosition(View));e.Handled=true;};root.Children.Add(startupPage);SetupTempGridMessage();RefreshRound24();}
 void RefreshRound24(){tempGridMessage.Visibility=Mode=="grid"&&Files.Count==0&&string.Equals(Folder,TempFolder,StringComparison.OrdinalIgnoreCase)?Visibility.Visible:Visibility.Collapsed;bool empty=Mode=="viewer"&&current==null;startupPage.Visibility=empty?Visibility.Visible:Visibility.Collapsed;bool compact=Config.HideQuickStart||root.ActualWidth<680||root.ActualHeight<420;foreach(UIElement child in startupPage.Children)child.Visibility=ReferenceEquals(child,startupLogo)||!compact?Visibility.Visible:Visibility.Collapsed;emptyFolderLine.Visibility=emptyFolderPath.Visibility=!compact&&hasFolder?Visibility.Visible:Visibility.Collapsed;emptyFolderPath.Text=hasFolder?Folder:"";if(!Config.AutoHideCursor)View.Cursor=Cursors.Arrow;if(Mode=="board")UpdateTitle();if(Config.SlideshowTimer)View.InvalidateVisual();}
 void AddRound24Settings(Panel p){Ui.Check(p,"Scroll wheel navigates images (CTRL + Scroll wheel to zoom)",Config.WheelNavigation,v=>Config.WheelNavigation=v);Ui.Check(p,"Hide quick start on Startup Page",Config.HideQuickStart,v=>Config.HideQuickStart=v);Ui.Check(p,"Confirm Escape to exit",Config.ConfirmEscape,v=>Config.ConfirmEscape=v);Ui.Check(p,"Auto hide cursor",Config.AutoHideCursor,v=>Config.AutoHideCursor=v);p.Children.Add(Ui.Label("Default fit",12));var fit=new ComboBox{ItemsSource=FitNames,SelectedItem=Config.DefaultFit,Margin=new Thickness(5)};fit.SelectionChanged+=(_,_)=>Config.DefaultFit=(string)fit.SelectedItem;p.Children.Add(fit);p.Children.Add(Ui.Button("Export settings…",ExportSettings));}
 void ExportSettings(){var d=new SaveFileDialog{Title="Export all gazegallery settings",Filter="gazegallery settings|*.json",FileName="gazegallery-settings.json"};if(d.ShowDialog(this)!=true)return;try{Config.Save();ExportWithBookmarks35(d.FileName);Toast("All settings exported");}catch(Exception ex){Error(ex);}}
 UIElement AboutPanel(){var p=new StackPanel{Margin=new Thickness(20)};p.Children.Add(Ui.Label("gazegallery",24));p.Children.Add(Ui.Label("Version "+typeof(MainWindow).Assembly.GetName().Version+"\nBuild: "+BuildInfo24.Timestamp,13));p.Children.Add(Ui.Label("A minimal image and video browser for viewing, sorting, and arranging your collection.",13));p.Children.Add(Ui.Label("Coder: Codex (OpenAI)\nQA#1 and Ideas Guy: pagemuncher",13));return p;}
 bool ConfirmEscapeExit(){var w=Ui.Dialog(this,"Exit gazegallery?",320,150);var p=new StackPanel{Margin=new Thickness(15)};p.Children.Add(Ui.Label("Exit gazegallery?",16));var row=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right};row.Children.Add(Ui.Button("Stay",()=>w.DialogResult=false));row.Children.Add(Ui.Button("Exit",()=>w.DialogResult=true));p.Children.Add(row);w.Content=p;w.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Space){e.Handled=true;w.DialogResult=true;}};return w.ShowDialog()==true;}
 void ToggleSelectAll(){var selectable=Enumerable.Range(FolderTileCount,GridPaths.Count-FolderTileCount).Where(i=>!GridHoles.Contains(GridPaths[i])).ToHashSet();if(View.Selected.SetEquals(selectable))View.Selected.Clear();else View.Selected=selectable;View.InvalidateVisual();}
 void ArrangeBoard(string action){var selected=View.BoardSelection.Where(View.Board.Contains).OrderBy(i=>i.ImportOrder).ToArray();if(selected.Length<2)return;View.Snapshot();if(action.StartsWith("Normalize")){bool width=action=="Normalize width";double largest=selected.Max(i=>width?i.Rect.Width:i.Rect.Height);foreach(var i in selected){var r=i.Rect;double factor=largest/(width?r.Width:r.Height);i.Rect=new Rect(r.X+r.Width*(1-factor)/2,r.Y+r.Height*(1-factor)/2,r.Width*factor,r.Height*factor);}}else{bool row=action=="Align in a row";bool reverse=row?rowReverse:columnReverse;if(reverse)Array.Reverse(selected);if(row)rowReverse=!rowReverse;else columnReverse=!columnReverse;var bounds=selected.Select(i=>i.Rect).Aggregate(Rect.Union);double length=selected.Sum(i=>row?i.Rect.Width:i.Rect.Height)+Config.CollageGap*(selected.Length-1);double cursor=(row?bounds.X+bounds.Width/2:bounds.Y+bounds.Height/2)-length/2;foreach(var i in selected){var r=i.Rect;i.Rect=row?new Rect(cursor,bounds.Y+(bounds.Height-r.Height)/2,r.Width,r.Height):new Rect(bounds.X+(bounds.Width-r.Width)/2,cursor,r.Width,r.Height);cursor+=(row?r.Width:r.Height)+Config.CollageGap;}}View.InvalidateVisual();}
 static readonly string[] FitNames={"Fit window","Fit width","Fit height","Comfy fit","Original size"};
 void FitMenu()=>FitMenu33().IsOpen=true;
 ContextMenu FitMenu33(){var menu=new ContextMenu();foreach(string name in FitNames){var item=new MenuItem{Header=name,IsCheckable=true,IsChecked=Config.DefaultFit==name,InputGestureText=Config.DefaultFit==name?"✓":""};item.Click+=(_,_)=>{Config.DefaultFit=name;Config.Save();View.FitStyle(name);};menu.Items.Add(item);}AddBackgroundChoices32(menu);AddWindowChoices36(menu);CloseOverlayMenu(menu,()=>Config.ZoomIndicator=false);NormalizeMenuSeparators(menu);return menu;}
 void ToBottom(){if(GridMetadataLoading){Toast("Cannot jump to bottom yet\nBuffering",2);return;}View.Scroll=Math.Max(0,View.GridBottom-View.GridViewport35);View.InvalidateVisual();}
 void SortMenu(){var menu=new ContextMenu();AddSortChoices(menu);menu.IsOpen=true;}
 void PositionMenu(){if(Files.Count==0)return;var w=Ui.Dialog(this,"Go to image",300,180);var p=new StackPanel{Margin=new Thickness(12)};p.Children.Add(Ui.Label("Image position (1–"+Files.Count+")",12));var input=Ui.Input((Index+1).ToString());p.Children.Add(input);var row=new WrapPanel();void Go(){if(int.TryParse(input.Text,out int n)&&n>=1&&n<=Files.Count){w.Close();Run(()=>ShowIndex(n-1));}}row.Children.Add(Ui.Button("Go",Go));row.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(row);input.PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Enter){e.Handled=true;Go();}};w.Content=p;w.Loaded+=(_,_)=>{input.Focus();input.SelectAll();};w.ShowDialog();}
}
