using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Collections.Generic;using System.Windows;using System.Diagnostics;
namespace gazegallery;
public partial class MainWindow {
 async Task VerifyRound22(List<object> report,Action<bool,string> check,string work){
 var launch=ExternalStartInfo(new ExternalProgram{Executable=@"C:\Program Files\qimgv\qimgv.exe"},Path.Combine(work,"file with spaces.jpg"));check(launch.UseShellExecute&&launch.WorkingDirectory==@"C:\Program Files\qimgv"&&launch.ArgumentList.Count==1,"External launch uses executable directory and intact file argument");
 string seed=Path.Combine(Paths.Test,"small_mario.png"),folder=Path.Combine(work,"round22");Directory.CreateDirectory(folder);string file=Path.Combine(folder,"image.png");File.Copy(seed,file);await Open(file);Toast("unchanged");int count=Operations.Count;await MoveSelection(folder);check(toast.Text=="unchanged"&&current==file&&Operations.Count==count,"Same-file no-op does not claim move success or change view");string dest=Path.Combine(folder,"copies");Directory.CreateDirectory(dest);quickCopy=true;await QuickTransfer(dest);check(toast.Text.Contains("was copied")&&!toast.Text.Contains("undo",StringComparison.OrdinalIgnoreCase),"Copy toast uses transfer layout without undo claim");quickCopy=false;
 await SetMode("grid");Config.SiblingNavigation=false;View.Scroll=0;ScrollGridBy(-120);check(View.Scroll==0&&boundaryDirection==-1,"First boundary scroll only arms navigation");boundaryArmed=DateTime.UtcNow.AddSeconds(-1);ScrollGridBy(-120);await Task.Delay(40);check(boundaryDirection==0,"Second delayed boundary scroll completes loop");
 string siblings=Path.Combine(work,"cycle");foreach(string name in new[]{"2","10","20"})Directory.CreateDirectory(Path.Combine(siblings,name));Config.SiblingNavigation=true;await NavigateFolder(Path.Combine(siblings,"20"));await CrossGridBoundary(1);check(Folder.EndsWith("2")&&Files.Count==0,"Thumbnail sibling cycle wraps to first empty folder");await CrossGridBoundary(-1);check(Folder.EndsWith("20"),"Thumbnail sibling cycle wraps backwards");autoScroll=true;autoBoundarySince=DateTime.UtcNow.AddSeconds(-4);AdvanceScroll();await Task.Delay(300);check(Folder.EndsWith("2")&&autoScroll,"Autoscroll advances through empty sibling and stays active");PauseScroll();Config.SiblingNavigation=false;
 await Open(file);check(TryPluginKey("U")&&pluginUndo!=null,"Drawing registers Ctrl+Z handler with overlay");EndPluginOverlay();check(pluginUndo==null,"Drawing undo handler removed when tool closes");
 check(Path.GetFullPath(Paths.Data).StartsWith(Path.GetFullPath(AppContext.BaseDirectory),StringComparison.OrdinalIgnoreCase),"Portable data is beneath executable directory");
 }
}
