using System;using System.Linq;using System.Threading.Tasks;using System.Runtime.InteropServices;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace gazegallery;
public partial class MainWindow {
 static readonly string[] OverlayNames33={"Zoom","Image Position","Slideshow","Diagnostics","Navigation Arrows","Filmstrip","Metadata","Histogram"};
 bool preparingImage33,resizingImageWindow33;double stripInset33;
 void StartStopSlideshow33(){if(slideshow)EndSlideshow();else ChangeSlideshow();}
 void SlideshowKey33(){if(!Config.SlideshowTimer){Config.SlideshowTimer=true;Config.TimerAutoHide=false;}else StartStopSlideshow33();Config.Save();View.InvalidateVisual();}
 public ContextMenu FilmstripMenu33(){var menu=new ContextMenu();var size=new MenuItem{Header="Thumbnail size…"};size.Click+=(_,_)=>{string? text=Ui.Prompt(this,"Filmstrip thumbnail size (24–240 px)",Config.FilmstripSize.ToString());if(int.TryParse(text,out int n)){Config.FilmstripSize=Math.Clamp(n,24,240);Config.Save();UpdateFilmstripLayout33();strip.InvalidateVisual();}};menu.Items.Add(size);var shrink=new MenuItem{Header="Shrink image view",IsCheckable=true,IsChecked=Config.FilmstripShrink,InputGestureText=Config.FilmstripShrink?"✓":""};shrink.Click+=(_,_)=>{Config.FilmstripShrink=shrink.IsChecked;Config.Save();UpdateFilmstripLayout33();};menu.Items.Add(shrink);AddTimeline34(menu);AddEndOfFolderChoices(menu);CloseOverlayMenu(menu,()=>{Config.Filmstrip=false;strip.Visibility=Visibility.Collapsed;UpdateFilmstripLayout33();});NormalizeMenuSeparators(menu);return menu;}
 double FilmstripInset33=>Mode=="viewer"&&Config.Filmstrip&&Config.FilmstripShrink&&!Cropping?Math.Clamp(Config.FilmstripSize,24,240)*1.25+16:0;
 void UpdateFilmstripLayout33(){double inset=FilmstripInset33;if(Math.Abs(inset-stripInset33)<.01)return;stripInset33=inset;View.Margin=new Thickness(View.Margin.Left,0,0,inset);View.UpdateLayout();if(!View.ZoomUsed&&!Cropping)FitViewer33();}
 void FitViewer33(){if(imageWindow&&!fullscreen){FitImageWindow33();return;}View.Fit();}
 void FitImageWindow33(){if(View.Image==null)return;SyncWindowFit34(View.RenderSize);View.ZoomUsed=false;View.InvalidateVisual();}
 [DllImport("user32.dll")]static extern bool SetWindowPos(IntPtr hwnd,IntPtr after,int x,int y,int width,int height,uint flags);
 void ApplyImageWindow33(Rect r,double dx,double dy){using var scope=Dispatcher.DisableProcessing();resizingImageWindow33=true;IntPtr handle=IntPtr.Zero;try{PrimeWindowFit34(r);handle=new System.Windows.Interop.WindowInteropHelper(this).Handle;if(handle!=IntPtr.Zero){if(!SetWindowPos(handle,IntPtr.Zero,(int)Math.Round(r.X*dx),(int)Math.Round(r.Y*dy),(int)Math.Round(r.Width*dx),(int)Math.Round(r.Height*dy),0x011C))throw new System.ComponentModel.Win32Exception();}else{Width=r.Width;Height=r.Height;Left=r.Left;Top=r.Top;}root.UpdateLayout();View.InvalidateVisual();}finally{resizingImageWindow33=false;if(handle!=IntPtr.Zero)RedrawWindow37(handle,IntPtr.Zero,IntPtr.Zero,0x05A1);}}
 static MenuItem? OverlayEntry33(object source){var d=source as DependencyObject;while(d!=null){if(d is MenuItem m&&Equals(m.Tag,"overlay-option"))return m;d=d is Visual?VisualTreeHelper.GetParent(d):LogicalTreeHelper.GetParent(d);}return null;}
 void OpenOverlayOptions33(string name){lastRightClick=0;switch(name){case "Zoom":FitMenu();break;case "Image Position":PositionContext();break;case "Slideshow":SlideshowMenu();break;case "Filmstrip":FilmstripMenu33().IsOpen=true;break;case "Histogram":HistogramMenu33().IsOpen=true;break;default:var menu=new ContextMenu();CloseOverlayMenu(menu,()=>{switch(name){case "Metadata":Config.MetadataOverlay=false;metadataPanel.Visibility=Visibility.Collapsed;break;case "Diagnostics":diagnostic=false;graph.Visibility=Visibility.Collapsed;break;case "Navigation Arrows":Config.Arrows=false;break;}},separator:name!="Metadata");menu.IsOpen=true;break;}}
 ContextMenu HistogramMenu33(){var m=new ContextMenu();void Add(string name,Func<bool> read,Action<bool> write){var i=new MenuItem{Header=name,IsCheckable=true,IsChecked=read(),StaysOpenOnClick=true,InputGestureText=read()?"✓":""};i.Click+=(_,_)=>{write(i.IsChecked);i.InputGestureText=i.IsChecked?"✓":"";histogramImage=null;Config.Save();};m.Items.Add(i);}Add("Red",()=>Config.HistogramRed,v=>Config.HistogramRed=v);Add("Green",()=>Config.HistogramGreen,v=>Config.HistogramGreen=v);Add("Blue",()=>Config.HistogramBlue,v=>Config.HistogramBlue=v);Add("Gray",()=>Config.HistogramGray,v=>Config.HistogramGray=v);CloseOverlayMenu(m,()=>Config.Histogram=false);return m;}
 public static BitmapSource BlurredPreview(BitmapSource source){double f=Math.Min(1,256d/Math.Max(source.PixelWidth,source.PixelHeight));BitmapSource small=source;if(f<1){small=new TransformedBitmap(source,new ScaleTransform(f,f));small.Freeze();}var bytes=PixelAnalysis.Pixels(small,out int stride);for(int n=0;n<3;n++)bytes=ExtendedAdjustments.Box(bytes,small.PixelWidth,small.PixelHeight,8,false);var result=BitmapSource.Create(small.PixelWidth,small.PixelHeight,96,96,PixelFormats.Bgra32,null,bytes,stride);result.Freeze();return result;}
 static Task<Brush?> PrepareBackground33(BitmapSource image,string mode)=>mode is "Auto" or "Blur"?Sta.Run<Brush?>(()=>{Brush b=mode=="Auto"?new SolidColorBrush(BackgroundAnalysis32.EdgeColor(image)):new ImageBrush(BlurredPreview(image));b.Freeze();return b;}):Task.FromResult<Brush?>(null);
 async Task CommitStill33(BitmapSource image,int id){string mode=Config.ViewerBackground;bool running=slideshow;int visual=visualGeneration;string effect=Choose(Config.SlideViews,"None"),transition=Choose(Config.SlideTransitions,"None"),slideMode=Choose(Config.SlideBackgrounds,"Plain");var bgTask=PrepareBackground33(image,mode);var slideTask=running&&slideMode!=mode?PrepareBackground33(image,slideMode):bgTask;await Task.WhenAll(bgTask,slideTask);Brush? bg=bgTask.Result,slide=slideTask.Result;if(id!=generation)return;if(mode!=Config.ViewerBackground){await CommitStill33(image,id);return;}background32Epoch++;background32Source=image;background32Mode=mode;background32Color=bg is SolidColorBrush?bg:null;background32Blur=(bg as ImageBrush)?.ImageSource as BitmapSource;if(running&&slideshow&&visual==visualGeneration){activeSlideEffect=effect;activeSlideTransition=transition;activeSlideBackground=slideMode;panDirection=Random.Shared.Next(2)==0?-1:1;slideBackground=(slide as ImageBrush)?.ImageSource as BitmapSource;slideAutoColor=slide is SolidColorBrush?slide:null;slideVisualStart=DateTime.UtcNow;if(slidePaused)slidePausedAt=slideVisualStart;else slideDeadline=DateTime.Now.AddSeconds(Config.SlideSeconds);}sourceImage=image;View.ZoomUsed=false;View.Image=image;MarkPresented35(current);holdingSlide33=false;preparingImage33=false;if(imageWindow&&!fullscreen)MatchImageWindow();else View.Fit();View.InvalidateVisual();}

}

