using System;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace gazegallery;
public partial class MainWindow {
 Border histogramPanel=new();BitmapSource? histogramImage,graySource,grayImage;int histogramEpoch,grayEpoch;bool grayPending,histogramPending;public bool AdjustmentsOpen;
 UIElement OverlaySettings(){var p=new StackPanel{Margin=new Thickness(8)};p.Children.Add(Ui.Label("Show these entries in the Overlays context submenu",12));foreach(string name in OverlayNames33)Ui.Check(p,name,!Config.HiddenOverlays.Contains(name),v=>{Config.HiddenOverlays.Remove(name);if(!v)Config.HiddenOverlays.Add(name);});return p;}
 void SetupRound31(){if(!Config.Keys.ContainsKey("Slideshow toggle"))Config.Keys["Slideshow toggle"]=new[]{"Y"};if(!Config.Keys.ContainsKey("Filmstrip"))Config.Keys["Filmstrip"]=new[]{"G"};if(!Config.Keys.ContainsKey("Grayscale view"))Config.Keys["Grayscale view"]=new[]{"I"};if(!Config.Effects31){if(Config.SlideEffect=="Slow Zoom")Config.SlideViews=new(){"Zoom In","Zoom Out"};else if(Config.SlideEffect is "Pan with Blurred Background" or "Random"){Config.SlideBackgrounds=new(){"Blur"};Config.SlideViews=Config.SlideEffect=="Random"?new(){"Pan","Zoom In","Zoom Out"}:new(){"Pan"};}Config.Effects31=true;}histogramPanel=new Border{Width=280,Height=135,Background=new SolidColorBrush(Color.FromArgb(192,30,32,36)),CornerRadius=new(6),Padding=new(8),HorizontalAlignment=HorizontalAlignment.Left,VerticalAlignment=VerticalAlignment.Top,Margin=new(12,180,12,12),Visibility=Visibility.Collapsed};histogramPanel.MouseRightButtonUp+=(_,e)=>{HistogramMenu33().IsOpen=true;e.Handled=true;};root.Children.Add(histogramPanel);}
 bool Round31Key(string key){if(Mode!="viewer"||Quick)return false;if(Config.Keys["Slideshow toggle"].Contains(key)){SlideshowKey33();return true;}if(Config.Keys["Filmstrip"].Contains(key)){Config.Filmstrip=!Config.Filmstrip;ResetFilmstrip();Config.Save();return true;}if(Config.Keys["Grayscale view"].Contains(key)){Config.Grayscale=!Config.Grayscale;graySource=null;grayImage=null;grayEpoch++;Config.Save();View.InvalidateVisual();return true;}return false;}
 public BitmapSource DisplayImage(BitmapSource image){if(!Config.Grayscale||Cropping||currentMotion)return image;if(ReferenceEquals(graySource,image)&&grayImage!=null)return grayImage;if(!grayPending){grayPending=true;int token=grayEpoch;_=Task.Run(async()=>{try{var result=await Sta.Run(()=>{return PixelAnalysis.Grayscale(image);});await Dispatcher.InvokeAsync(()=>{if(token==grayEpoch&&ReferenceEquals(View.Image,image)){graySource=image;grayImage=result;View.InvalidateVisual();}});}finally{await Dispatcher.InvokeAsync(()=>{grayPending=false;View.InvalidateVisual();});}});}return image;}
 async void RefreshHistogram(){histogramPanel.Visibility=Config.Histogram&&Mode=="viewer"&&!currentMotion&&View.Image!=null?Visibility.Visible:Visibility.Collapsed;if(histogramPending||histogramPanel.Visibility!=Visibility.Visible||ReferenceEquals(histogramImage,View.Image))return;histogramPending=true;var source=View.Image!;histogramImage=source;int token=++histogramEpoch;try{var counts=await LoaderPool.Run(()=>PixelAnalysis.Histogram(source));if(token!=histogramEpoch||!ReferenceEquals(View.Image,source))return;histogramPanel.Child=new HistogramDrawing(counts,Config.HistogramRed,Config.HistogramGreen,Config.HistogramBlue,Config.HistogramGray);}catch(Exception e){Paths.Log("histogram",e.Message);}finally{histogramPending=false;}}
 double imageWindowArea;
 void MatchImageWindow(){if(imageWindow&&!fullscreen&&View.Image!=null){if(Config.BorderlessFitsWindow)FitViewer33();else ResizeImageWindow(1,true);}}
 void ResizeImageWindow(double factor,bool match){if(!imageWindow||View.Image==null)return;if(Config.BorderlessFitsWindow){ResizeFixedWindow36(factor);return;}var screen=System.Windows.Forms.Screen.FromHandle(new System.Windows.Interop.WindowInteropHelper(this).Handle).WorkingArea;var dpi=VisualTreeHelper.GetDpi(this);var bounds=new Rect(screen.Left/dpi.DpiScaleX,screen.Top/dpi.DpiScaleY,screen.Width/dpi.DpiScaleX,screen.Height/dpi.DpiScaleY);double area=match?(imageWindowArea>0?imageWindowArea:Width*Height):Width*Height*factor*factor;var r=WindowSizing32.Resize(new Rect(Left,Top,Width,Height),area,View.Image.PixelWidth/(double)View.Image.PixelHeight,bounds);ApplyImageWindow33(r,dpi.DpiScaleX,dpi.DpiScaleY);if(!match)imageWindowArea=r.Width*r.Height;}

}
public static class PixelAnalysis {
 public static byte[] Pixels(BitmapSource source,out int stride){var b=new FormatConvertedBitmap(source,PixelFormats.Bgra32,null,0);stride=source.PixelWidth*4;var data=new byte[stride*source.PixelHeight];b.CopyPixels(data,stride,0);return data;}
 public static BitmapSource Grayscale(BitmapSource source){var bytes=Pixels(source,out int stride);for(int p=0;p<bytes.Length;p+=4){byte luminance=(byte)Math.Round(.2126*bytes[p+2]+.7152*bytes[p+1]+.0722*bytes[p]);bytes[p]=bytes[p+1]=bytes[p+2]=luminance;}var image=BitmapSource.Create(source.PixelWidth,source.PixelHeight,source.DpiX,source.DpiY,PixelFormats.Bgra32,null,bytes,stride);image.Freeze();return image;}
 public static long[][] Histogram(BitmapSource source){var data=Pixels(source,out _);var bins=Enumerable.Range(0,4).Select(_=>new long[256]).ToArray();for(int p=0;p<data.Length;p+=4){if(data[p+3]==0)continue;bins[0][data[p+2]]++;bins[1][data[p+1]]++;bins[2][data[p]]++;bins[3][(int)Math.Round(.2126*data[p+2]+.7152*data[p+1]+.0722*data[p])]++;}return bins;}
}
sealed class HistogramDrawing:FrameworkElement {
 readonly long[][] bins;readonly bool[] enabled;public HistogramDrawing(long[][] b,params bool[] e){bins=b;enabled=e;}
 protected override void OnRender(DrawingContext dc){var colors=new[]{Colors.IndianRed,Colors.LightGreen,Colors.CornflowerBlue,Colors.Gainsboro};long peak=bins.Where((_,i)=>enabled[i]).SelectMany(b=>b).DefaultIfEmpty(1).Max();for(int i=0;i<4;i++){if(!enabled[i])continue;var g=new StreamGeometry();using(var c=g.Open()){c.BeginFigure(new Point(0,ActualHeight),false,false);for(int x=0;x<256;x++)c.LineTo(new Point(x/255d*ActualWidth,ActualHeight-bins[i][x]/(double)Math.Max(1,peak)*(ActualHeight-4)),true,false);}g.Freeze();dc.DrawGeometry(null,new Pen(new SolidColorBrush(colors[i]),1),g);}}
}
