using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Diagnostics;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;
namespace gazegallery;
public partial class MainWindow {
 async Task VerifyRound23(List<object> report,Action<bool,string> check,string work){
 string seed=Path.Combine(Paths.Test,"small_mario.png");await Open(seed);TryPluginKey("U");var controls=(Panel)pluginTools!.Child;var input=controls.Children.OfType<TextBox>().Single();var slider=controls.Children.OfType<Slider>().Single();check(input.Text=="8","Draw defaults to size eight");var key=new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(this),0,Key.D2){RoutedEvent=Keyboard.PreviewKeyDownEvent,Source=input};KeyDownHandler(this,key);check(!key.Handled,"Drawing host permits typing in size input");input.Text="80";check(slider.Minimum==40&&slider.Maximum==160&&slider.Value==80,"Manual brush size rebases slider");slider.Value=120;check(input.Text=="120"&&slider.Minimum==40&&slider.Maximum==160,"Slider changes size without rebasing its range");check(input.Foreground is SolidColorBrush brush&&brush.Color.R>180,"Brush-size text is light");EndPluginOverlay();
 await SetMode("board");await ImportBoard(Enumerable.Repeat(seed,4));check(View.BoardSelection.Count==0&&View.BoardSelected==-1,"Collage imports stay deselected");var ordered=View.Board.OrderBy(i=>i.ImportOrder).ToArray();FocusBoard(ordered[1]);RemoveBoardSelection();check(!View.Board.Contains(ordered[1]),"B removal can target focused unselected collage item");TryBoardNavigate(Config.Keys["Next"][0]);check(focusedBoard==ordered[2],"Next after focus removal keeps import-order position");FocusBoard(ordered[2],false);RemoveBoardSelection();TryBoardNavigate(Config.Keys["Previous"][0]);check(focusedBoard==ordered[0],"Previous after removal chooses prior surviving import");View.BoardSelection.Clear();View.BoardSelection.Add(ordered[0]);await StartBoardCrop();View.CropRect=new Rect(-10,-10,20,20);await ApplyBoardCrop();check(ordered[0].Image.PixelWidth==10&&ordered[0].Image.PixelHeight==10,"Collage overcrop clamps to source edges");var transparent=System.Windows.Media.Imaging.BitmapSource.Create(2,2,96,96,PixelFormats.Bgra32,null,new byte[16],8);transparent.Freeze();var transparentCrop=CropWithinImage(transparent,new Rect(-1,-1,2,2));var px=new byte[4];transparentCrop.CopyPixels(px,4,0);check(px[3]==0,"Collage crop preserves source transparency");ReleaseBoard();Mode="viewer";
 await Open(seed);StartCrop();Config.CropFillOutside=false;View.CropRect=new Rect(-10,-10,20,20);ConstrainViewerCrop();check(View.CropRect==new Rect(0,0,10,10),"Viewer crop clamp updates visible bounds");Config.CropFillOutside=true;View.CropRect=new Rect(-10,-10,20,20);check(ViewerCropArea().Width==20,"Viewer fill option preserves outside area");CancelCrop();check(MinWidth==300,"Window minimum width halved");
 string collection=Path.Combine(Paths.Test,"_testing","stress-3000-small");await Open(collection);Config.Masonry=true;GridRatios.Clear();var watch=Stopwatch.StartNew();await SetMode("grid");report.Add(new{metric="masonry_first_batch_ms",value=watch.Elapsed.TotalMilliseconds,tiles=View.Tiles.Count});check(View.Tiles.Count>=64&&View.Tiles.Count<Files.Count&&GridMetadataLoading,"Masonry shows first metadata batch before full folder");var stable=View.Tiles.Take(64).ToArray();while(GridMetadataLoading&&watch.ElapsedMilliseconds<15000)await Task.Delay(20);check(!GridMetadataLoading&&View.Tiles.Count==GridPaths.Count,"Masonry completes remaining metadata in background");check(stable.SequenceEqual(View.Tiles.Take(64)),"First masonry tiles stay fixed as later batches arrive");
 var cycle=Path.Combine(work,"scroll23");Directory.CreateDirectory(cycle);foreach(var name in new[]{"1","2"}){var d=Path.Combine(cycle,name);Directory.CreateDirectory(d);File.Copy(seed,Path.Combine(d,"image.png"));}await NavigateFolder(Path.Combine(cycle,"1"));Config.SiblingNavigation=true;autoScroll=true;await CrossGridBoundary(1);check(autoScroll&&Mode=="grid"&&Config.Masonry&&Folder.EndsWith("2"),"Adjacent autoscroll preserves masonry and active state");autoBoundarySince=DateTime.UtcNow.AddSeconds(-1.2);countdownSecond=-1;AdvanceScroll();check(toast.Text.Contains("2 seconds"),"Autoscroll countdown updates to two seconds");autoBoundarySince=DateTime.UtcNow.AddSeconds(-2.2);AdvanceScroll();check(toast.Text.Contains("1 second"),"Autoscroll countdown updates to one second");PauseScroll();Config.SiblingNavigation=false;
 }
}
