using System;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Shell;
namespace gazegallery;
public partial class MainWindow {
 Border peekDim36=new(){IsHitTestVisible=false,Visibility=Visibility.Collapsed,Background=new SolidColorBrush(Color.FromArgb(241,22,22,22))};string? returnPath36;bool transitionReverse36,reversePending36;Rect transitionTarget36,transitionClip36,transitionTargetClip36;DrawingGroup? transitionBackdrop36;
 void SetupRound36(){Deactivated+=(_,_)=>ResetAlt36();Activated+=(_,_)=>ResetAlt36();}
 void ResetAlt36(){altPeekHeld35=false;ClosePeek34();}
 void TrackReturn36(string path){if(returnPath36!=null&&!returnPath36.Equals(path,StringComparison.OrdinalIgnoreCase))returnPath36=null;}
 void ClearTransition36(){forwardPending37=false;transitionImage35=null;transitionBackdrop36=null;reversePending36=false;}
 public static Rect TransitionRect36(Rect from,Rect to,double t)=>new(from.X+(to.X-from.X)*t,from.Y+(to.Y-from.Y)*t,from.Width+(to.Width-from.Width)*t,from.Height+(to.Height-from.Height)*t);
 void PrepareReverse36(string previous,string next){reversePending36=false;if(previous=="viewer"&&next=="grid"&&Config.ThumbnailTransition&&returnPath36==current&&View.Image!=null&&!Paths.Motion(current??"")){transitionImage35=DisplayImage(View.Image);transitionFrom35=transitionClip36=View.ImageRect;reversePending36=true;}else ClearTransition36();}
 void FinishReverse36(string previous,string next){if(!reversePending36||next!="grid"||transitionImage35==null)return;int i=GridPaths.IndexOf(current??"");if(i<0||i>=View.Tiles.Count){ClearTransition36();return;}transitionTargetClip36=View.ScreenTile35(View.Tiles[i]);transitionTarget36=View.ThumbnailImageRect36(transitionTargetClip36,transitionImage35);transitionReverse36=true;transitionBackdrop36=null;transitionGeneration35=generation;transitionStart35=DateTime.UtcNow;reversePending36=false;}
 void OpenFilter36(Button owner){var popup=new Popup{PlacementTarget=owner,Placement=PlacementMode.Bottom,StaysOpen=false,AllowsTransparency=true};var row=new StackPanel{Orientation=Orientation.Horizontal};filterInput34=Ui.Input(gridFilter34);filterInput34.Width=160;filterInput34.FontSize=owner.FontSize;filterInput34.VerticalContentAlignment=VerticalAlignment.Center;filterInput34.ToolTip="Filename contains text; a leading period matches an extension";filterInput34.TextChanged+=(_,_)=>{gridFilter34=filterInput34.Text.Trim();filterRevision34++;PauseScroll();View.Scroll=0;View.Selected.Clear();ClosePeek34();filterDelay34.Stop();filterDelay34.Start();};row.Children.Add(filterInput34);row.Children.Add(Ui.Button("×",()=>filterInput34.Text=""));popup.Child=new Border{Background=Ui.Bg,CornerRadius=new(6),Padding=new(8),Child=row};popup.IsOpen=true;filterInput34.Focus();filterInput34.SelectAll();filterInput34.PreviewKeyDown+=(_,e)=>{if(e.Key is Key.Escape or Key.Enter){popup.IsOpen=false;View.Focus();e.Handled=true;}};}
 void AddWindowChoices36(ContextMenu menu){menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});menu.Items.Add(new MenuItem{Header="Window Behaviour",IsEnabled=false});var windowed=new MenuItem{Header="Windowed",IsCheckable=true,IsChecked=!imageWindow&&!fullscreen};windowed.Click+=(_,_)=>Run(SetWindowed36);menu.Items.Add(windowed);var borderless=new MenuItem{Header="Borderless",IsCheckable=true,IsChecked=imageWindow&&!fullscreen,IsEnabled=View.Image!=null};borderless.InputGestureText="right click for more";borderless.Click+=(_,_)=>Run(async()=>{if(!imageWindow)await ToggleImageWindow();else if(fullscreen)ToggleFullscreen();});borderless.PreviewMouseRightButtonUp+=(_,e)=>{e.Handled=true;var options=new ContextMenu();foreach(var pair in new[]{("Window fits image",false),("Image fits window",true)}){var item=new MenuItem{Header=pair.Item1,IsCheckable=true,IsChecked=Config.BorderlessFitsWindow==pair.Item2};item.Click+=(_,_)=>{Config.BorderlessFitsWindow=pair.Item2;Config.Save();if(imageWindow){if(!pair.Item2){imageWindowArea=Width*Height;MatchImageWindow();}else FitViewer33();}};options.Items.Add(item);}options.IsOpen=true;};menu.Items.Add(borderless);}
 Task SetWindowed36(){if(fullscreen)ToggleFullscreen();if(imageWindow)return ToggleImageWindow();WindowState=WindowState.Normal;WindowStyle=WindowStyle.SingleBorderWindow;ApplyBorderlessChrome36(false);HideFullscreenExit36();View.Fit();return Task.CompletedTask;}
 bool IsActualFullscreen36=>fullscreen&&WindowState==WindowState.Maximized&&WindowStyle==WindowStyle.None;
 void HideFullscreenExit36(){fullscreenExit.Visibility=Visibility.Collapsed;fullscreenExit.IsHitTestVisible=false;exitShown=false;fullscreenExit.BeginAnimation(OpacityProperty,null);fullscreenExit.Opacity=0;}
 void ApplyBorderlessChrome36(bool on){WindowChrome.SetWindowChrome(this,on?new WindowChrome{CaptionHeight=0,ResizeBorderThickness=new Thickness(4),GlassFrameThickness=new Thickness(0),CornerRadius=new CornerRadius(8),UseAeroCaptionButtons=false,NonClientFrameEdges=NonClientFrameEdges.None}:null);}
 public Rect WindowFitRect36(int w,int h,double vw,double vh){if(!Config.BorderlessFitsWindow)return WindowImageFit34.Rect(w,h,vw,vh);if(w<=0||h<=0||vw<=0||vh<=0)return Rect.Empty;double raw=Math.Min(vw/w,vh/h);double scale=Config.DefaultFit switch{"Fit width"=>vw/w,"Fit height"=>vh/h,"Comfy fit"=>Math.Min(4,raw*.95),"Original size"=>1,_=>Math.Min(4,raw)};return new Rect((vw-w*scale)/2,(vh-h*scale)/2,w*scale,h*scale);}
 void ResizeFixedWindow36(double factor){var screen=System.Windows.Forms.Screen.FromHandle(new System.Windows.Interop.WindowInteropHelper(this).Handle).WorkingArea;var dpi=VisualTreeHelper.GetDpi(this);var bounds=new Rect(screen.Left/dpi.DpiScaleX,screen.Top/dpi.DpiScaleY,screen.Width/dpi.DpiScaleX,screen.Height/dpi.DpiScaleY);double w=Math.Clamp(Width*factor,32,bounds.Width*.95),h=Math.Clamp(Height*factor,32,bounds.Height*.95);double x=Math.Clamp(Left+(Width-w)/2,bounds.Left,bounds.Right-w),y=Math.Clamp(Top+(Height-h)/2,bounds.Top,bounds.Bottom-h);ApplyImageWindow33(new Rect(x,y,w,h),dpi.DpiScaleX,dpi.DpiScaleY);}
}
public sealed partial class Surface {
 public DrawingGroup CaptureGrid36(){var drawing=new DrawingGroup();using(var dc=drawing.Open())DrawGridRetained(dc);var snapshot=drawing.CloneCurrentValue();snapshot.Freeze();return snapshot;}
 public Rect ThumbnailImageRect36(Rect tile,BitmapSource image){double scale=Host.Config.River&&image.PixelHeight>image.PixelWidth?Math.Max(tile.Width/image.PixelWidth,tile.Height/image.PixelHeight):Math.Min(tile.Width/image.PixelWidth,tile.Height/image.PixelHeight);double w=image.PixelWidth*scale,h=image.PixelHeight*scale;return new Rect(tile.X+(tile.Width-w)/2,tile.Y+(tile.Height-h)/2,w,h);}
}
