using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Threading;
namespace gazegallery;
public static class FolderFilter34 {public static bool Matches(string path,string query){query=query.Trim();return query.Length==0|| (query.StartsWith('.')?Path.GetFileName(path).EndsWith(query,StringComparison.OrdinalIgnoreCase):Path.GetFileName(path).Contains(query,StringComparison.OrdinalIgnoreCase));}}
public static class WindowImageFit34 {public static Rect Rect(int w,int h,double vw,double vh){if(w<=0||h<=0||vw<=0||vh<=0)return System.Windows.Rect.Empty;double scale=Math.Min(vw/w,vh/h)*1.02;return new Rect((vw-w*scale)/2,(vh-h*scale)/2,w*scale,h*scale);}}
public sealed class TransferBatch34 {public bool CancelRequested;public int Processed,Total;public readonly List<string> Completed=new();public string Current="";public async Task Run(string[] paths,Func<string,Task<bool>> transfer,Action? progress=null){Total=paths.Length;foreach(string path in paths){if(CancelRequested)break;Current=path;progress?.Invoke();if(await transfer(path))Completed.Add(path);Processed++;progress?.Invoke();}Current="";progress?.Invoke();}}
public partial class MainWindow {
 string gridFilter34="";TextBox? filterInput34;TextBlock? filterCount34;DispatcherTimer filterDelay34=new(){Interval=TimeSpan.FromMilliseconds(140)};int filterRevision34;Border batchPanel34=new();TextBlock batchText34=new(),batchFile34=new();ProgressBar batchBar34=new();TransferBatch34? batch34;
 public bool RenderWindowFit34=>Mode=="viewer"&&imageWindow&&!fullscreen&&!View.ZoomUsed&&!Cropping;
 public void SyncWindowFit34(Size viewport){if(View.Image==null)return;var r=WindowFitRect36(View.Image.PixelWidth,View.Image.PixelHeight,viewport.Width,viewport.Height);if(r.IsEmpty)return;View.Scale=r.Width/View.Image.PixelWidth;View.Pan=new(r.X,r.Y);}
 void PrimeWindowFit34(Rect window){View.ZoomUsed=false;SyncWindowFit34(new Size(Math.Max(0,window.Width-View.Margin.Left-View.Margin.Right),Math.Max(0,window.Height-View.Margin.Top-View.Margin.Bottom)));}
 void AddTimeline34(ContextMenu menu){menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});var timeline=new MenuItem{Header="Folder timeline",IsCheckable=true,IsChecked=Config.SlideTimeline,InputGestureText=Config.SlideTimeline?"✓":""};timeline.Click+=(_,_)=>{Config.SlideTimeline=timeline.IsChecked;Config.Save();View.InvalidateVisual();};menu.Items.Add(timeline);}
 void SetupRound34(){filterDelay34.Tick+=(_,_)=>{filterDelay34.Stop();Run(ApplyFilter34);};batchPanel34.Background=Ui.Bg;batchPanel34.CornerRadius=new(6);batchPanel34.Padding=new(10);batchPanel34.Width=420;batchPanel34.MaxWidth=Math.Max(260,Width-40);batchPanel34.HorizontalAlignment=HorizontalAlignment.Center;batchPanel34.VerticalAlignment=VerticalAlignment.Bottom;batchPanel34.Margin=new(12,0,12,100);batchPanel34.Visibility=Visibility.Collapsed;var box=new StackPanel();batchText34.Foreground=batchFile34.Foreground=Ui.Fg;batchFile34.TextTrimming=TextTrimming.CharacterEllipsis;batchText34.Margin=new(0,0,0,5);batchBar34.Height=4;batchBar34.Margin=new(0,5,0,5);box.Children.Add(batchText34);box.Children.Add(batchFile34);box.Children.Add(batchBar34);var cancel=Ui.Button("Cancel remaining",()=>{if(batch34!=null){batch34.CancelRequested=true;batchText34.Text="Finishing current file…";}});cancel.HorizontalAlignment=HorizontalAlignment.Right;box.Children.Add(cancel);batchPanel34.Child=box;root.Children.Add(batchPanel34);SetupPeek34();Activated+=(_,_)=>PollFocus34(true);Deactivated+=(_,_)=>Dispatcher.BeginInvoke(()=>PollFocus34(true),DispatcherPriority.Background);Closed+=(_,_)=>filterDelay34.Stop();}
 void AddFilter34(Panel toolbar){var filter=Ui.Button("Filter",()=>{});filter.VerticalAlignment=VerticalAlignment.Center;filter.Click+=(_,_)=>OpenFilter36(filter);toolbar.Children.Add(filter);filterCount34=Ui.Label("",12);filterCount34.VerticalAlignment=VerticalAlignment.Center;toolbar.Children.Add(filterCount34);UpdateFilterCount34();}
 void UpdateFilterCount34(){if(filterCount34!=null)filterCount34.Text=gridFilter34.Length==0?"":$"{Files.Count(p=>FolderFilter34.Matches(p,gridFilter34))} / {Files.Count}";}
 async Task ApplyFilter34(){if(Mode!="grid")return;PauseScroll();gridPreparation++;ClearGridHoles();View.Selected.Clear();View.Scroll=0;int revision=filterRevision34;await PrepareGrid();if(revision!=filterRevision34||Mode!="grid")return;View.Scroll=0;View.LayoutTiles();UpdateFilterCount34();}
 void ResetFilter34(){filterDelay34.Stop();gridFilter34="";filterRevision34++;ClosePeek34();}
 TransferBatch34 BeginBatch34(string label,int count){batch34=new TransferBatch34();batchBar34.Maximum=Math.Max(1,count);batchBar34.Value=0;batchPanel34.MaxWidth=Math.Max(260,ActualWidth-40);batchPanel34.Visibility=count>1?Visibility.Visible:Visibility.Collapsed;batchText34.Text=label;return batch34;}
 void ReportBatch34(string label){if(batch34==null)return;batchText34.Text=$"{label}: {batch34.Processed} / {batch34.Total} processed · {batch34.Completed.Count} completed";batchFile34.Text=Path.GetFileName(batch34.Current);batchBar34.Value=batch34.Processed;}
 void EndBatch34(){batchPanel34.Visibility=Visibility.Collapsed;batch34=null;}
}
