using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Text.Json;using System.Text.Json.Nodes;using System.Threading;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Animation;using System.Windows.Media.Imaging;
namespace gazegallery;
// No reads, existence checks or writes on ordinary navigation or startup.
public sealed class BookmarkStore35 {
 readonly string file;public BookmarkStore35(string file){this.file=file;}
 public List<string> Read(){try{return JsonSerializer.Deserialize<List<string>>(File.ReadAllText(file))?.Where(p=>!string.IsNullOrWhiteSpace(p)).Distinct(StringComparer.OrdinalIgnoreCase).Take(5).ToList()??new();}catch{return new();}}
 public static List<string> Promote(IEnumerable<string> current,string path)=>new[]{path}.Concat(current.Where(p=>!p.Equals(path,StringComparison.OrdinalIgnoreCase))).Take(5).ToList();
 public List<string> Save(string path)=>Change(list=>Promote(list,path));public List<string> Remove(string path)=>Change(list=>list.Where(p=>!p.Equals(path,StringComparison.OrdinalIgnoreCase)).ToList());public List<string> Replace(IEnumerable<string> entries)=>Change(_=>entries.Where(p=>!string.IsNullOrWhiteSpace(p)).Distinct(StringComparer.OrdinalIgnoreCase).Take(5).ToList());
 List<string> Change(Func<List<string>,List<string>> change){using var mutex=new Mutex(false,"Local\\gazegalleryBookmarks-"+Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(file))).Substring(0,16));bool held=false;try{try{held=mutex.WaitOne(5000);}catch(AbandonedMutexException){held=true;}if(!held)throw new IOException("Bookmarks are busy; try again.");var list=change(Read());Directory.CreateDirectory(Path.GetDirectoryName(file)!);string temp=file+".tmp";File.WriteAllText(temp,JsonSerializer.Serialize(list));File.Move(temp,file,true);return list;}finally{if(held)mutex.ReleaseMutex();}}
}
public partial class MainWindow {
 BookmarkStore35 bookmarks35=new(Path.Combine(Paths.Data,"bookmarks.json"));int bookmarkCount35;string? thumbnailReturn35;bool altPeekHeld35;DateTime transitionStart35;BitmapSource? transitionImage35;Rect transitionFrom35;int transitionGeneration35;string? presentedPath35,videoPath35,animationPath35;
 public bool FilmstripCanPresent35=>Mode=="viewer"&&!Operations.Busy&&!preparingImage33&&!bufferingVideo&&presentedPath35==current;
 void MarkPresented35(string? path){if(path==current)presentedPath35=path;}
 public string ThumbnailLayoutName35=>Config.River?"River":Config.Masonry?"Masonry":"Grid";
 void SetupRound35(){Config.Keys.Remove("Sort mode");foreach(var list in Config.MenuLayouts.Values)list.RemoveAll(x=>x=="Sort mode"||x=="Borderless windowed");}
 void CycleLayout35(){string previous=ThumbnailLayoutName35;Config.River=previous=="Masonry";Config.Masonry=previous=="Grid";if(Config.River)Config.Masonry=false;PauseScroll();View.Scroll=0;ClearGridHoles();Config.Save();BuildModeToolbar();View.LayoutTiles();}
 static Brush KeyTint35(){var c=Ui.CanvasColor;return new SolidColorBrush(Color.FromRgb((byte)Math.Round(c.R*.9+255*.1),(byte)Math.Round(c.G*.9+225*.1),(byte)Math.Round(c.B*.9+60*.1)));}
 ContextMenu BuildPositionMenu35(){var menu=new ContextMenu();var bookmark=new MenuItem{StaysOpenOnClick=true,Header=$"Bookmark position ({bookmarkCount35})",InputGestureText="right click for bookmarks"};void Update(){var line=new StackPanel{Orientation=Orientation.Horizontal};line.Children.Add(Ui.Label("Bookmark position",12));var count=Ui.Label($" ({bookmarkCount35})",12);count.Opacity=bookmarkCount35==0?.4:1;line.Children.Add(count);bookmark.Header=line;bookmark.Opacity=1;}Update();bookmark.Click+=(_,_)=>Run(async()=>{if(current==null)return;string path=current;var list=await Task.Run(()=>bookmarks35.Save(path));bookmarkCount35=list.Count;Update();Toast("Position bookmarked");});bookmark.PreviewMouseRightButtonUp+=(_,e)=>{e.Handled=true;OpenBookmarks35(bookmark,Update);};menu.Items.Add(bookmark);menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});AddSortChoices(menu);AddEndOfFolderChoices(menu);AddTimeline34(menu);NormalizeMenuSeparators(menu);CloseOverlayMenu(menu,()=>Config.PositionIndicator=false);_=RefreshBookmarkCount35(Update);return menu;}
 async Task RefreshBookmarkCount35(Action update){var list=await Task.Run(bookmarks35.Read);bookmarkCount35=list.Count;update();}
 async void OpenBookmarks35(MenuItem owner,Action update){var menu=new ContextMenu{PlacementTarget=owner,Placement=PlacementMode.Right};menu.Items.Add(new MenuItem{Header="Loading bookmarks…",IsEnabled=false});menu.IsOpen=true;try{var entries=await Task.Run(()=>bookmarks35.Read().Select(p=>(Path:p,Exists:File.Exists(p))).ToArray());bookmarkCount35=entries.Length;update();if(!menu.IsOpen)return;menu.Items.Clear();foreach(var entry in entries){var row=new DockPanel{MinWidth=260};var remove=Ui.Button("×",()=>Run(async()=>{await Task.Run(()=>bookmarks35.Remove(entry.Path));menu.Items.Remove(row);bookmarkCount35=Math.Max(0,bookmarkCount35-1);update();}));DockPanel.SetDock(remove,Dock.Right);row.Children.Add(remove);var text=Ui.Label(Path.GetFileName(entry.Path),12);text.ToolTip=entry.Path;text.TextTrimming=TextTrimming.CharacterEllipsis;if(!entry.Exists){text.Opacity=.4;text.TextDecorations=TextDecorations.Strikethrough;}var go=Ui.Button("",()=>{menu.IsOpen=false;Run(()=>Open(entry.Path));});go.Tag="Flat";remove.Tag="Flat";go.Content=text;go.IsEnabled=entry.Exists;go.HorizontalContentAlignment=HorizontalAlignment.Left;row.Children.Add(go);menu.Items.Add(row);}if(entries.Length==0)menu.Items.Add(new MenuItem{Header="No bookmarks",IsEnabled=false});}catch(Exception ex){Error(ex);menu.IsOpen=false;}}
 void ExportWithBookmarks35(string target){var json=JsonNode.Parse(File.ReadAllText(Path.Combine(Paths.Data,"settings.json")))!.AsObject();json["Bookmarks35"]=JsonSerializer.SerializeToNode(bookmarks35.Read());File.WriteAllText(target,json.ToJsonString(new JsonSerializerOptions{WriteIndented=true}));}
 void ImportBookmarks35(string source){var json=JsonNode.Parse(File.ReadAllText(source));if(json?["Bookmarks35"] is JsonArray list)bookmarks35.Replace(list.Deserialize<List<string>>()??new());}
 public void ArmThumbnailReturn35()=>thumbnailReturn35=current;
 public void TrackThumbnailReturn35(string path){if(thumbnailReturn35!=null&&!thumbnailReturn35.Equals(path,StringComparison.OrdinalIgnoreCase))thumbnailReturn35=null;}
 bool TryThumbnailBack35(){if(Mode!="viewer"||thumbnailReturn35==null||current!=thumbnailReturn35)return false;thumbnailReturn35=null;Run(()=>SetMode("grid"));return true;}
 bool ThumbnailAlt35(KeyEventArgs e,bool down){Key k=e.Key==Key.System?e.SystemKey:e.Key;if(Mode!="grid"||k is not (Key.LeftAlt or Key.RightAlt))return false;if(down&&(!IsActive||e.IsRepeat))return false;altPeekHeld35=down;e.Handled=true;if(!down)ClosePeek34();return true;}
 void LoopMenu35(){var menu=new ContextMenu();foreach(var pair in new[]{("Set A",(Action)(()=>SetAB34(false))),("Set B",()=>SetAB34(true)),("Clear loop",ClearAB34)}){var item=new MenuItem{Header=pair.Item1};item.Click+=(_,_)=>pair.Item2();menu.Items.Add(item);}menu.Items.Add(new Separator{Style=(Style)FindResource(typeof(Separator))});loopLabel34=Ui.Label("",11);RefreshAB34();menu.Items.Add(loopLabel34);menu.IsOpen=true;}
 async Task EnterThumbnailView35(int index){string path=GridPaths[index];bool animate=Config.ThumbnailTransition&&!Paths.Motion(path);var grid=animate?View.CaptureGrid36():null;Rect tile=View.ScreenTile35(View.Tiles[index]);var load=SetMode("viewer");if(animate){forwardPending37=true;transitionBackdrop36=grid;forwardGeneration37=generation;View.InvalidateVisual();}try{await load;if(!animate||Mode!="viewer"||View.Image==null||current!=path){ClearTransition36();return;}transitionImage35=DisplayImage(View.Image);transitionFrom35=View.ThumbnailImageRect36(tile,transitionImage35);transitionClip36=tile;transitionBackdrop36=grid;transitionReverse36=false;returnPath36=path;transitionGeneration35=generation;transitionStart35=DateTime.UtcNow;View.InvalidateVisual();}finally{forwardPending37=false;}}
 public bool DrawThumbnailTransition35(DrawingContext dc){if(forwardPending37){if(Mode!="viewer"||generation!=forwardGeneration37){ClearTransition36();return false;}if(transitionBackdrop36!=null)dc.DrawDrawing(transitionBackdrop36);return true;}if(transitionImage35==null)return false;if(reversePending36){dc.DrawRectangle(CanvasBrush,null,new Rect(View.RenderSize));dc.DrawImage(transitionImage35,transitionFrom35);return true;}if((transitionReverse36?Mode!="grid":Mode!="viewer")||generation!=transitionGeneration35){ClearTransition36();return false;}double t=Math.Clamp((DateTime.UtcNow-transitionStart35).TotalSeconds/.134,0,1);if(t>=1){ClearTransition36();return false;}t=t*t*(3-2*t);var end=transitionReverse36?transitionTarget36:View.ImageRect;var a=transitionFrom35;var r=TransitionRect36(a,end,t);if(transitionReverse36){dc.PushOpacity(1-t);dc.DrawRectangle(CanvasBrush,null,new Rect(View.RenderSize));dc.Pop();}if(!transitionReverse36&&transitionBackdrop36!=null){dc.PushOpacity(1-t);dc.DrawDrawing(transitionBackdrop36);dc.Pop();}dc.PushClip(new RectangleGeometry(TransitionRect36(transitionClip36,transitionReverse36?transitionTargetClip36:end,t)));dc.DrawImage(transitionImage35,r);dc.Pop();return true;}
 void TickTransition35(){if(transitionImage35!=null)View.InvalidateVisual();}
}
