using System;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;
namespace gazegallery;
public partial class MainWindow {
 void PreviewSet<T>(Window owner,string title,List<T> entries,List<T> current,Func<T,string> label,Func<T,T?> copy,Action<List<T>> commit) where T:class {
  var w=Ui.Dialog(owner,title,650,540);var p=new StackPanel{Margin=new Thickness(14)};var rows=new StackPanel();
  void CopyOne(T value){var choose=Ui.Dialog(w,"Choose destination slot",600,430);var slots=new StackPanel{Margin=new Thickness(12)};for(int i=0;i<current.Count;i++){int slot=i;slots.Children.Add(Ui.Button($"{i+1}. {label(current[i])}",()=>{var item=copy(value);if(item==null)return;var result=current.ToList();result[slot]=item;commit(result);choose.Close();w.Close();}));}slots.Children.Add(Ui.Button("Cancel",choose.Close));choose.Content=new ScrollViewer{Content=slots};choose.ShowDialog();}
  for(int i=0;i<entries.Count;i++){var entry=entries[i];var row=new DockPanel();var button=Ui.Button("Copy to slot…",()=>CopyOne(entry));DockPanel.SetDock(button,Dock.Right);row.Children.Add(button);row.Children.Add(Ui.Label($"{i+1}. {label(entry)}",12));rows.Children.Add(row);}p.Children.Add(new ScrollViewer{Content=rows,Height=365});var actions=new WrapPanel();actions.Children.Add(Ui.Button("Copy All",()=>{var result=new List<T>();foreach(var item in entries){var value=copy(item);if(value==null)return;result.Add(value);}commit(result);w.Close();}));actions.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(actions);w.Content=p;w.ShowDialog();
 }
 ExternalProgram? CopyProgram(Window owner,ExternalProgram item){string args=item.Arguments;if(!string.IsNullOrWhiteSpace(args)&&args.Trim()!="{file}"){var w=Ui.Dialog(owner,"Custom arguments too?",540,240);var p=new StackPanel{Margin=new Thickness(14)};p.Children.Add(Ui.Label(item.Executable+"\n"+args,12));p.Children.Add(Ui.Label("Custom arguments too?",14));int answer=0;var row=new WrapPanel();foreach(var pair in new[]{("Yes",1),("No",2),("Cancel",0)})row.Children.Add(Ui.Button(pair.Item1,()=>{answer=pair.Item2;w.Close();}));p.Children.Add(row);w.Content=p;w.ShowDialog();if(answer==0)return null;if(answer==2)args="{file}";}return new ExternalProgram{Executable=item.Executable,Arguments=args};}
 void ExternalSetsMenu(string extension){var w=Ui.Dialog(this,"External program sets",600,490);var p=new StackPanel{Margin=new Thickness(14)};var list=new StackPanel();void Preview(string name,List<ExternalProgram> entries)=>PreviewSet(w,name,entries,Config.ExternalPrograms[extension],e=>string.IsNullOrEmpty(e.Executable)?"Empty":e.Executable,e=>CopyProgram(w,e),items=>{Config.ExternalPrograms[extension]=items;Config.Save();});void Refresh(){list.Children.Clear();list.Children.Add(Ui.Label("Named sets",14));foreach(var pair in Config.ExternalSets.ToArray()){var row=new DockPanel();var remove=Ui.Button("−",()=>{Config.ExternalSets.Remove(pair.Key);Config.Save();Refresh();});DockPanel.SetDock(remove,Dock.Right);row.Children.Add(remove);row.Children.Add(Ui.Button(pair.Key,()=>Preview(pair.Key,pair.Value)));list.Children.Add(row);}list.Children.Add(Ui.Label("Other extensions",14));foreach(var pair in Config.ExternalPrograms.Where(x=>x.Key!=extension).ToArray())list.Children.Add(Ui.Button(pair.Key,()=>Preview(pair.Key,pair.Value)));}Refresh();p.Children.Add(new ScrollViewer{Content=list,Height=340});var buttons=new WrapPanel();buttons.Children.Add(Ui.Button("Save current as…",()=>{var name=Ui.Prompt(w,"Set name","")?.Trim();if(string.IsNullOrEmpty(name))return;Config.ExternalSets[name]=Config.ExternalPrograms[extension].Select(e=>new ExternalProgram{Executable=e.Executable,Arguments=e.Arguments}).ToList();Config.Save();Refresh();}));buttons.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(buttons);w.Content=p;w.ShowDialog();}
 void DestinationSetMenu(){var w=Ui.Dialog(this,Config.QuickSecondUniversal?"Second universal sets":"Location-specific sets",650,530);var p=new StackPanel{Margin=new Thickness(14)};var list=new StackPanel();void Preview(string name,List<Destination> entries)=>PreviewSet(w,name,entries,Config.Destinations(Folder).Skip(10).ToList(),d=>string.IsNullOrEmpty(d.Folder)?"Empty":FriendlyKey(d.Key)+" — "+d.Folder,d=>new Destination{Folder=d.Folder,Key=d.Key},items=>{Config.SetSecondDestinations(Folder,items);Config.Save();});void Refresh(){list.Children.Clear();list.Children.Add(Ui.Label("Named sets",14));foreach(var pair in Config.DestinationSets.ToArray()){var row=new DockPanel();var remove=Ui.Button("−",()=>{Config.DestinationSets.Remove(pair.Key);Config.Save();Refresh();});DockPanel.SetDock(remove,Dock.Right);row.Children.Add(remove);row.Children.Add(Ui.Button(pair.Key,()=>Preview(pair.Key,pair.Value)));list.Children.Add(row);}list.Children.Add(Ui.Label("Other folders",14));foreach(var pair in Config.Local.Where(x=>!x.Key.Equals(Folder,StringComparison.OrdinalIgnoreCase)&&x.Value.Any(d=>d.Folder.Length>0)).ToArray())list.Children.Add(Ui.Button(pair.Key,()=>Preview(pair.Key,pair.Value)));}Refresh();p.Children.Add(new ScrollViewer{Content=list,Height=370});var buttons=new WrapPanel();buttons.Children.Add(Ui.Button("Save current ten as…",()=>{var name=Ui.Prompt(w,"Set name","")?.Trim();if(string.IsNullOrEmpty(name))return;Config.DestinationSets[name]=Config.Destinations(Folder).Skip(10).Select(d=>new Destination{Folder=d.Folder,Key=d.Key}).ToList();Config.Save();Refresh();}));buttons.Children.Add(Ui.Button("Cancel",w.Close));p.Children.Add(buttons);w.Content=p;w.ShowDialog();if(Quick){Quick=false;ToggleQuick();}}
}
