using System;using System.IO;using System.Linq;using System.Text.Json;using System.Windows;using System.Windows.Controls;using Microsoft.Win32;
namespace gazegallery;
public partial class MainWindow {
 bool ImportSettings(){var dialog=new OpenFileDialog{Title="Import gazegallery settings",Filter="gazegallery settings|settings.json;*.json"};if(dialog.ShowDialog(this)!=true)return false;try{var settings=JsonSerializer.Deserialize<Settings>(File.ReadAllText(dialog.FileName))??throw new IOException("Empty settings file");if(settings.Columns<2||settings.Columns>9||settings.Global==null||settings.Local==null||settings.Keys==null)throw new IOException("This file does not contain valid gazegallery settings.");if(!Ui.Confirm(this,"Import settings?","Replace your preferences, keybindings and folder destinations with this file? Your current settings are backed up.","Import",true))return false;string current=Path.Combine(Paths.Data,"settings.json");if(File.Exists(current))File.Copy(current,Path.Combine(Paths.Data,"settings-before-import-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".json"));ImportBookmarks35(dialog.FileName);Config=settings;LoaderPool.Limit=Config.LoaderThreads;Config.Save();ResetFilmstrip();metadataPath=null;ApplyPalette();Toast("Settings imported. Restart gazegallery to apply all bindings and startup options.");return true;}catch(Exception ex){Error(ex);return false;}}
 void GroupGeneralSettings(StackPanel panel){
  var groups=new[]{("Viewing and appearance",new[]{"OLED","Checkerboard","Smooth","Default fit","Auto hide cursor","Scroll wheel navigates"}),("Overlays",new[]{"navigation arrows","Show zoom","Show image position","Show fullscreen exit"}),("Playback and window",new[]{"Default video","Mute","Pause motion","Start in borderless"}),("Folders and file actions",new[]{"Confirmation","Confirm Escape","End of folder","Folder order","Right-click a quick-sort","Moves, crops"}),("Performance",new[]{"cache budget","Thumbnail preview","Loader threads"}),("Startup",new[]{"Startup","Hide quick start"}),("Settings backup",new[]{"Export settings","Import settings"})};
  var items=panel.Children.Cast<UIElement>().ToArray();panel.Children.Clear();var buckets=groups.Select(_=>new StackPanel{Margin=new Thickness(12,8,4,12)}).ToArray();int selected=0;
  foreach(var item in items){if(item is Separator)continue;string text=item switch{TextBlock t=>t.Text,CheckBox c=>c.Content?.ToString()??"",Button b=>b.Content?.ToString()??"",_=>""};if(text=="gazegallery")continue;for(int i=0;i<groups.Length;i++)if(groups[i].Item2.Any(k=>text.Contains(k,StringComparison.OrdinalIgnoreCase))){selected=i;break;}if(text=="Startup")continue;buckets[selected].Children.Add(item);}
  for(int i=0;i<groups.Length;i++){var header=Ui.Label(groups[i].Item1,14);panel.Children.Add(new Expander{Header=header,Content=buckets[i],IsExpanded=false,Foreground=Ui.Fg,Margin=new Thickness(0,4,0,4)});panel.Children.Add(new Separator());}
 }
}
