using System;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Effects;using System.Windows.Media.Imaging;
namespace gazegallery;
public partial class MainWindow {
 BitmapSource? previousSlide,slideBackground;DateTime slideVisualStart;string activeSlideEffect="None",activeSlideTransition="None",activeSlideBackground="Plain";int panDirection=1,visualGeneration;int[] timelineIndices=Array.Empty<int>();object? timelineFiles;
 Brush? slideAutoColor;DateTime? slidePausedAt;bool SlideVisualEnabled=>activeSlideEffect!="None"||activeSlideBackground!="Plain"||activeSlideTransition!="None";
 bool HasSlideEffects=>Config.SlideViews.Any(v=>v!="None")||Config.SlideBackgrounds.Any(v=>v!="Plain")||Config.SlideTransitions.Any(v=>v!="None");
 static string Choose(System.Collections.Generic.List<string> options,string fallback)=>options.Count==0?fallback:options[Random.Shared.Next(options.Count)];
 void SlideshowOptions(){bool resume=slideshow&&!slidePaused;bool animationWasPlaying=animation?.Playing==true;if(resume){ChangeSlideshow();if(animation!=null)animation.Playing=false;}var backgrounds=Config.SlideBackgrounds.ToList();var transitions=Config.SlideTransitions.ToList();var views=Config.SlideViews.ToList();try{var w=Ui.Dialog(this,"Slideshow effects",470,570);var panel=new StackPanel{Margin=new Thickness(18)};void Group(string name,string[] choices,System.Collections.Generic.List<string> enabled){panel.Children.Add(Ui.Label(name,14));foreach(var option in choices)Ui.Check(panel,option,enabled.Contains(option),on=>{enabled.Remove(option);if(on)enabled.Add(option);});panel.Children.Add(new Separator());}Group("Background",new[]{"Plain","Auto","Blur"},backgrounds);Group("Transition",new[]{"None","Crossfade","Soft Zoom Fade"},transitions);Group("View effect",new[]{"None","Pan","Zoom In","Zoom Out"},views);panel.Children.Add(Ui.Label("Changes start with the next image. Playback stays paused while these options are open. Transitions take 0.5 seconds; animated media uses ordinary playback.",11));panel.Children.Add(Ui.Button("Done",()=>{Config.SlideBackgrounds=backgrounds;Config.SlideTransitions=transitions;Config.SlideViews=views;Config.Save();w.Close();}));w.Content=new ScrollViewer{Content=panel};w.ShowDialog();}finally{if(resume&&slideshow){ChangeSlideshow();if(animation!=null&&animationWasPlaying)animation.Playing=true;}}}
 double heldSlideProgress33;bool holdingSlide33;
 void CaptureSlideVisual(){heldSlideProgress33=Math.Clamp(1-RemainingSeconds/Math.Max(.1,Config.SlideSeconds),0,1);holdingSlide33=slideshow;previousSlide=slideshow&&SlideVisualEnabled&&current!=null&&!currentMotion&&largeRaster==null?View.Image:null;visualGeneration++;}
 void BeginSlideVisual(BitmapSource image,int id){slideVisualStart=DateTime.UtcNow;activeSlideEffect=Choose(Config.SlideViews,"None");activeSlideTransition=Choose(Config.SlideTransitions,"None");activeSlideBackground=Choose(Config.SlideBackgrounds,"Plain");panDirection=Random.Shared.Next(2)==0?-1:1;int token=++visualGeneration;slideAutoColor=null;if(!slideshow||activeSlideBackground=="Plain"||current==null||currentMotion)return;_=Task.Run(async()=>{try{var bg=await Sta.Run(()=>{Brush result=activeSlideBackground=="Auto"?new SolidColorBrush(BackgroundAnalysis32.EdgeColor(image)):new ImageBrush(BlurredPreview(image));result.Freeze();return result;});await Dispatcher.InvokeAsync(()=>{if(id==generation&&token==visualGeneration){if(bg is ImageBrush b)slideBackground=(BitmapSource)b.ImageSource;else slideAutoColor=bg;View.InvalidateVisual();}});}catch(Exception e){Paths.Log("slideshow-preview",e.Message);}});}

 Rect SlideFit(BitmapSource image,double zoom=1,double shift=0){double f=Math.Min(View.ActualWidth*.95/image.PixelWidth,View.ActualHeight*.95/image.PixelHeight)*zoom;double w=image.PixelWidth*f,h=image.PixelHeight*f;return new Rect((View.ActualWidth-w)/2+shift,(View.ActualHeight-h)/2,w,h);}
 public static Rect PanFrame32(int iw,int ih,double vw,double vh,double seconds,double progress,int direction){double fit=Math.Min(vw/iw,vh/ih)*.95,fill=Math.Max(vw/iw,vh/ih)*1.03,blend=Math.Clamp(seconds/30,0,1),scale=fit+(fill-fit)*blend,w=iw*scale,h=ih*scale;bool horizontal=iw>=ih;double travel=Math.Min(Math.Abs(horizontal?w-vw:h-vh)*.7,seconds*8),offset=(progress-.5)*direction*travel;return new Rect((vw-w)/2+(horizontal?offset:0),(vh-h)/2+(horizontal?0:offset),w,h);}
 public static double MotionZoom(string effect,double progress)=>effect=="Zoom In"?1+progress*.12:effect=="Zoom Out"?1.12-progress*.12:1;
 public bool DrawSlideshowImage(DrawingContext dc){if(!slideshow||!SlideVisualEnabled||Cropping||current==null||currentMotion||largeRaster!=null)return false;var source=View.Image;if(source==null){if(previousSlide!=null){dc.DrawImage(previousSlide,SlideFit(previousSlide));return true;}return false;}var image=DisplayImage(source);double alpha=activeSlideTransition=="None"?1:Math.Clamp(((slidePausedAt??DateTime.UtcNow)-slideVisualStart).TotalSeconds/.5,0,1),progress=holdingSlide33?heldSlideProgress33:Math.Clamp(1-RemainingSeconds/Math.Max(.1,Config.SlideSeconds),0,1);
  dc.DrawRectangle(activeSlideBackground=="Auto"&&slideAutoColor!=null?slideAutoColor:Config.Oled?Brushes.Black:Ui.Canvas,null,new Rect(0,0,View.ActualWidth,View.ActualHeight));if(previousSlide!=null&&alpha<1){dc.PushOpacity(1-alpha);dc.DrawImage(previousSlide,SlideFit(previousSlide,activeSlideTransition=="Soft Zoom Fade"?1.04-.04*alpha:1));dc.Pop();}else previousSlide=null;
  if(activeSlideBackground=="Blur"&&slideBackground!=null){double f=Math.Max(View.ActualWidth/slideBackground.PixelWidth,View.ActualHeight/slideBackground.PixelHeight);dc.PushOpacity(.48*alpha);dc.DrawImage(slideBackground,new Rect((View.ActualWidth-slideBackground.PixelWidth*f)/2,(View.ActualHeight-slideBackground.PixelHeight*f)/2,slideBackground.PixelWidth*f,slideBackground.PixelHeight*f));dc.Pop();}
  dc.PushOpacity(alpha);if(activeSlideEffect=="Pan"){dc.DrawImage(image,PanFrame32(image.PixelWidth,image.PixelHeight,View.ActualWidth,View.ActualHeight,Config.SlideSeconds,progress,panDirection));}else dc.DrawImage(image,SlideFit(image,MotionZoom(activeSlideEffect,progress)));dc.Pop();return true;}
 void DrawSlideTimeline(DrawingContext dc){if(!Config.SlideTimeline)return;double progress;if(!slideshow)progress=Files.Count<=1?0:Index/(double)(Files.Count-1);else{if(!ReferenceEquals(timelineFiles,Files)){timelineFiles=Files;timelineIndices=Enumerable.Range(0,Files.Count).Where(i=>!VideoThumbnails.IsVideo(Files[i])).ToArray();}if(timelineIndices.Length==0)return;int before=Array.FindIndex(timelineIndices,i=>i>=Index);if(before<0)before=timelineIndices.Length;bool isVideo=current!=null&&VideoThumbnails.IsVideo(current);progress=isVideo?before/(double)timelineIndices.Length:(Math.Max(0,before)+Math.Clamp(1-RemainingSeconds/Math.Max(.1,Config.SlideSeconds),0,1))/timelineIndices.Length;}var r=new Rect(18,Math.Max(0,View.ActualHeight-(Config.Filmstrip&&!Config.FilmstripShrink&&strip.Visibility==Visibility.Visible?strip.Height+7:5)),Math.Max(0,View.ActualWidth-36),4.5);dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromArgb(160,200,200,200)),null,r,1,1);r.Width*=Math.Clamp(progress,0,1);dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(215,63,63)),null,r,1,1);}
}

