using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;
namespace gazegallery;
public static class TitleBar32 {
 public static readonly string[] ViewerFields={"Image position","Filename","File extension","Dimensions","File size","Folder name","Program name"};public static readonly string[] BoardFields={"Image count","Collage","Program name"};
 public static string Build(Settings c,string mode,string? file,string folder,int index,int count,int boardCount,int w,int h){var values=new Dictionary<string,string>();if(mode=="board"){values["Image count"]=$"[{boardCount}]";values["Collage"]="Collage";}else if(file!=null){values["Image position"]=$"[{index+1}/{count}]";values["Filename"]=Path.GetFileNameWithoutExtension(file);values["File extension"]=Path.GetExtension(file);values["Dimensions"]=w>0&&h>0?$"{w} × {h}":"";try{long bytes=new FileInfo(file).Length;values["File size"]=bytes>=1048576?$"{bytes/1048576d:0.##} MB":$"{bytes/1024d:0.##} KB";}catch{}values["Folder name"]=Path.GetFileName(folder.TrimEnd(Path.DirectorySeparatorChar)) is {Length:>0} n?n:folder;}values["Program name"]="gazegallery";var parts=new List<string>();var order=mode=="board"?c.CollageTitle:c.ViewerTitle;for(int i=0;i<order.Count;i++){string name=order[i];if(!values.TryGetValue(name,out var value)||value.Length==0)continue;if(name=="Filename"&&i+1<order.Count&&order[i+1]=="File extension"&&values.TryGetValue("File extension",out var ext)){value+=ext;i++;}parts.Add(value);}return string.Join(" — ",parts);}
}
public partial class MainWindow {
 UIElement TitleSettings32(){var panel=new StackPanel{Margin=new Thickness(16)};void Section(string title,string[] available,List<string> saved){panel.Children.Add(Ui.Label(title,16));var order=saved.Where(available.Contains).Concat(available.Where(n=>!saved.Contains(n))).ToList();var rows=new StackPanel();void Rebuild(){rows.Children.Clear();for(int n=0;n<order.Count;n++){int index=n;string name=order[n];var row=new WrapPanel();Ui.Check(row,name,saved.Contains(name),v=>{saved.Remove(name);if(v)saved.Add(name);Commit();});row.Children.Add(Ui.Button("↑",()=>Move(index,-1)));row.Children.Add(Ui.Button("↓",()=>Move(index,1)));rows.Children.Add(row);}}void Commit(){var enabled=saved.ToHashSet();saved.Clear();saved.AddRange(order.Where(enabled.Contains));Config.Save();UpdateTitle();}void Move(int i,int d){int j=i+d;if(j<0||j>=order.Count)return;(order[i],order[j])=(order[j],order[i]);Commit();Rebuild();}Rebuild();panel.Children.Add(rows);}Section("Image / video",TitleBar32.ViewerFields,Config.ViewerTitle);panel.Children.Add(new Separator());Section("Collage",TitleBar32.BoardFields,Config.CollageTitle);panel.Children.Add(Ui.Label("Uncheck every field for a blank title bar. Width and height stay together as Dimensions.",11));return new ScrollViewer{Content=panel};}
}
