using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using SkiaSharp;
namespace gazegallery;
public partial class MainWindow {
 public async Task VerifyRevision(){var report=new List<object>();int passed=0;var originalConfig=Config;string work=Path.Combine(Paths.Test,"_testing","revision-"+DateTime.Now.ToString("yyyyMMdd-HHmmss"));Directory.CreateDirectory(work);void Check(bool ok,string name){if(!ok)throw new Exception(name);passed++;report.Add(new{test=name,status="passed"});}async Task Case(string name,Func<Task> test){try{await test();}catch(Exception e){report.Add(new{test=name,status="failed",error=e.ToString()});Paths.Log("verification-failure",new{name,error=e.ToString()});if(Mode=="board"){ReleaseBoard();Mode="viewer";}}}
  Config=new Settings();SetupExperienceForTest();try{
 if(Environment.GetCommandLineArgs().Contains("--round23-only")){await Case("round23",()=>VerifyRound23(report,Check,work));return;}
  await Case("formats and animation",async()=>{foreach(string path in Directory.GetFiles(Paths.Test).Concat(Directory.GetFiles(Path.Combine(Paths.Test,"_testing","format-fixtures"))).Where(Paths.Motion)){await Open(path);var wait=Stopwatch.StartNew();while(View.Image==null&&wait.ElapsedMilliseconds<7000)await Task.Delay(50);Check(View.Image!=null,"Motion first frame: "+Path.GetFileName(path));if(Path.GetExtension(path)==".webp"){var before=View.Image;await Task.Delay(250);Check(View.Image!=before,"Animated WebP advances frames");}if(video!=null&&videoActive){video.Pause();await Task.Delay(300);Check(!video.Playing,"Pause: "+Path.GetFileName(path));long frame=video.FrameSerial;video.Step();await Task.Delay(300);Check(video.FrameSerial>frame,"Paused step decodes a new frame");if(video.CanPrevious){frame=video.FrameSerial;video.PreviousFrame();await Task.Delay(100);Check(video.FrameSerial>frame,"Previous step presents an actual buffered frame");}}await StopVideo();}
   using var bitmap=new SKBitmap(73,41);using(var canvas=new SKCanvas(bitmap))canvas.Clear(SKColors.Coral);string webp=Path.Combine(work,"static.webp");using(var data=SKImage.FromBitmap(bitmap).Encode(SKEncodedImageFormat.Webp,95))using(var f=File.Create(webp))data.SaveTo(f);await Open(webp);Check(View.Image?.PixelWidth==73,"Static WebP decode");string bmp=Path.Combine(work,"still.bmp");var enc=new BmpBitmapEncoder();enc.Frames.Add(BitmapFrame.Create(View.Image!));using(var f=File.Create(bmp))enc.Save(f);await Open(bmp);Check(View.Image?.PixelHeight==41,"BMP decode");});
  await Case("navigation and grid",async()=>{string collection=Path.Combine(Paths.Test,"24000");var sw=Stopwatch.StartNew();await Open(collection);report.Add(new{metric="real_folder_open_ms",value=sw.Elapsed.TotalMilliseconds,count=Files.Count});Check(Files.Count>=400,"Real stress collection indexed");string? start=current;await SetMode("grid");await Action("Next");await Action("Previous");Check(current==start,"Thumbnail next/previous preserve viewer");for(int i=0;i<6;i++){await Open(i%2==0?work:collection);await SetMode("grid");View.LayoutTiles();await Task.Delay(40);}await Open(collection);await SetMode("grid");Config.Columns=9;View.LayoutTiles();Check(View.ActualColumns==9,"Nine columns without tree");ShowFolders();Check(View.ActualColumns<9&&folderPanel.Width>=240,"Readable tree reserves layout space");ShowFolders();Config.Names=true;Config.Masonry=true;View.LayoutTiles();for(int i=0;i<12;i++){View.Scroll+=420;View.LayoutTiles();await Task.Delay(60);}var positions=View.Tiles.ToArray();View.Thumbs.Clear();View.LayoutTiles();Check(positions.SequenceEqual(View.Tiles),"Masonry positions unchanged after thumbnail eviction");Check(View.ToolTip==null,"No unintended tooltip");await SetMode("viewer");Check(View.ToolTip==null,"Thumbnail tooltip cleared on return");var requests=Enumerable.Range(0,30).Select(i=>ShowIndex(i)).ToArray();await Task.WhenAll(requests);Check(current==Files[29]&&View.Image!=null,"Rapid requests settle on final image");await ShowIndex(0);await Task.Delay(150);sw.Restart();await ShowIndex(1);report.Add(new{metric="warm_neighbor_ms",value=sw.Elapsed.TotalMilliseconds});Check(Cache.Bytes<=Cache.Budget||Cache.Count==1,"Image cache bounded");Check(ThumbCache.Bytes<=ThumbCache.Budget||ThumbCache.Count==1,"Thumbnail cache bounded");});
  await Case("3000 entry folder",async()=>{string stress=Path.Combine(Paths.Test,"_testing","stress-3000-small");Directory.CreateDirectory(stress);string seed=Path.Combine(Paths.Test,"small_mario.png");await Task.Run(()=>{for(int i=0;i<3000;i++){string target=Path.Combine(stress,$"item-{i:0000}.png");if(!File.Exists(target))File.Copy(seed,target);}});var sw=Stopwatch.StartNew();await Open(stress);Check(Files.Count==3000,"3000-entry enumeration");report.Add(new{metric="synthetic_3000_open_ms",value=sw.Elapsed.TotalMilliseconds});await SetMode("grid");View.Scroll=10000;View.LayoutTiles();await Task.Delay(300);Check(VisibleTiles<150,"3000-entry view only draws visible tiles");await SetMode("viewer");});
  await Case("collage and geometry",async()=>{await SetMode("board");var seeds=Directory.GetFiles(Paths.Test).Where(p=>!Paths.Motion(p)&&Paths.Media(p)).Take(3).ToArray();await ImportBoard(seeds,new Point(100,200));Check(View.Board.Count==3,"Collage imports three");Check(Math.Abs(View.Board[0].Rect.X+View.Board[0].Rect.Width/2-100)<.01&&Math.Abs(View.Board[1].Rect.X+View.Board[1].Rect.Width/2-124)<.01,"Import preserves drop position and staggers");var a=View.Board[0];var b=View.Board[1];View.BoardSelection.Add(a);View.BoardSelection.Add(b);var rect=a.Rect;var resized=GeometryRules.Resize(rect,rect.BottomRight,rect.BottomRight+new Vector(90,10),2,false);Check(resized.Width==rect.Width+90&&resized.Height==rect.Height+10,"Unlocked corner dimensions independent");var locked=GeometryRules.Resize(rect,rect.BottomRight,rect.BottomRight+new Vector(90,10),2,true);Check(Math.Abs(locked.Width/locked.Height-rect.Width/rect.Height)<.00001,"Locked aspect preserved");ClearBoard();Check(View.Board.Count==0,"Clear removes all");await Undo();Check(View.Board.Count==3,"Undo Clear restores all");NormalizeBoard();double min=View.Board.Min(i=>i.Rect.Width*i.Rect.Height),max=View.Board.Max(i=>i.Rect.Width*i.Rect.Height);Check(Math.Abs(max-min)<1,"Equal-area normalization");PackBoard();var items=View.Board.Select(i=>i.Clone()).ToArray();var bounds=items.Select(i=>i.Rect).Aggregate(Rect.Union);var export=await Sta.Run(()=>RenderBoard(items,bounds,2500));Check(Math.Max(export.PixelWidth,export.PixelHeight)==2500,"Export chosen size exact");View.BoardSelection=View.Board.ToHashSet();ResetBoardAspect();Check(View.Board.All(i=>Math.Abs(i.Rect.Width/i.Rect.Height-i.Image.PixelWidth/(double)i.Image.PixelHeight)<.001),"Reset aspect restores every selected source ratio");ReleaseBoard();Check(View.Board.Count==0&&View.BoardUndo.Count==0,"Collage release clears pixels and undo");Mode="viewer";});
  await Case("latest interaction state",async()=>{
   await Open(work);Config.FadeToolbar=true;await SetMode("grid");Check(toolbarHost.Opacity==0,"Thumbnail fade starts hidden");Config.ShowSubfolders=true;Directory.CreateDirectory(Path.Combine(work,"child"));RebuildGridPaths();Check(FolderTileCount==2&&GridPaths[1].EndsWith("child"),"Subfolders and Go up precede images");ShowFolders();await NavigateFolder(Path.Combine(work,"child"));Check(Mode=="grid"&&folderPanel.Visibility==Visibility.Visible,"Tree remains open when navigating folders");await NavigateFolder(work);ShowFolders();await SetMode("viewer");Config.FadeCollage=true;await SetMode("board");Check(toolbarHost.Opacity==0,"Collage fade starts hidden independently");var seed=Path.Combine(Paths.Test,"small_mario.png");await ImportBoard(Enumerable.Repeat(seed,4).ToArray(),new Point(200,200));PackBoard();Check(View.Board.Count==4&&Math.Abs(View.Board[0].Rect.Right+4)<.001&&Math.Abs(View.Board[1].Rect.Left-4)<.001&&Math.Abs(View.Board[2].Rect.Top-4)<.001,"Four image pack retains central gap");ReleaseBoard();Mode="viewer";
   string copySource=Path.Combine(work,"copy-source.png");File.Copy(seed,copySource,true);await Open(copySource);StartCrop();View.CropRect=new Rect(-2,-2,20,20);var area=View.CropRect;await SaveCropCopy();Check(current==copySource&&Cropping&&View.CropRect==area,"Save cropped copy retains original and crop selection");Check(File.Exists(Path.Combine(work,"copy-source_cropped_01.png")),"Cropped copy filename and file exist");CancelCrop();
   await Open(work);slideshow=true;Config.SlideSeconds=.1;slideDeadline=DateTime.Now.AddMilliseconds(-1);string? before=current;AdvanceTimedModes();await Task.Delay(250);slideshow=false;Check(current!=before,"Still slideshow advances on deadline");
   await Open(Path.Combine(Paths.Test,"September.mp4"));await Task.Delay(300);slideshow=true;slideDeadline=DateTime.Now.AddSeconds(-1);before=current;AdvanceTimedModes();await Task.Delay(250);Check(current==before,"Slideshow video ignores expired still interval");slideshow=false;await StopVideo();
   var viewerMenu=MenuOrder("viewer");var boardMenu=MenuOrder("board");Check(!ReferenceEquals(viewerMenu,boardMenu)&&viewerMenu.Contains("Settings")&&boardMenu.Contains("Settings"),"Mode menus independent and Settings retained");
  });
  if(!Environment.GetCommandLineArgs().Contains("--quick")) await Case("video collection",async()=>{var paths=Directory.GetFiles(Path.Combine(Paths.Test,"videos")).Where(Paths.Motion).ToArray();foreach(string path in paths){var sw=Stopwatch.StartNew();await Open(path);while(View.Image==null&&sw.ElapsedMilliseconds<7000)await Task.Delay(20);Check(View.Image!=null,"Video collection decode: "+Path.GetFileName(path));long before=video?.FrameSerial??0,decoded=video?.DecodedFrames??0;await Task.Delay(1200);report.Add(new{metric="video_frames_1_2s",file=Path.GetFileName(path),presented=(video?.FrameSerial??0)-before,decoded=(video?.DecodedFrames??0)-decoded,fps=video?.SourceFps});}await StopVideo();});
 await Case("file safety and undo",async()=>{bool guarded=false;try{Paths.Guard(Path.Combine(Paths.Root,"forbidden.jpg"));}catch(IOException){guarded=true;}Check(!guarded,"Normal file paths accepted without test guard");foreach(var pair in new[]{("x_09.png","x_0A.png"),("x_0F.png","x_10.png"),("x_FF.png","x_0100.png")})Check(Path.GetFileName(FileNames.Next(Path.Combine(work,pair.Item1)))==pair.Item2,"Hex counter "+pair.Item1);var ops=new FileOperations();string a=Path.Combine(work,"source.txt"),b=Path.Combine(work,"target.txt");File.WriteAllText(a,"source");File.WriteAllText(b,"target");var entry=new UndoEntry();entry.Changes.Add(await ops.Move(a,b,true));ops.Commit(entry);await ops.Undo();Check(File.ReadAllText(a)=="source"&&File.ReadAllText(b)=="target","Overwrite undo preserves both originals");try{if(Environment.GetCommandLineArgs().Contains("--skip-recycle"))throw new IOException("Recycling validated separately in normal desktop session");var tr=new UndoEntry();tr.Changes.Add(await ops.Trash(a));ops.Commit(tr);await ops.Undo();Check(File.ReadAllText(a)=="source","Recycle roundtrip exact file");}catch(Exception ex){Check(File.Exists(a)&&File.ReadAllText(a)=="source","Unavailable recycling retains source");report.Add(new{test="Recycle availability",status="blocked",error=ex.Message});}ops.Close();var source=ImageCache.Read(Directory.GetFiles(Paths.Test,"*.png").First(),0);var crop=CropPixels(source,new Rect(-12,-10,source.PixelWidth+24,source.PixelHeight+20));Check(crop.PixelWidth==source.PixelWidth+24,"Overcrop enlarges image");var px=new byte[4];crop.CopyPixels(new Int32Rect(0,0,1,1),px,4,0);Check(px[0]==24&&px[1]==24&&px[2]==24,"Overcrop background matches viewer");});
  await Case("daily changes",()=>VerifyDaily(report,Check,work));
 await Case("expanded features",()=>VerifyExpansion(report,Check,work));
 await Case("portable and scrolling",()=>VerifyRound22(report,Check,work));
 await Case("round23",()=>VerifyRound23(report,Check,work));
  }finally{await StopVideo();Config=originalConfig;Config.Save();File.WriteAllText(Path.Combine(Paths.Logs,"revision-results.json"),System.Text.Json.JsonSerializer.Serialize(new{passed,work,memoryMB=Process.GetCurrentProcess().WorkingSet64/1048576,report},new System.Text.Json.JsonSerializerOptions{WriteIndented=true}));shutdown=true;Close();}}
 void SetupExperienceForTest(){hasFolder=true;Config.Keys["Open with"]=new[]{"L"};Config.Keys["Equal area collage"]=new[]{"L"};Config.Keys["Pack collage"]=new[]{"P"};foreach(var command in pluginCommands)if(command.Shortcut.Length>0)Config.Keys["Plugin: "+command.Id+" / "+command.Title]=new[]{command.Shortcut};foreach(var pair in new[]{("Autoscroll thumbnails","Space"),("Copy thumbnails","Ctrl+C"),("Scroll up thumbnails","Up"),("Scroll down thumbnails","Down")})Config.Keys[pair.Item1]=new[]{pair.Item2};}
}






