using System;
using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace gazegallery;
// mpv owns decode, timestamps, audio synchronization, seeking and looping.
// Its render thread never calls core APIs or waits for the WPF dispatcher.
public sealed class Video : IDisposable {
 IntPtr core,renderer; readonly AutoResetEvent renderWake=new(false);readonly Thread renderThread,eventThread;readonly RenderCallback callback;volatile bool disposed,active,paused,ended;public volatile bool HasAudio;volatile int width=640,height=360;double time,length,fps;readonly object pixelsLock=new();byte[]? pixels;int pixelWidth,pixelHeight,pixelStride;bool changed;long epoch;public long FrameSerial,DecodedFrames;public readonly List<double> PresentationSamples=new();public readonly List<long> PresentationFrameIds=new();readonly Stopwatch clock=new();public event Action? FrameReady;
 readonly int renderLimit;
 public Video(bool thumbnail=false,int maxEdge=1920){renderLimit=maxEdge;core=mpv_create();if(core==IntPtr.Zero)throw new IOException("Cannot initialize video player");foreach(var pair in new[]{("config","no"),("vo","libmpv"),("hwdec","no"),("terminal","no"),("osd-level","0"),("sub","no"),("keep-open","yes"),("idle","yes"),("sw-fast","yes"),("demuxer-max-bytes","33554432"),("demuxer-max-back-bytes","8388608")})mpv_set_option_string(core,pair.Item1,pair.Item2);if(thumbnail){mpv_set_option_string(core,"audio","no");mpv_set_option_string(core,"vd-lavc-threads","1");mpv_set_option_string(core,"demuxer-max-bytes","2097152");mpv_set_option_string(core,"demuxer-max-back-bytes","0");}Check(mpv_initialize(core));IntPtr api=Marshal.StringToCoTaskMemUTF8("sw");try{Check(mpv_render_context_create(out renderer,core,new[]{new Param(1,api),new Param()}));}finally{Marshal.FreeCoTaskMem(api);}callback=_=>renderWake.Set();mpv_render_context_set_update_callback(renderer,callback,IntPtr.Zero);string[] props={"time-pos","duration","pause","eof-reached","video-out-params/dw","video-out-params/dh","container-fps"};for(int i=0;i<props.Length;i++)mpv_observe_property(core,(ulong)i+1,props[i],i is 2 or 3?3:i is 4 or 5?4:5);mpv_observe_property(core,8,"audio-params/channel-count",4);mpv_observe_property(core,9,"track-list/count",4);renderThread=new Thread(RenderLoop){IsBackground=true,Name="gazegallery video presentation"};eventThread=new Thread(EventLoop){IsBackground=true,Name="gazegallery media events"};renderThread.Start();eventThread.Start();}
 static void Check(int error){if(error<0)throw new IOException("Video player: "+Marshal.PtrToStringUTF8(mpv_error_string(error)));}
 void Set(string name,string value){if(!disposed)Check(mpv_set_property_string(core,name,value));}
 void Command(params string[] args){if(disposed)return;var values=new IntPtr[args.Length+1];for(int i=0;i<args.Length;i++)values[i]=Marshal.StringToCoTaskMemUTF8(args[i]);try{Check(mpv_command(core,values));}finally{foreach(var p in values)if(p!=IntPtr.Zero)Marshal.FreeCoTaskMem(p);}}
 public void Play(string path,bool mute,int volume,bool loop=true){Interlocked.Increment(ref epoch);lock(pixelsLock){PresentationSamples.Clear();PresentationFrameIds.Clear();changed=false;}HasAudio=false;DecodedFrames=0;clock.Restart();time=length=0;ended=false;paused=false;active=true;Set("pause","no");SetLoop(loop);Mute(mute);Volume(volume);Command("loadfile",path,"replace");}
 public bool Playing=>active&&!paused&&!ended;public bool Ended=>active&&ended;public bool CanPrevious=>active&&paused&&Time>0;public long Time=>(long)(Volatile.Read(ref time)*1000);public long Length=>(long)(Volatile.Read(ref length)*1000);public float SourceFps=>(float)Volatile.Read(ref fps);
 public void SetPaused(bool value){paused=value;Set("pause",value?"yes":"no");}public void SetAB(long? a,long? b){Set("ab-loop-a",a.HasValue?(a.Value/1000d).ToString("R",CultureInfo.InvariantCulture):"no");Set("ab-loop-b",b.HasValue?(b.Value/1000d).ToString("R",CultureInfo.InvariantCulture):"no");}public void SetLoop(bool loop)=>Set("loop-file",loop?"inf":"no");public void RestartLoop(){if(Ended)Seek(0);}public void Mute(bool mute)=>Set("mute",mute?"yes":"no");public void Volume(int volume)=>Set("volume",Math.Clamp(volume,0,100).ToString(CultureInfo.InvariantCulture));public void Pause(){paused=!paused;Set("pause",paused?"yes":"no");}public void Seek(long ms){ended=false;Command("seek",(Math.Max(0,ms)/1000.0).ToString("R",CultureInfo.InvariantCulture),"absolute+exact");}public void Step(){if(!Playing)Command("frame-step");}public void PreviousFrame(){if(!Playing)Command("frame-back-step");}
 public Task Stop(){active=false;Interlocked.Increment(ref epoch);return Task.Run(()=>{Command("stop");lock(pixelsLock){changed=false;pixels=null;}ended=false;});}
 void EventLoop(){while(!disposed){var ptr=mpv_wait_event(core,.1);if(ptr==IntPtr.Zero)continue;var ev=Marshal.PtrToStructure<Event>(ptr);if(ev.Id is 8 or 18)RefreshAudioTracks();if(ev.Id==22&&ev.Data!=IntPtr.Zero){var prop=Marshal.PtrToStructure<Property>(ev.Data);if(prop.Data==IntPtr.Zero){if(ev.User==8)HasAudio=false;continue;}switch(ev.User){case 9:RefreshAudioTracks();break;case 8:if(prop.Format==4)HasAudio=Marshal.ReadInt64(prop.Data)>0;break;case 1:if(prop.Format==5)Volatile.Write(ref time,Marshal.PtrToStructure<double>(prop.Data));break;case 2:if(prop.Format==5)Volatile.Write(ref length,Marshal.PtrToStructure<double>(prop.Data));break;case 3:if(prop.Format==3)paused=Marshal.ReadInt32(prop.Data)!=0;break;case 4:if(prop.Format==3)ended=Marshal.ReadInt32(prop.Data)!=0;break;case 5:if(prop.Format==4)width=Math.Max(1,(int)Marshal.ReadInt64(prop.Data));break;case 6:if(prop.Format==4)height=Math.Max(1,(int)Marshal.ReadInt64(prop.Data));break;case 7:if(prop.Format==5)Volatile.Write(ref fps,Marshal.PtrToStructure<double>(prop.Data));break;}}if(ev.Id==7&&ev.Data!=IntPtr.Zero){int reason=Marshal.ReadInt32(ev.Data),error=Marshal.ReadInt32(ev.Data,4);if(reason==4)Paths.Log("video-error",new{error,message=Marshal.PtrToStringUTF8(mpv_error_string(error))});}}}
 string PropertyText(string name){var value=mpv_get_property_string(core,name);if(value==IntPtr.Zero)return "";try{return Marshal.PtrToStringUTF8(value)??"";}finally{mpv_free(value);}}
 void RefreshAudioTracks(){bool found=false;if(int.TryParse(PropertyText("track-list/count"),out int count))for(int i=0;i<Math.Min(count,256);i++)if(PropertyText($"track-list/{i}/type")=="audio"){found=true;break;}HasAudio=found;}
 unsafe void RenderLoop(){IntPtr allocation=IntPtr.Zero,buffer=IntPtr.Zero;int capacity=0;IntPtr format=Marshal.StringToCoTaskMemUTF8("bgr0");int* size=stackalloc int[2];try{while(!disposed){renderWake.WaitOne(100);if(disposed)break;if((mpv_render_context_update(renderer)&1)==0)continue;FrameInfo info=new();mpv_render_context_get_info(renderer,new Param(11,(IntPtr)(&info)));long token=Interlocked.Read(ref epoch);int sw=width,sh=height;double scale=Math.Min(1,(double)renderLimit/Math.Max(sw,sh));int w=Math.Max(1,(int)(sw*scale)),h=Math.Max(1,(int)(sh*scale)),stride=(w*4+63)&~63,bytes=checked(stride*h);if(bytes>capacity){if(allocation!=IntPtr.Zero)Marshal.FreeHGlobal(allocation);allocation=Marshal.AllocHGlobal(bytes+63);buffer=new IntPtr((allocation.ToInt64()+63)&~63L);capacity=bytes;}size[0]=w;size[1]=h;long pitch=stride;var parameters=new[]{new Param(17,(IntPtr)size),new Param(18,format),new Param(19,(IntPtr)(&pitch)),new Param(20,buffer),new Param()};int result=mpv_render_context_render(renderer,parameters);mpv_render_context_report_swap(renderer);if(result<0||(info.Flags&1)==0||!active||token!=Interlocked.Read(ref epoch))continue;lock(pixelsLock){if(pixels==null||pixels.Length!=bytes)pixels=new byte[bytes];Marshal.Copy(buffer,pixels,0,bytes);pixelWidth=w;pixelHeight=h;pixelStride=stride;changed=true;DecodedFrames++;if((info.Flags&6)==0&&PresentationSamples.Count<4096){PresentationSamples.Add(clock.Elapsed.TotalMilliseconds);PresentationFrameIds.Add(DecodedFrames-1);}}FrameReady?.Invoke();}}catch(Exception ex){Paths.Log("video-render-error",ex.ToString());}finally{if(allocation!=IntPtr.Zero)Marshal.FreeHGlobal(allocation);Marshal.FreeCoTaskMem(format);}}
 public bool Update(ref WriteableBitmap? target){lock(pixelsLock){if(!changed||pixels==null)return false;if(target==null||target.PixelWidth!=pixelWidth||target.PixelHeight!=pixelHeight)target=new WriteableBitmap(pixelWidth,pixelHeight,96,96,PixelFormats.Bgr32,null);target.WritePixels(new Int32Rect(0,0,pixelWidth,pixelHeight),pixels,pixelStride,0);changed=false;FrameSerial++;return true;}}
 public void Dispose(){if(disposed)return;active=false;Command("stop");disposed=true;renderWake.Set();eventThread.Join();renderThread.Join();mpv_render_context_free(renderer);mpv_terminate_destroy(core);renderWake.Dispose();}
 [StructLayout(LayoutKind.Sequential)]struct FrameInfo {public ulong Flags;public long TargetTime;}
 [StructLayout(LayoutKind.Sequential)]struct Param {public int Type;public IntPtr Data;public Param(int type,IntPtr data){Type=type;Data=data;}}
 [StructLayout(LayoutKind.Sequential)]struct Event {public int Id,Error;public ulong User;public IntPtr Data;}
 [StructLayout(LayoutKind.Sequential)]struct Property {public IntPtr Name;public int Format;public IntPtr Data;}
 [UnmanagedFunctionPointer(CallingConvention.Cdecl)]delegate void RenderCallback(IntPtr context);
 const string Dll="libmpv-2.dll";
 static Video(){NativeLibrary.SetDllImportResolver(typeof(Video).Assembly,(name,assembly,search)=>name==Dll?NativeLibrary.Load(File.Exists(Path.Combine(AppContext.BaseDirectory,"runtime",Dll))?Path.Combine(AppContext.BaseDirectory,"runtime",Dll):Path.Combine(AppContext.BaseDirectory,Dll)):IntPtr.Zero);}
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern IntPtr mpv_get_property_string(IntPtr h,[MarshalAs(UnmanagedType.LPUTF8Str)]string name);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern void mpv_free(IntPtr value);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern IntPtr mpv_create();
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_initialize(IntPtr h);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern IntPtr mpv_error_string(int e);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_set_option_string(IntPtr h,[MarshalAs(UnmanagedType.LPUTF8Str)]string n,[MarshalAs(UnmanagedType.LPUTF8Str)]string v);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_set_property_string(IntPtr h,[MarshalAs(UnmanagedType.LPUTF8Str)]string n,[MarshalAs(UnmanagedType.LPUTF8Str)]string v);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_command(IntPtr h,IntPtr[] args);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_observe_property(IntPtr h,ulong user,[MarshalAs(UnmanagedType.LPUTF8Str)]string n,int format);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern IntPtr mpv_wait_event(IntPtr h,double seconds);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern void mpv_terminate_destroy(IntPtr h);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_render_context_create(out IntPtr r,IntPtr h,Param[] args);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern void mpv_render_context_set_update_callback(IntPtr r,RenderCallback callback,IntPtr context);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern ulong mpv_render_context_update(IntPtr r);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_render_context_get_info(IntPtr r,Param param);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern int mpv_render_context_render(IntPtr r,Param[] args);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern void mpv_render_context_report_swap(IntPtr r);
 [DllImport(Dll,CallingConvention=CallingConvention.Cdecl)]static extern void mpv_render_context_free(IntPtr r);
}

